import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getAdminFeedback, updateAdminFeedback, type FeedbackStatus } from '@/services/playerExperience';
import { useAppTheme } from '@/theme/ThemeProvider';

const STATUSES:FeedbackStatus[]=['new','reviewing','planned','resolved','closed'];
export default function AdminFeedbackScreen(){
 const{colors}=useAppTheme();const[status,setStatus]=useState<FeedbackStatus|null>('new');const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[working,setWorking]=useState<string|null>(null);const[notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{setLoading(true);setRows(await getAdminFeedback(status,200));}finally{setLoading(false);}},[status]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function update(id:string,next:FeedbackStatus){try{setWorking(id);await updateAdminFeedback(id,next,notes[id]??null);await load();}finally{setWorking(null);}}
 return <Screen title="Feedback • Admin" subtitle="Triagem de bugs, sugestões, balanceamento e UX enviados dentro do app.">
  <View style={styles.filters}><Pressable onPress={()=>setStatus(null)} style={[styles.filter,{borderColor:status===null?colors.accent:colors.border,backgroundColor:status===null?colors.accentSoft:colors.surface}]}><Text style={[styles.filterText,{color:colors.text}]}>TODOS</Text></Pressable>{STATUSES.map(s=><Pressable key={s} onPress={()=>setStatus(s)} style={[styles.filter,{borderColor:status===s?colors.accent:colors.border,backgroundColor:status===s?colors.accentSoft:colors.surface}]}><Text style={[styles.filterText,{color:colors.text}]}>{s.toUpperCase()}</Text></Pressable>)}</View>
  {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}<View style={styles.list}>{rows.map(r=><View key={r.id} style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.head}><View><Text style={[styles.category,{color:colors.accent}]}>{String(r.category).toUpperCase()}</Text><Text style={[styles.user,{color:colors.text}]}>@{r.username}</Text></View><Text style={[styles.status,{color:colors.yellow}]}>{String(r.status).toUpperCase()}</Text></View><Text style={[styles.message,{color:colors.text}]}>{r.message}</Text><Text style={[styles.meta,{color:colors.muted}]}>{r.route??'sem rota'} • app {r.appVersion??'—'} • {new Date(r.createdAt).toLocaleString('pt-BR')}</Text><TextInput multiline value={notes[r.id]??r.adminNote??''} onChangeText={v=>setNotes(n=>({...n,[r.id]:v}))} placeholder="Nota/resposta administrativa..." placeholderTextColor={colors.muted} style={[styles.note,{color:colors.text,backgroundColor:colors.surfaceAlt,borderColor:colors.border}]}/><View style={styles.actions}>{STATUSES.filter(s=>s!==r.status).map(s=><Pressable key={s} disabled={working===r.id} onPress={()=>void update(r.id,s)} style={[styles.action,{borderColor:s==='resolved'?'#4FB77F':s==='closed'?'#D96575':colors.accent}]}><Text style={[styles.actionText,{color:s==='resolved'?'#65D894':s==='closed'?'#FF8290':colors.accent}]}>{s.toUpperCase()}</Text></Pressable>)}</View></View>)}</View>
 </Screen>;
}
const styles=StyleSheet.create({filters:{flexDirection:'row',flexWrap:'wrap',gap:6},filter:{borderRadius:999,borderWidth:1,paddingHorizontal:9,paddingVertical:7},filterText:{fontSize:7,fontWeight:'900'},list:{gap:8},card:{borderRadius:17,borderWidth:1,padding:11},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},category:{fontSize:6.5,fontWeight:'900'},user:{fontSize:10,fontWeight:'900',marginTop:2},status:{fontSize:7,fontWeight:'900'},message:{fontSize:10,lineHeight:14,marginTop:8},meta:{fontSize:7,marginTop:5},note:{minHeight:70,borderRadius:12,borderWidth:1,padding:9,fontSize:8,textAlignVertical:'top',marginTop:8},actions:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:8},action:{minHeight:32,borderRadius:9,borderWidth:1,paddingHorizontal:7,alignItems:'center',justifyContent:'center'},actionText:{fontSize:6.5,fontWeight:'900'}});
