import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Switch, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getAdminFeatureFlags, setAdminFeatureFlag } from '@/services/playerExperience';
import { useAppTheme } from '@/theme/ThemeProvider';

const ROLLOUTS=[0,25,50,100];
export default function AdminFeatureFlagsScreen(){
 const{colors}=useAppTheme();const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[working,setWorking]=useState<string|null>(null);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setError(null);setRows(await getAdminFeatureFlags());}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar flags.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function patch(row:any,change:{enabled?:boolean;rolloutPercent?:number;testerOnly?:boolean}){try{setWorking(row.key);await setAdminFeatureFlag(row.key,change.enabled??row.enabled,change.rolloutPercent??row.rolloutPercent,change.testerOnly??row.testerOnly);await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível atualizar a flag.');}finally{setWorking(null);}}
 return <Screen title="Feature Flags" subtitle="Libere recursos gradualmente, apenas para testers ou desligue experimentos sem remover código.">
  <View style={[styles.warning,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Ionicons name="git-branch" size={22} color={colors.accent}/><Text style={[styles.warningText,{color:colors.muted}]}>Flags controlam recursos novos/experimentais. Sistemas críticos existentes não são desligados automaticamente por este painel.</Text></View>
  {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}{error?<Text style={styles.error}>{error}</Text>:null}
  <View style={styles.list}>{rows.map(row=><View key={row.key} style={[styles.card,{backgroundColor:colors.surface,borderColor:row.enabled?colors.accent:colors.border}]}><View style={styles.head}><View style={{flex:1}}><Text style={[styles.key,{color:colors.accent}]}>{row.key}</Text><Text style={[styles.name,{color:colors.text}]}>{row.name}</Text><Text style={[styles.desc,{color:colors.muted}]}>{row.description}</Text></View><Switch disabled={working===row.key||row.adminOnly} value={Boolean(row.enabled)} onValueChange={v=>void patch(row,{enabled:v})}/></View><View style={styles.badges}>{row.adminOnly?<Badge text="ADMIN ONLY" color="#FF5CCF"/>:null}{row.testerOnly?<Badge text="TESTERS" color="#F0C74E"/>:null}<Badge text={'ROLLOUT '+row.rolloutPercent+'%'} color="#5AA8FF"/></View>{!row.adminOnly?<><Text style={[styles.label,{color:colors.muted}]}>ROLLOUT</Text><View style={styles.rollouts}>{ROLLOUTS.map(v=><Pressable key={v} disabled={working===row.key} onPress={()=>void patch(row,{rolloutPercent:v})} style={[styles.rollout,{backgroundColor:row.rolloutPercent===v?colors.accentSoft:colors.surfaceAlt,borderColor:row.rolloutPercent===v?colors.accent:colors.border}]}><Text style={[styles.rolloutText,{color:colors.text}]}>{v}%</Text></Pressable>)}</View><Pressable disabled={working===row.key} onPress={()=>void patch(row,{testerOnly:!row.testerOnly})} style={[styles.tester,{borderColor:row.testerOnly?colors.yellow:colors.border}]}><Ionicons name="flask" size={16} color={row.testerOnly?colors.yellow:colors.muted}/><Text style={[styles.testerText,{color:colors.text}]}>{row.testerOnly?'Somente testers/admin':'Liberado conforme rollout'}</Text></Pressable></>:null}</View>)}</View>
 </Screen>;
}
function Badge({text,color}:{text:string;color:string}){return <View style={[styles.badge,{borderColor:color}]}><Text style={[styles.badgeText,{color}]}>{text}</Text></View>;}
const styles=StyleSheet.create({warning:{borderRadius:16,borderWidth:1,padding:10,flexDirection:'row',alignItems:'center',gap:8},warningText:{flex:1,fontSize:7.5,lineHeight:11},error:{color:'#FF9EAA',fontSize:9},list:{gap:8},card:{borderRadius:17,borderWidth:1,padding:11},head:{flexDirection:'row',alignItems:'center',gap:8},key:{fontSize:6.5,fontWeight:'900'},name:{fontSize:12,fontWeight:'900',marginTop:2},desc:{fontSize:7.5,lineHeight:11,marginTop:2},badges:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:8},badge:{borderWidth:1,borderRadius:999,paddingHorizontal:6,paddingVertical:3},badgeText:{fontSize:5.8,fontWeight:'900'},label:{fontSize:6.5,fontWeight:'900',marginTop:10},rollouts:{flexDirection:'row',gap:5,marginTop:5},rollout:{minWidth:50,minHeight:32,borderRadius:9,borderWidth:1,alignItems:'center',justifyContent:'center'},rolloutText:{fontSize:7,fontWeight:'900'},tester:{alignSelf:'flex-start',minHeight:34,borderRadius:10,borderWidth:1,paddingHorizontal:8,flexDirection:'row',alignItems:'center',gap:5,marginTop:7},testerText:{fontSize:7,fontWeight:'900'}});
