import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { useAppTheme } from '@/theme/ThemeProvider';
import { getAdventureHub, startAdventureBattle, type AdventureChallenge } from '@/services/adventure';

export default function AdventureChallengesScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[items,setItems]=useState<AdventureChallenge[]>([]);const[loading,setLoading]=useState(true);const[working,setWorking]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setItems((await getAdventureHub()).challenges)}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível carregar os desafios.')}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));
 async function fight(item:AdventureChallenge){if(working)return;try{setWorking(item.id);const result=await startAdventureBattle('challenge',item.id);router.push(result.route as any)}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível iniciar o desafio.')}finally{setWorking(null)}}
 return <Screen title="Desafios Especiais" subtitle="Regras diferentes forçam você a montar times novos em vez de usar sempre as mesmas cartas.">
  {notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{borderColor:colors.yellow,backgroundColor:colors.surface}]}><Text style={[styles.noticeText,{color:colors.text}]}>{notice}</Text><Ionicons name="close" size={16} color={colors.muted}/></Pressable>:null}
  {loading?<ActivityIndicator color={colors.accent}/>:items.map((item,index)=>{const complete=item.wins>0;const tone=complete?'#65D894':index===items.length-1?'#FFD447':colors.accent;return <View key={item.id} style={[styles.card,{backgroundColor:colors.surface,borderColor:tone}]}><View style={[styles.icon,{backgroundColor:tone+'1C'}]}><Ionicons name={item.requiredType?'filter':'flask'} size={24} color={tone}/></View><View style={{flex:1}}><View style={styles.head}><Text style={[styles.title,{color:colors.text}]}>{item.title}</Text><Text style={[styles.stars,{color:item.stars?'#FFD447':colors.muted}]}>{'★'.repeat(item.stars)}{'☆'.repeat(3-item.stars)}</Text></View><Text style={[styles.desc,{color:colors.muted}]}>{item.description}</Text><View style={styles.tags}>{item.requiredType?<Tag text={item.requiredType.toUpperCase()} color={tone}/>:<Tag text="EQUIPE LIVRE" color={tone}/>}<Tag text={`IA ${item.aiStyle.toUpperCase()}`} color={tone}/><Tag text={`FORÇA ${item.targetPower}`} color={tone}/></View><Text style={[styles.reward,{color:colors.muted}]}>Recompensa da 1ª vitória: 🪙 {item.rewardCoins.toLocaleString('pt-BR')} {item.rewardDiamonds?`• 💎 ${item.rewardDiamonds}`:''} • {item.wins} vitória(s){item.bestTurns?` • melhor ${item.bestTurns} turnos`:''}</Text></View><Pressable disabled={!!working} onPress={()=>void fight(item)} style={[styles.play,{backgroundColor:tone}]}>{working===item.id?<ActivityIndicator size="small" color="#07111F"/>:<Ionicons name={complete?'refresh':'flash'} size={16} color="#07111F"/>}<Text style={styles.playText}>{complete?'REPETIR':'JOGAR'}</Text></Pressable></View>})}
 </Screen>
}
function Tag({text,color}:{text:string;color:string}){return <View style={[styles.tag,{borderColor:color+'88',backgroundColor:color+'10'}]}><Text style={[styles.tagText,{color}]}>{text}</Text></View>}
const styles=StyleSheet.create({notice:{borderWidth:1,borderRadius:11,padding:10,flexDirection:'row'},noticeText:{flex:1,fontSize:11,fontWeight:'700'},card:{borderWidth:1,borderRadius:15,padding:12,flexDirection:'row',gap:10,alignItems:'center'},icon:{width:46,height:46,borderRadius:14,alignItems:'center',justifyContent:'center'},head:{flexDirection:'row',justifyContent:'space-between',gap:7},title:{fontSize:13,fontWeight:'900',flex:1},stars:{fontSize:9,letterSpacing:1},desc:{fontSize:9,lineHeight:13,marginTop:2},tags:{flexDirection:'row',flexWrap:'wrap',gap:4,marginTop:6},tag:{borderWidth:1,borderRadius:99,paddingHorizontal:6,paddingVertical:3},tagText:{fontSize:7,fontWeight:'900'},reward:{fontSize:8,marginTop:6},play:{borderRadius:10,paddingVertical:8,paddingHorizontal:8,alignItems:'center',gap:2},playText:{color:'#07111F',fontSize:7,fontWeight:'900'}});
