import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { listPacks, type Pack } from '@/services/packs';
import { autoOpenPacks, getBoosterPerks, type BoosterPerks } from '@/services/boosterPerks';
import { useWallet } from '@/wallet/WalletProvider';
import { useAppTheme } from '@/theme/ThemeProvider';
import { VIRTUAL_LIST_PERF_PROPS } from '@/performance/scrollPerformance';

const PRESETS=[10,25,50,75,100];
const TIER_OPTIONS=[0,4,5,6];
const ROW_HEIGHT=88;

export default function AutoOpenPlusScreen(){
  const router=useRouter(); const {colors}=useAppTheme(); const wallet=useWallet();
  const[packs,setPacks]=useState<Pack[]>([]); const[perks,setPerks]=useState<BoosterPerks|null>(null); const[selectedId,setSelectedId]=useState<string|null>(null);
  const[quantityText,setQuantityText]=useState('50'); const[valueText,setValueText]=useState(''); const[tier,setTier]=useState(0); const[pickerOpen,setPickerOpen]=useState(false); const[search,setSearch]=useState('');
  const[loading,setLoading]=useState(true); const[working,setWorking]=useState(false); const[error,setError]=useState<string|null>(null); const[result,setResult]=useState<any>(null);
  const load=useCallback(async()=>{try{setLoading(true);setError(null);const[p,perk]=await Promise.all([listPacks(),getBoosterPerks()]);setPacks(p);setPerks(perk);setSelectedId(current=>current&&p.some(x=>x.id===current)?current:p[0]?.id??null);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o Auto Booster+.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  const selected=useMemo(()=>packs.find(p=>p.id===selectedId)??null,[packs,selectedId]);
  const quantity=Math.max(1,Math.min(100,Number(quantityText.replace(/\D/g,''))||1));
  const stopValue=Number(valueText.replace(',','.'))>0?Number(valueText.replace(',','.')):null;
  const maxCost=selected?selected.price*quantity:0; const balance=selected?.currency==='diamonds'?wallet.diamonds:wallet.coins;
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?packs.filter(p=>p.name.toLowerCase().includes(q)||p.set_id.toLowerCase().includes(q)):packs;},[packs,search]);
  async function run(){if(!selected||!perks?.autoOpenPlusGamepass||working)return;if(balance<maxCost){setError('Saldo insuficiente para o limite máximo escolhido. Diminua a quantidade ou aumente o saldo.');return;}try{setWorking(true);setError(null);setResult(null);const r=await autoOpenPacks(selected.id,quantity,{stopAfterValueUsd:stopValue,stopAfterTier:tier||null});setResult(r);await Promise.all([wallet.refresh(),load()]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível concluir o Auto Booster+.');}finally{setWorking(false);}}
  function confirm(){if(!selected)return;const rules=[stopValue?`parar em carta ≥ US$ ${stopValue.toFixed(2)}`:null,tier?`parar em raridade Tier ${tier}+`:null].filter(Boolean).join(' ou ')||'sem parada antecipada';const msg=`Abrir até ${quantity}x ${selected.name}?\n\nCusto máximo: ${selected.currency==='diamonds'?'💎':'🪙'} ${maxCost.toLocaleString('pt-BR')}\nRegra: ${rules}.\n\nSe a regra disparar, o lote para antes e você só paga pelos boosters realmente abertos.`;if(Platform.OS==='web'){void run();return;}Alert.alert('Confirmar Auto Booster+',msg,[{text:'Cancelar',style:'cancel'},{text:'ABRIR',onPress:()=>void run()}]);}
  if(loading&&!perks)return <Screen title="Auto Booster+" subtitle="Automação avançada"><ActivityIndicator size="large" color={colors.yellow}/></Screen>;
  return <Screen title="Auto Booster+" subtitle="Até 100 boosters e parada automática por valor ou raridade.">
    <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
    <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:perks?.autoOpenPlusGamepass?'#59D49A':colors.yellow}]}><Ionicons name={perks?.autoOpenPlusGamepass?'rocket':'lock-closed'} size={30} color={perks?.autoOpenPlusGamepass?'#59D49A':colors.yellow}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>GAMEPASS AUTO BOOSTER+</Text><Text style={[styles.title,{color:colors.text}]}>{perks?.autoOpenPlusGamepass?'ATIVA':'NÃO ATIVA'}</Text><Text style={[styles.help,{color:colors.muted}]}>{perks?.autoOpenPlusGamepass?'Controle avançado: até 100 por lote e parada antecipada.':'Esta é uma Gamepass separada. A compra é em dinheiro real e a ativação é manual pelo dono.'}</Text></View></View>
    {!perks?.autoOpenPlusGamepass?<Pressable onPress={()=>router.push('/gamepasses')} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="diamond" size={18} color="#07111F"/><Text style={styles.primaryText}>VER GAMEPASSES</Text></Pressable>:null}
    {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.error}>{error}</Text></Pressable>:null}
    <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.text}]}>1. Booster</Text><Pressable onPress={()=>setPickerOpen(true)} style={[styles.pack,{backgroundColor:colors.surfaceAlt,borderColor:colors.accent}]}>{selected?.booster_art_url?<Image source={{uri:selected.booster_art_url}} style={styles.packImage} resizeMode="contain" resizeMethod="resize" fadeDuration={0}/>:<View style={styles.packImage}/>}<View style={{flex:1}}><Text numberOfLines={2} style={[styles.packName,{color:colors.text}]}>{selected?.name??'Escolha um booster'}</Text><Text style={[styles.packPrice,{color:colors.yellow}]}>{selected?(selected.currency==='diamonds'?'💎':'🪙')+' '+selected.price.toLocaleString('pt-BR'):'—'}</Text></View><Ionicons name="swap-horizontal" size={19} color={colors.accent}/></Pressable></View>
    <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.text}]}>2. Limite do lote</Text><View style={styles.presets}>{PRESETS.map(v=><Pressable key={v} onPress={()=>setQuantityText(String(v))} style={[styles.preset,{backgroundColor:quantity===v?colors.yellow:colors.surfaceAlt,borderColor:quantity===v?colors.yellow:colors.border}]}><Text style={[styles.presetText,{color:quantity===v?'#07111F':colors.text}]}>{v}x</Text></Pressable>)}</View><TextInput value={quantityText} onChangeText={v=>setQuantityText(v.replace(/\D/g,'').slice(0,3))} keyboardType="number-pad" maxLength={3} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/></View>
    <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.section,{color:colors.text}]}>3. Parada automática</Text><Text style={[styles.help,{color:colors.muted}]}>Opcional. Se qualquer regra abaixo acontecer, o servidor interrompe o lote imediatamente.</Text><TextInput value={valueText} onChangeText={setValueText} keyboardType="decimal-pad" placeholder="Parar se sair carta ≥ US$ ..." placeholderTextColor={colors.muted} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/><View style={styles.presets}>{TIER_OPTIONS.map(v=><Pressable key={v} onPress={()=>setTier(v)} style={[styles.preset,{backgroundColor:tier===v?colors.accentSoft:colors.surfaceAlt,borderColor:tier===v?colors.accent:colors.border}]}><Text style={[styles.presetText,{color:tier===v?colors.accent:colors.text}]}>{v===0?'SEM RARIDADE':`TIER ${v}+`}</Text></Pressable>)}</View></View>
    <View style={[styles.quote,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><View><Text style={[styles.quoteLabel,{color:colors.muted}]}>CUSTO MÁXIMO</Text><Text style={[styles.quoteValue,{color:colors.yellow}]}>{selected?.currency==='diamonds'?'💎':'🪙'} {maxCost.toLocaleString('pt-BR')}</Text></View><View style={{alignItems:'flex-end'}}><Text style={[styles.quoteLabel,{color:colors.muted}]}>LUCKY</Text><Text style={[styles.quoteSmall,{color:colors.text}]}>{perks?.lucky2xEnabled?'ATIVO':'PAUSADO'} • {perks?.lucky2xUses??0} carga(s)</Text></View></View>
    <Pressable disabled={!perks?.autoOpenPlusGamepass||!selected||working} onPress={confirm} style={[styles.primary,{backgroundColor:colors.yellow},(!perks?.autoOpenPlusGamepass||!selected||working)&&styles.disabled]}>{working?<ActivityIndicator color="#07111F"/>:<Ionicons name="rocket" size={19} color="#07111F"/>}<Text style={styles.primaryText}>{working?'ABRINDO...':`ABRIR ATÉ ${quantity}`}</Text></Pressable>
    {result?<View style={[styles.result,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={24} color="#59D49A"/><View style={{flex:1}}><Text style={styles.resultTitle}>{result.quantity} booster(s) aberto(s)</Text><Text style={styles.resultText}>{result.stopTriggered?`Parada automática: ${result.stopReason==='value'?'valor atingido':'raridade atingida'}. `:''}Maior valor encontrado: US$ {Number(result.highestValueUsd??0).toFixed(2)} • Tier máximo {result.highestRarityTier} • {result.cards?.length??0} cartas.</Text></View></View>:null}
    <Modal visible={pickerOpen} transparent animationType="fade" onRequestClose={()=>setPickerOpen(false)}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setPickerOpen(false)}/><View style={[styles.picker,{backgroundColor:colors.bg,borderColor:colors.border}]}><View style={styles.pickerHead}><Text style={[styles.pickerTitle,{color:colors.text}]}>Escolher booster</Text><Pressable onPress={()=>setPickerOpen(false)}><Ionicons name="close" size={23} color={colors.text}/></Pressable></View><View style={[styles.search,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Buscar booster ou set..." placeholderTextColor={colors.muted} style={[styles.searchInput,{color:colors.text}]}/></View><FlatList {...VIRTUAL_LIST_PERF_PROPS} data={filtered} keyExtractor={p=>p.id} getItemLayout={(_,index)=>({length:ROW_HEIGHT,offset:ROW_HEIGHT*index,index})} contentContainerStyle={styles.list} renderItem={({item})=><Pressable onPress={()=>{setSelectedId(item.id);setPickerOpen(false);setSearch('');}} style={[styles.row,{backgroundColor:colors.surface,borderColor:item.id===selectedId?colors.accent:colors.border}]}>{item.booster_art_url?<Image source={{uri:item.booster_art_url}} style={styles.rowImage} resizeMode="contain" resizeMethod="resize" fadeDuration={0}/>:<View style={styles.rowImage}/>}<View style={{flex:1}}><Text numberOfLines={2} style={[styles.rowName,{color:colors.text}]}>{item.name}</Text><Text style={[styles.rowMeta,{color:colors.yellow}]}>{item.currency==='diamonds'?'💎':'🪙'} {item.price.toLocaleString('pt-BR')}</Text></View></Pressable>}/></View></View></Modal>
  </Screen>;
}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',gap:7,alignItems:'center'},backText:{fontSize:11,fontWeight:'800'},hero:{borderRadius:20,borderWidth:1,padding:14,flexDirection:'row',alignItems:'center',gap:11},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},title:{fontSize:20,fontWeight:'900',marginTop:2},help:{fontSize:8.5,lineHeight:13,marginTop:2},notice:{borderRadius:13,borderWidth:1,padding:10,flexDirection:'row',gap:8},error:{color:'#FFD7DD',flex:1,fontSize:9},panel:{borderRadius:18,borderWidth:1,padding:12,gap:9},section:{fontSize:15,fontWeight:'900'},pack:{borderRadius:14,borderWidth:1,padding:9,flexDirection:'row',alignItems:'center',gap:10},packImage:{width:55,height:70},packName:{fontSize:11,fontWeight:'900'},packPrice:{fontSize:9,fontWeight:'900',marginTop:3},presets:{flexDirection:'row',gap:6,flexWrap:'wrap'},preset:{minHeight:36,borderRadius:10,borderWidth:1,paddingHorizontal:10,alignItems:'center',justifyContent:'center'},presetText:{fontSize:8,fontWeight:'900'},input:{height:46,borderRadius:12,borderWidth:1,paddingHorizontal:11,fontSize:11},quote:{borderRadius:15,borderWidth:1,padding:12,flexDirection:'row',justifyContent:'space-between',gap:10},quoteLabel:{fontSize:7,fontWeight:'900'},quoteValue:{fontSize:20,fontWeight:'900',marginTop:2},quoteSmall:{fontSize:8,fontWeight:'900',marginTop:3},primary:{minHeight:48,borderRadius:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},primaryText:{color:'#07111F',fontSize:9,fontWeight:'900'},disabled:{opacity:.4},result:{borderRadius:15,borderWidth:1,padding:11,flexDirection:'row',gap:9},resultTitle:{color:'#D9FFEC',fontSize:11,fontWeight:'900'},resultText:{color:'#A7EBC8',fontSize:8,lineHeight:12,marginTop:3},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.7)',justifyContent:'flex-end'},picker:{height:'82%',borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1},pickerHead:{padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},pickerTitle:{fontSize:22,fontWeight:'900'},search:{height:44,borderRadius:12,borderWidth:1,marginHorizontal:12,flexDirection:'row',gap:7,alignItems:'center',paddingHorizontal:10},searchInput:{flex:1,height:'100%',fontSize:10},list:{padding:12,gap:6,paddingBottom:28},row:{height:82,borderRadius:13,borderWidth:1,padding:7,flexDirection:'row',alignItems:'center',gap:9},rowImage:{width:48,height:68},rowName:{fontSize:10,fontWeight:'900'},rowMeta:{fontSize:8,fontWeight:'900',marginTop:3}});
