import { VIRTUAL_LIST_PERF_PROPS } from '@/performance/scrollPerformance';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { getMyBagOverview, getMyBagPage, type BagSortMode } from '@/services/bag';
import type { OwnedCardEntry } from '@/services/player';
import { createBagProFolder, deleteBagProFolder, deleteBagProPreset, getBagProDashboard, getBagProFolderCards, saveBagProPreset, setBagProFolderCard, type BagProDashboard, type BagProFolder } from '@/services/proGamepasses';
import { useAppTheme } from '@/theme/ThemeProvider';

const SORTS = [
  {id:'recent',label:'RECENTES'}, {id:'name',label:'NOME'}, {id:'value',label:'VALOR'},
  {id:'damage',label:'DANO'}, {id:'hp',label:'HP'}, {id:'quantity',label:'QUANTIDADE'}, {id:'rarity',label:'RARIDADE'},
] as const;
const QUICK = [{id:'all',label:'TODAS'},{id:'favorites',label:'FAVORITAS'},{id:'duplicates',label:'REPETIDAS'}] as const;

function rarityScore(value?: string | null){const r=(value??'').toLowerCase();if(r.includes('hyper')||r.includes('secret')||r.includes('special illustration'))return 7;if(r.includes('ultra')||r.includes('illustration'))return 6;if(r.includes('double rare'))return 5;if(r.includes('rare')||r.includes('holo'))return 4;if(r.includes('uncommon'))return 2;return 1;}

export default function BagProScreen(){
  const router=useRouter(); const{colors}=useAppTheme();
  const[data,setData]=useState<BagProDashboard|null>(null); const[loading,setLoading]=useState(true); const[working,setWorking]=useState(false); const[error,setError]=useState<string|null>(null); const[notice,setNotice]=useState<string|null>(null);
  const[name,setName]=useState(''); const[search,setSearch]=useState(''); const[setQuery,setSetQuery]=useState(''); const[type,setType]=useState(''); const[rarity,setRarity]=useState(''); const[quick,setQuick]=useState<'all'|'favorites'|'duplicates'>('all'); const[sort,setSort]=useState<(typeof SORTS)[number]['id']>('recent');
  const[types,setTypes]=useState<string[]>([]); const[rarities,setRarities]=useState<string[]>([]); const[preview,setPreview]=useState<OwnedCardEntry[]>([]); const[previewTotal,setPreviewTotal]=useState(0); const[previewLoading,setPreviewLoading]=useState(false);
  const[folder,setFolder]=useState<BagProFolder|null>(null); const[folderCards,setFolderCards]=useState<Set<string>>(new Set()); const[folderSearch,setFolderSearch]=useState(''); const[folderPool,setFolderPool]=useState<OwnedCardEntry[]>([]); const[folderLoading,setFolderLoading]=useState(false); const[newFolder,setNewFolder]=useState('');

  const load=useCallback(async()=>{try{setLoading(true);setError(null);const[d,o]=await Promise.all([getBagProDashboard(),getMyBagOverview()]);setData(d);setTypes(o.types??[]);setRarities(o.rarities??[]);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o Bag Pro.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();},[load]));

  async function previewFilters(filters?:Record<string,any>,sortOverride?:string){
    const f=filters??{search,setQuery,quickFilter:quick,typeFilter:type||null,rarityFilter:rarity||null,generation:null}; const s=sortOverride??sort;
    try{setPreviewLoading(true);const page=await getMyBagPage(0,60,{search:String(f.search??''),setQuery:String(f.setQuery??''),quickFilter:(f.quickFilter??'all') as any,typeFilter:f.typeFilter?String(f.typeFilter):null,rarityFilter:f.rarityFilter?String(f.rarityFilter):null,generation:null,sortMode:(s==='rarity'?'name':s) as BagSortMode});let items=page.items;if(s==='rarity')items=[...items].sort((a,b)=>rarityScore(b.cards?.rarity)-rarityScore(a.cards?.rarity)||String(a.cards?.pokemon_name??'').localeCompare(String(b.cards?.pokemon_name??'')));setPreview(items);setPreviewTotal(page.totalFiltered);}catch(e){setError(e instanceof Error?e.message:'Não foi possível aplicar o preset.');}finally{setPreviewLoading(false);}
  }

  async function savePreset(){if(!name.trim())return;try{setWorking(true);await saveBagProPreset({name:name.trim(),filters:{search,setQuery,quickFilter:quick,typeFilter:type||null,rarityFilter:rarity||null,generation:null},sortMode:sort});setName('');setNotice('Preset salvo no Bag Pro.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o preset.');}finally{setWorking(false);}}
  async function usePreset(p:any){setSearch(String(p.filters?.search??''));setSetQuery(String(p.filters?.setQuery??''));setQuick((p.filters?.quickFilter??'all') as any);setType(String(p.filters?.typeFilter??''));setRarity(String(p.filters?.rarityFilter??''));setSort((p.sortMode??'recent') as any);await previewFilters(p.filters,p.sortMode);}
  async function removePreset(id:string){try{setWorking(true);await deleteBagProPreset(id);await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível excluir.');}finally{setWorking(false);}}
  async function addFolder(){if(!newFolder.trim())return;try{setWorking(true);await createBagProFolder(newFolder.trim());setNewFolder('');setNotice('Pasta criada.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a pasta.');}finally{setWorking(false);}}
  async function openFolder(f:BagProFolder){setFolder(f);setFolderSearch('');try{setFolderLoading(true);const[cards,page]=await Promise.all([getBagProFolderCards(f.id),getMyBagPage(0,60,{search:'',setQuery:'',quickFilter:'all',typeFilter:null,rarityFilter:null,generation:null,sortMode:'recent'})]);setFolderCards(new Set(cards.map(c=>c.id)));setFolderPool(page.items);}catch(e){setError(e instanceof Error?e.message:'Não foi possível abrir a pasta.');setFolder(null);}finally{setFolderLoading(false);}}
  async function searchFolderCards(q:string){setFolderSearch(q);if(!folder)return;try{setFolderLoading(true);const page=await getMyBagPage(0,60,{search:q,setQuery:'',quickFilter:'all',typeFilter:null,rarityFilter:null,generation:null,sortMode:'name'});setFolderPool(page.items);}finally{setFolderLoading(false);}}
  async function toggleFolderCard(cardId:string){if(!folder||working)return;const enabled=!folderCards.has(cardId);try{setWorking(true);await setBagProFolderCard(folder.id,cardId,enabled);setFolderCards(current=>{const next=new Set(current);if(enabled)next.add(cardId);else next.delete(cardId);return next;});await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar a pasta.');}finally{setWorking(false);}}
  async function removeFolder(id:string){try{setWorking(true);await deleteBagProFolder(id);if(folder?.id===id)setFolder(null);await load();}finally{setWorking(false);}}

  const chips=(items:string[],active:string,setter:(v:string)=>void)=>items.slice(0,12).map(v=><Pressable key={v} onPress={()=>setter(active===v?'':v)} style={[styles.chip,{backgroundColor:active===v?colors.accentSoft:colors.surfaceAlt,borderColor:active===v?colors.accent:colors.border}]}><Text style={[styles.chipText,{color:active===v?colors.accent:colors.muted}]}>{v.toUpperCase()}</Text></Pressable>);

  return <Screen title="Bag Pro" subtitle="Pastas, filtros salvos e ordenações avançadas para a sua coleção.">
    <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
    <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.accent}]}><Ionicons name="briefcase" size={30} color={colors.accent}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>BAG PRO ATIVA</Text><Text style={[styles.heroTitle,{color:colors.text}]}>Organização sem procurar carta por carta</Text><Text style={[styles.helper,{color:colors.muted}]}>Até 30 presets e 30 pastas. As listas usam renderização virtualizada.</Text></View></View>
    {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.error}>{error}</Text></Pressable>:null}
    {notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={18} color="#59D49A"/><Text style={[styles.error,{color:'#D9FFEC'}]}>{notice}</Text></Pressable>:null}
    {loading&&!data?<ActivityIndicator size="large" color={colors.yellow}/>:null}

    <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Novo preset</Text><View style={styles.row}><TextInput value={name} onChangeText={setName} placeholder="Nome do preset" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/><TextInput value={search} onChangeText={setSearch} placeholder="Buscar Pokémon" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/><TextInput value={setQuery} onChangeText={setSetQuery} placeholder="Set" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/></View>
      <Text style={[styles.label,{color:colors.muted}]}>VISÃO</Text><View style={styles.chips}>{QUICK.map(x=><Pressable key={x.id} onPress={()=>setQuick(x.id)} style={[styles.chip,{backgroundColor:quick===x.id?colors.accentSoft:colors.surfaceAlt,borderColor:quick===x.id?colors.accent:colors.border}]}><Text style={[styles.chipText,{color:quick===x.id?colors.accent:colors.muted}]}>{x.label}</Text></Pressable>)}</View>
      <Text style={[styles.label,{color:colors.muted}]}>ORDENAR</Text><View style={styles.chips}>{SORTS.map(x=><Pressable key={x.id} onPress={()=>setSort(x.id)} style={[styles.chip,{backgroundColor:sort===x.id?colors.accentSoft:colors.surfaceAlt,borderColor:sort===x.id?colors.accent:colors.border}]}><Text style={[styles.chipText,{color:sort===x.id?colors.accent:colors.muted}]}>{x.label}</Text></Pressable>)}</View>
      <Text style={[styles.label,{color:colors.muted}]}>TIPO</Text><View style={styles.chips}>{chips(types,type,setType)}</View><Text style={[styles.label,{color:colors.muted}]}>RARIDADE</Text><View style={styles.chips}>{chips(rarities,rarity,setRarity)}</View>
      <View style={styles.actions}><Pressable disabled={working} onPress={()=>void previewFilters()} style={[styles.secondary,{borderColor:colors.accent}]}><Ionicons name="eye" size={17} color={colors.accent}/><Text style={[styles.secondaryText,{color:colors.accent}]}>TESTAR FILTRO</Text></Pressable><Pressable disabled={working||!name.trim()} onPress={()=>void savePreset()} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="save" size={17} color="#07111F"/><Text style={styles.primaryText}>SALVAR PRESET</Text></Pressable></View>
    </View>

    {data?.presets?.length?<><Text style={[styles.sectionTitle,{color:colors.text}]}>Presets salvos</Text><View style={styles.stack}>{data.presets.map(p=><View key={p.id} style={[styles.item,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="options" size={20} color={colors.accent}/><Pressable onPress={()=>void usePreset(p)} style={{flex:1}}><Text style={[styles.itemTitle,{color:colors.text}]}>{p.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{String(p.sortMode).toUpperCase()} • toque para aplicar</Text></Pressable><Pressable onPress={()=>void removePreset(p.id)}><Ionicons name="trash" size={18} color="#FF8998"/></Pressable></View>)}</View></>:null}

    {previewLoading?<ActivityIndicator color={colors.yellow}/>:preview.length?<><Text style={[styles.sectionTitle,{color:colors.text}]}>Prévia • {preview.length}/{previewTotal}</Text><View style={styles.previewGrid}>{preview.slice(0,18).map(item=><Pressable key={item.cards?.id} onPress={()=>item.cards?.id&&router.push(('/card/'+item.cards.id) as never)} style={[styles.previewCard,{backgroundColor:colors.surface,borderColor:colors.border}]}>{item.cards?.image_small?<Image source={{uri:item.cards.image_small}} style={styles.previewImage} resizeMode="contain"/>:null}<Text numberOfLines={1} style={[styles.cardName,{color:colors.text}]}>{item.cards?.pokemon_name??'Carta'}</Text><Text style={[styles.meta,{color:colors.muted}]}>{item.quantity}x • {item.cards?.rarity??'—'}</Text></Pressable>)}</View></>:null}

    <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Pastas de coleção</Text><View style={styles.row}><TextInput value={newFolder} onChangeText={setNewFolder} onSubmitEditing={()=>void addFolder()} placeholder="Ex.: Favoritas para batalha" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/><Pressable disabled={working||!newFolder.trim()} onPress={()=>void addFolder()} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="folder-open" size={17} color="#07111F"/><Text style={styles.primaryText}>CRIAR</Text></Pressable></View>
      <View style={styles.stack}>{data?.folders.map(f=><View key={f.id} style={[styles.item,{backgroundColor:colors.surfaceAlt,borderColor:colors.border}]}><Ionicons name="folder" size={21} color={colors.yellow}/><Pressable onPress={()=>void openFolder(f)} style={{flex:1}}><Text style={[styles.itemTitle,{color:colors.text}]}>{f.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{f.count} carta(s) • abrir pasta</Text></Pressable><Pressable onPress={()=>void removeFolder(f.id)}><Ionicons name="trash-outline" size={18} color="#FF8998"/></Pressable></View>)}</View>
    </View>

    <Modal visible={Boolean(folder)} animationType="slide" onRequestClose={()=>setFolder(null)}><View style={[styles.modal,{backgroundColor:colors.bg}]}><View style={styles.modalHead}><View><Text style={[styles.kicker,{color:colors.yellow}]}>PASTA BAG PRO</Text><Text style={[styles.modalTitle,{color:colors.text}]}>{folder?.name}</Text></View><Pressable onPress={()=>setFolder(null)}><Ionicons name="close" size={25} color={colors.text}/></Pressable></View><View style={[styles.searchBox,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={folderSearch} onChangeText={v=>void searchFolderCards(v)} placeholder="Buscar na sua Bag..." placeholderTextColor={colors.muted} style={[styles.searchInput,{color:colors.text}]}/></View>{folderLoading?<ActivityIndicator color={colors.yellow}/>:null}<FlatList {...VIRTUAL_LIST_PERF_PROPS} data={folderPool} keyExtractor={(i,idx)=>i.cards?.id??String(idx)} contentContainerStyle={styles.list} renderItem={({item})=>{const id=item.cards?.id;const active=Boolean(id&&folderCards.has(id));return <Pressable disabled={!id||working} onPress={()=>id&&void toggleFolderCard(id)} style={[styles.cardRow,{backgroundColor:colors.surface,borderColor:active?colors.yellow:colors.border}]}>{item.cards?.image_small?<Image source={{uri:item.cards.image_small}} style={styles.rowImage} resizeMode="contain"/>:<View style={styles.rowImage}/>}<View style={{flex:1}}><Text style={[styles.itemTitle,{color:colors.text}]}>{item.cards?.pokemon_name??'Carta'}</Text><Text style={[styles.meta,{color:colors.muted}]}>{item.cards?.rarity??'—'} • {item.quantity}x</Text></View><Ionicons name={active?'checkmark-circle':'add-circle-outline'} size={23} color={active?colors.yellow:colors.accent}/></Pressable>;}}/></View></Modal>
  </Screen>;
}

const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},hero:{borderWidth:1,borderRadius:20,padding:15,flexDirection:'row',gap:11,alignItems:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},heroTitle:{fontSize:18,fontWeight:'900',marginTop:2},helper:{fontSize:9,lineHeight:14,marginTop:3},notice:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',alignItems:'center',gap:8},error:{flex:1,color:'#FFD7DD',fontSize:9,fontWeight:'800'},panel:{borderWidth:1,borderRadius:18,padding:13,gap:9},title:{fontSize:17,fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900'},label:{fontSize:7,fontWeight:'900',letterSpacing:.8},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},input:{flex:1,minWidth:150,height:44,borderWidth:1,borderRadius:11,paddingHorizontal:11},chips:{flexDirection:'row',gap:6,flexWrap:'wrap'},chip:{minHeight:34,paddingHorizontal:9,borderWidth:1,borderRadius:999,alignItems:'center',justifyContent:'center'},chipText:{fontSize:7,fontWeight:'900'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{minHeight:42,paddingHorizontal:12,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},primaryText:{color:'#07111F',fontSize:8,fontWeight:'900'},secondary:{minHeight:42,paddingHorizontal:12,borderRadius:11,borderWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},secondaryText:{fontSize:8,fontWeight:'900'},stack:{gap:7},item:{minHeight:58,borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',alignItems:'center',gap:9},itemTitle:{fontSize:10,fontWeight:'900'},meta:{fontSize:7.5,marginTop:2},previewGrid:{flexDirection:'row',flexWrap:'wrap',gap:7},previewCard:{flexBasis:115,flexGrow:1,maxWidth:160,borderWidth:1,borderRadius:12,padding:7},previewImage:{width:'100%',height:120},cardName:{fontSize:9,fontWeight:'900',marginTop:4},modal:{flex:1,paddingTop:45},modalHead:{padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{fontSize:24,fontWeight:'900'},searchBox:{marginHorizontal:12,minHeight:45,borderRadius:12,borderWidth:1,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10},searchInput:{flex:1},list:{padding:12,gap:7},cardRow:{minHeight:78,borderWidth:1,borderRadius:13,padding:8,flexDirection:'row',alignItems:'center',gap:9},rowImage:{width:48,height:64}});
