import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getBattleLeaderboard, getMyBattleHistory, rematchBattle } from '@/services/battles';
import { getMyProfile } from '@/services/player';
import { getTrainerRank } from '@/services/ranks';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function BattlesHubScreen(){
  const router=useRouter();const{colors}=useAppTheme();
  const[profile,setProfile]=useState<any>(null);const[history,setHistory]=useState<any[]>([]);const[leaderboard,setLeaderboard]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[working,setWorking]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setLoading(true);const[p,h,l]=await Promise.all([getMyProfile(),getMyBattleHistory(),getBattleLeaderboard(25)]);setProfile(p);setHistory(h);setLeaderboard(l);}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível carregar as batalhas.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  const completed=useMemo(()=>history.filter(x=>x.status==='completed'),[history]);
  const myRank=getTrainerRank(profile?.battle_rating);
  const wins=completed.filter(x=>x.winner_id===profile?.id).length;const losses=completed.length-wins;const winRate=completed.length?Math.round(wins/completed.length*100):0;
  async function rematch(id:string){try{setWorking(id);const next=await rematchBattle(id);router.push(`/battle/${next}`);}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível criar a revanche.');}finally{setWorking(null);}}
  return <Screen title="Battle Center" subtitle="Histórico, ranking ELO, estatísticas e revanche.">
    <Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
    {notice?<Pressable style={styles.notice} onPress={()=>setNotice(null)}><Ionicons name="information-circle" size={18} color={colors.yellow}/><Text style={styles.noticeText}>{notice}</Text></Pressable>:null}
    {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}
    <View style={[styles.hero,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><View><Text style={[styles.kicker,{color:colors.yellow}]}>RANKED RATING</Text><Text style={[styles.rating,{color:colors.text}]}>{profile?.battle_rating??1000}</Text><Text style={[styles.rankLabel,{color:colors.muted}]}>{myRank.symbol} {myRank.displayName}</Text></View><View style={styles.heroStats}><Mini value={profile?.battle_wins??wins} label="Vitórias"/><Mini value={profile?.battle_losses??losses} label="Derrotas"/><Mini value={`${winRate}%`} label="Win rate"/><Mini value={profile?.best_battle_streak??0} label="Melhor streak"/></View></View>
    <View style={styles.sectionHead}><Text style={[styles.sectionTitle,{color:colors.text}]}>Ranking</Text><Text style={[styles.sectionMeta,{color:colors.muted}]}>TOP {leaderboard.length}</Text></View>
    <View style={styles.list}>{leaderboard.map((p,index)=>{const visible=p.id===profile?.id||p.show_battle_rating!==false;const rank=getTrainerRank(p.battle_rating);return <View key={p.id} style={[styles.rankRow,{backgroundColor:colors.surface,borderColor:p.id===profile?.id?colors.accent:colors.border}]}><View style={[styles.position,{backgroundColor:index<3?colors.accentSoft:colors.surfaceAlt}]}><Text style={[styles.positionText,{color:index<3?colors.accent:colors.muted}]}>{index+1}</Text></View><View style={styles.grow}><Text style={[styles.name,{color:colors.text}]}>{visible?rank.symbol+' ':''}@{p.username}{p.id===profile?.id?' • você':''}</Text><Text style={[styles.sub,{color:colors.muted}]}>{visible?rank.displayName:'ELO oculto'} • {p.battle_wins}V • {p.battle_losses}D • streak {p.battle_streak}</Text></View><Text style={[styles.elo,{color:colors.yellow}]}>{visible?p.battle_rating:'•••'}</Text></View>})}</View>
    <View style={styles.sectionHead}><Text style={[styles.sectionTitle,{color:colors.text}]}>Minhas batalhas</Text><Text style={[styles.sectionMeta,{color:colors.muted}]}>{history.length}</Text></View>
    {!loading&&history.length===0?<View style={[styles.empty,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="game-controller-outline" size={35} color={colors.muted}/><Text style={[styles.emptyTitle,{color:colors.text}]}>Nenhuma batalha ainda</Text><Text style={[styles.emptyText,{color:colors.muted}]}>Desafie um amigo pelo chat.</Text></View>:null}
    <View style={styles.list}>{history.map(item=>{const mineChallenger=item.challenger_id===profile?.id;const opponent=mineChallenger?(Array.isArray(item.opponent)?item.opponent[0]:item.opponent):(Array.isArray(item.challenger)?item.challenger[0]:item.challenger);const won=item.status==='completed'&&item.winner_id===profile?.id;const before=mineChallenger?item.challenger_rating_before:item.opponent_rating_before;const after=mineChallenger?item.challenger_rating_after:item.opponent_rating_after;const delta=before!=null&&after!=null?Number(after)-Number(before):0;return <View key={item.id} style={[styles.battleRow,{backgroundColor:colors.surface,borderColor:colors.border}]}><Pressable style={styles.battleBody} onPress={()=>router.push(`/battle/${item.id}`)}><View style={[styles.resultIcon,{backgroundColor:won?'#163426':item.status==='completed'?'#391D26':colors.surfaceAlt}]}><Ionicons name={won?'trophy':item.status==='completed'?'close-circle':'hourglass'} size={21} color={won?'#63D99A':item.status==='completed'?'#FF8290':colors.muted}/></View><View style={styles.grow}><Text style={[styles.name,{color:colors.text}]}>{item.status==='completed'?(won?'Vitória':'Derrota'):'Batalha '+item.status} vs @{opponent?.username??'Treinador'}</Text><Text style={[styles.sub,{color:colors.muted}]}>{item.mode==='draft3'?'Draft 3':item.mode==='mystery'?'Mystery BO3':'Quick'} • {item.stake_type==='coins'?`🪙 ${item.wager_coins}`:item.stake_type==='card'?'🎴 valendo carta':'Casual'} • {item.challenger_score}–{item.opponent_score}</Text><Text style={[styles.sub,{color:item.reward_eligible===false?'#E6A15A':colors.muted}]}>{item.completed_at?new Date(item.completed_at).toLocaleString('pt-BR'):new Date(item.created_at).toLocaleString('pt-BR')}{item.status==='completed'?` • ELO ${delta>=0?'+':''}${delta}`:''}{item.reward_eligible===false?' • sem XP/ELO anti-farm':''}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.muted}/></Pressable>{item.status==='completed'?<Pressable style={[styles.rematch,{borderColor:colors.accent}]} onPress={()=>rematch(item.id)} disabled={working===item.id}><Ionicons name="refresh" size={15} color={colors.accent}/><Text style={[styles.rematchText,{color:colors.accent}]}>{working===item.id?'CRIANDO...':'REVANCHE'}</Text></Pressable>:null}</View>})}</View>
  </Screen>;
}
function Mini({value,label}:{value:number|string;label:string}){const{colors}=useAppTheme();return <View><Text style={[styles.miniValue,{color:colors.text}]}>{value}</Text><Text style={[styles.miniLabel,{color:colors.muted}]}>{label}</Text></View>}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},notice:{flexDirection:'row',gap:8,padding:11,borderRadius:14,backgroundColor:'#2B2818',borderWidth:1,borderColor:'#5A5125'},noticeText:{flex:1,color:'#F8EFCB',fontSize:11,fontWeight:'700'},hero:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:18,flexWrap:'wrap',padding:18,borderRadius:22,borderWidth:1},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.3},rating:{fontSize:38,fontWeight:'900'},rankLabel:{fontSize:10},heroStats:{flexDirection:'row',flexWrap:'wrap',gap:18},miniValue:{fontSize:17,fontWeight:'900'},miniLabel:{fontSize:8,fontWeight:'800'},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:4},sectionTitle:{fontSize:20,fontWeight:'900'},sectionMeta:{fontSize:9,fontWeight:'900'},list:{gap:8},rankRow:{flexDirection:'row',alignItems:'center',gap:10,padding:11,borderRadius:16,borderWidth:1},position:{width:34,height:34,borderRadius:11,alignItems:'center',justifyContent:'center'},positionText:{fontWeight:'900'},grow:{flex:1,minWidth:0},name:{fontSize:12,fontWeight:'900'},sub:{fontSize:9,marginTop:3},elo:{fontSize:16,fontWeight:'900'},battleRow:{borderRadius:17,borderWidth:1,overflow:'hidden'},battleBody:{flexDirection:'row',alignItems:'center',gap:10,padding:11},resultIcon:{width:42,height:42,borderRadius:14,alignItems:'center',justifyContent:'center'},rematch:{alignSelf:'flex-end',marginRight:10,marginBottom:10,flexDirection:'row',alignItems:'center',gap:5,paddingHorizontal:10,paddingVertical:7,borderRadius:10,borderWidth:1},rematchText:{fontSize:8,fontWeight:'900'},empty:{padding:24,borderRadius:18,borderWidth:1,alignItems:'center',gap:7},emptyTitle:{fontSize:15,fontWeight:'900'},emptyText:{fontSize:10}});
