import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { getMyBattleStyle, setMyBattleStyle, type BattleStyle } from '@/services/proGamepasses';
import { useAppTheme } from '@/theme/ThemeProvider';

const ARENAS:Array<{id:BattleStyle['arenaStyle'];label:string;bg:string;border:string;detail:string}>=[
 {id:'classic',label:'CLÁSSICA',bg:'#182233',border:'#516178',detail:'Visual Game Boy moderno e neutro.'},
 {id:'kanto_night',label:'KANTO NOTURNA',bg:'#10152E',border:'#6A7CFF',detail:'Arena azul-índigo inspirada em batalhas noturnas.'},
 {id:'neon_grid',label:'NEON GRID',bg:'#071B24',border:'#45F3FF',detail:'Grade ciano e contraste tecnológico.'},
 {id:'champion_gold',label:'CHAMPION GOLD',bg:'#2A2414',border:'#FFD447',detail:'Dourado de campeão sem alterar qualquer stat.'},
 {id:'galaxy_void',label:'GALAXY VOID',bg:'#171027',border:'#8B5CFF',detail:'Roxo espacial com brilho de entrada.'},
];
const ENTRANCES:Array<{id:BattleStyle['entranceFx'];label:string;icon:keyof typeof Ionicons.glyphMap}>=[{id:'flash',label:'FLASH',icon:'flash'},{id:'scan',label:'SCAN',icon:'scan'},{id:'spark',label:'SPARK',icon:'sparkles'},{id:'warp',label:'WARP',icon:'planet'},{id:'none',label:'SEM EFEITO',icon:'remove-circle-outline'}];
const SWITCHES:Array<{id:BattleStyle['switchFx'];label:string;icon:keyof typeof Ionicons.glyphMap}>=[{id:'pulse',label:'PULSE',icon:'radio-button-on'},{id:'slide',label:'SLIDE',icon:'swap-horizontal'},{id:'spark',label:'SPARK',icon:'sparkles'},{id:'warp',label:'WARP',icon:'planet'},{id:'none',label:'SEM EFEITO',icon:'remove-circle-outline'}];

export default function BattleStylePassScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[style,setStyle]=useState<BattleStyle>({arenaStyle:'classic',entranceFx:'flash',switchFx:'pulse'});const[active,setActive]=useState(false);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setError(null);const next=await getMyBattleStyle();setActive(next.active);setStyle(next.style);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o estilo.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function save(){try{setWorking(true);await setMyBattleStyle(style);setNotice('Estilo de batalha salvo. A arena 3×3 usará este visual nas próximas batalhas.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');}finally{setWorking(false);}}
 const arena=ARENAS.find(a=>a.id===style.arenaStyle)??ARENAS[0];
 return <Screen title="Battle Style Pass" subtitle="Arenas, entradas e trocas personalizadas sem vantagem competitiva.">
  <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
  <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:arena.border}]}><Ionicons name="game-controller" size={30} color={arena.border}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>BATTLE STYLE PASS {active?'ATIVO':'INATIVO'}</Text><Text style={[styles.heroTitle,{color:colors.text}]}>Personalize a arena 3×3</Text><Text style={[styles.helper,{color:colors.muted}]}>Somente visual. Dano, HP, precisão, PP e ELO continuam idênticos.</Text></View></View>
  {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.noticeText}>{error}</Text></Pressable>:null}{notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={18} color="#59D49A"/><Text style={[styles.noticeText,{color:'#D9FFEC'}]}>{notice}</Text></Pressable>:null}
  {loading?<ActivityIndicator color={colors.yellow}/>:null}
  <View style={[styles.preview,{backgroundColor:arena.bg,borderColor:arena.border}]}><View style={[styles.scanLine,{backgroundColor:arena.border,opacity:style.entranceFx==='scan'?.55:.15}]}/><View style={styles.fighter}><Text style={styles.owner}>ADVERSÁRIO</Text><View style={[styles.sprite,{borderColor:arena.border}]}><Ionicons name="paw" size={35} color={arena.border}/></View><View style={[styles.hp,{backgroundColor:'#263246'}]}><View style={[styles.hpFill,{width:'72%',backgroundColor:'#59D49A'}]}/></View></View><View style={styles.vs}><Text style={[styles.vsText,{color:arena.border}]}>VS</Text><Text style={styles.fxText}>{style.entranceFx.toUpperCase()} • {style.switchFx.toUpperCase()}</Text></View><View style={styles.fighter}><Text style={styles.owner}>VOCÊ</Text><View style={[styles.sprite,{borderColor:arena.border}]}><Ionicons name="paw" size={35} color={arena.border}/></View><View style={[styles.hp,{backgroundColor:'#263246'}]}><View style={[styles.hpFill,{width:'88%',backgroundColor:'#59D49A'}]}/></View></View></View>
  <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Arena</Text><View style={styles.grid}>{ARENAS.map(a=><Pressable key={a.id} onPress={()=>setStyle(s=>({...s,arenaStyle:a.id}))} style={[styles.arenaCard,{backgroundColor:a.bg,borderColor:style.arenaStyle===a.id?a.border:colors.border,borderWidth:style.arenaStyle===a.id?2:1}]}><View style={[styles.swatch,{backgroundColor:a.border}]}/><Text style={styles.arenaName}>{a.label}</Text><Text style={styles.arenaDetail}>{a.detail}</Text>{style.arenaStyle===a.id?<Ionicons name="checkmark-circle" size={18} color={a.border}/>:null}</Pressable>)}</View></View>
  <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Efeito de entrada</Text><View style={styles.chips}>{ENTRANCES.map(x=><Pressable key={x.id} onPress={()=>setStyle(s=>({...s,entranceFx:x.id}))} style={[styles.chip,{backgroundColor:style.entranceFx===x.id?colors.accentSoft:colors.surfaceAlt,borderColor:style.entranceFx===x.id?colors.accent:colors.border}]}><Ionicons name={x.icon} size={16} color={style.entranceFx===x.id?colors.yellow:colors.muted}/><Text style={[styles.chipText,{color:style.entranceFx===x.id?colors.text:colors.muted}]}>{x.label}</Text></Pressable>)}</View><Text style={[styles.title,{color:colors.text}]}>Efeito de troca</Text><View style={styles.chips}>{SWITCHES.map(x=><Pressable key={x.id} onPress={()=>setStyle(s=>({...s,switchFx:x.id}))} style={[styles.chip,{backgroundColor:style.switchFx===x.id?colors.accentSoft:colors.surfaceAlt,borderColor:style.switchFx===x.id?colors.accent:colors.border}]}><Ionicons name={x.icon} size={16} color={style.switchFx===x.id?colors.yellow:colors.muted}/><Text style={[styles.chipText,{color:style.switchFx===x.id?colors.text:colors.muted}]}>{x.label}</Text></Pressable>)}</View></View>
  <Pressable disabled={!active||working} onPress={()=>void save()} style={[styles.primary,{backgroundColor:active?colors.yellow:colors.border,opacity:working?.65:1}]}>{working?<ActivityIndicator color="#07111F"/>:<Ionicons name="save" size={18} color="#07111F"/>}<Text style={styles.primaryText}>{active?'SALVAR ESTILO DE BATALHA':'GAMEPASS NECESSÁRIA'}</Text></Pressable>
 </Screen>;
}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},hero:{borderWidth:1,borderRadius:20,padding:15,flexDirection:'row',gap:11,alignItems:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},heroTitle:{fontSize:18,fontWeight:'900',marginTop:2},helper:{fontSize:9,lineHeight:14,marginTop:3},notice:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',gap:8,alignItems:'center'},noticeText:{flex:1,color:'#FFD7DD',fontSize:9,fontWeight:'800'},preview:{height:210,borderWidth:2,borderRadius:20,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',overflow:'hidden'},scanLine:{position:'absolute',left:0,right:0,top:'48%',height:2},fighter:{flex:1,alignItems:'center',gap:7},owner:{color:'#C6D0E0',fontSize:7,fontWeight:'900'},sprite:{width:74,height:74,borderWidth:2,borderRadius:18,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.03)'},hp:{width:'85%',height:7,borderRadius:999,overflow:'hidden'},hpFill:{height:'100%'},vs:{width:80,alignItems:'center'},vsText:{fontSize:28,fontWeight:'900'},fxText:{color:'#9CA9BD',fontSize:6.5,textAlign:'center',marginTop:5},panel:{borderWidth:1,borderRadius:18,padding:13,gap:10},title:{fontSize:17,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},arenaCard:{flexGrow:1,flexBasis:150,minWidth:140,borderRadius:14,padding:10,minHeight:115},swatch:{width:28,height:5,borderRadius:999},arenaName:{color:'#F4F7FB',fontSize:9,fontWeight:'900',marginTop:7},arenaDetail:{color:'#AAB5C6',fontSize:7,lineHeight:11,marginTop:3,flex:1},chips:{flexDirection:'row',gap:7,flexWrap:'wrap'},chip:{minHeight:40,borderWidth:1,borderRadius:11,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:6},chipText:{fontSize:7.5,fontWeight:'900'},primary:{minHeight:50,borderRadius:14,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},primaryText:{color:'#07111F',fontSize:9,fontWeight:'900'}});
