import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getBetaTesterHub } from '@/services/playerExperience';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function BetaTesterScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);
 const load=useCallback(async()=>{try{setData(await getBetaTesterHub());}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 return <Screen title="Beta & Tester" subtitle="Status da transição 1.0, participação de tester, feedbacks e recursos liberados para sua conta.">
  {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}{data?<><View style={[styles.hero,{backgroundColor:colors.surface,borderColor:data.isTester?colors.yellow:colors.border}]}><Ionicons name={data.isTester?'flask':'person'} size={30} color={data.isTester?colors.yellow:colors.muted}/><View style={{flex:1}}><Text style={[styles.kicker,{color:data.isTester?colors.yellow:colors.muted}]}>{data.isTester?'TESTER OFICIAL':'JOGADOR'}</Text><Text style={[styles.title,{color:colors.text}]}>{data.isTester?'Você faz parte dos testers':'Conta sem título Tester Oficial'}</Text><Text style={[styles.sub,{color:colors.muted}]}>{data.testerSince?'Desde '+new Date(data.testerSince).toLocaleDateString('pt-BR'):'O status só é concedido pelo administrador.'}</Text></View></View>
   {data.campaign?<View style={[styles.campaign,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Text style={[styles.kicker,{color:colors.accent}]}>TRANSIÇÃO ATUAL</Text><Text style={[styles.campaignTitle,{color:colors.text}]}>{data.campaign.title}</Text><Text style={[styles.sub,{color:colors.muted}]}>Fase: {data.campaign.phase} • alvo {data.campaign.targetVersion} • {data.campaign.releaseDate?new Date(data.campaign.releaseDate+'T00:00:00').toLocaleDateString('pt-BR'):'sem data'}</Text></View>:null}
   <View style={styles.grid}><Metric label="FEEDBACKS" value={String(data.feedback?.total??0)}/><Metric label="PLANEJADOS" value={String(data.feedback?.planned??0)}/><Metric label="RESOLVIDOS" value={String(data.feedback?.resolved??0)}/><Metric label="FLAGS ATIVAS" value={String(Object.values(data.featureFlags??{}).filter(Boolean).length)}/></View>
   <Pressable onPress={()=>router.push('/feedback')} style={[styles.action,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="chatbox" size={20} color={colors.accent}/><View style={{flex:1}}><Text style={[styles.actionTitle,{color:colors.text}]}>Enviar feedback</Text><Text style={[styles.sub,{color:colors.muted}]}>Bugs e sugestões ficam vinculados à sua conta.</Text></View><Ionicons name="chevron-forward" size={17} color={colors.muted}/></Pressable>
   <Pressable onPress={()=>router.push('/whats-new')} style={[styles.action,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="newspaper" size={20} color={colors.yellow}/><View style={{flex:1}}><Text style={[styles.actionTitle,{color:colors.text}]}>O que mudou</Text><Text style={[styles.sub,{color:colors.muted}]}>Acompanhe cada atualização e o que já foi lido.</Text></View><Ionicons name="chevron-forward" size={17} color={colors.muted}/></Pressable>
  </>:null}
 </Screen>;
}
function Metric({label,value}:{label:string;value:string}){const{colors}=useAppTheme();return <View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.metricLabel,{color:colors.muted}]}>{label}</Text><Text style={[styles.metricValue,{color:colors.text}]}>{value}</Text></View>;}
const styles=StyleSheet.create({hero:{borderRadius:20,borderWidth:1,padding:14,flexDirection:'row',alignItems:'center',gap:10},kicker:{fontSize:7,fontWeight:'900',letterSpacing:.8},title:{fontSize:16,fontWeight:'900',marginTop:2},sub:{fontSize:8,lineHeight:12,marginTop:2},campaign:{borderRadius:17,borderWidth:1,padding:11},campaignTitle:{fontSize:13,fontWeight:'900',marginTop:2},grid:{flexDirection:'row',flexWrap:'wrap',gap:7},metric:{flexGrow:1,flexBasis:130,minWidth:120,borderRadius:14,borderWidth:1,padding:9},metricLabel:{fontSize:6.5,fontWeight:'900'},metricValue:{fontSize:18,fontWeight:'900',marginTop:3},action:{borderRadius:15,borderWidth:1,padding:10,flexDirection:'row',alignItems:'center',gap:8},actionTitle:{fontSize:10,fontWeight:'900'}});
