import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { globalSearch, type GlobalCardResult } from '@/services/globalSearch';
import { getCardGameProfile, type CardGameProfile } from '@/services/cardGameProfile';
import { useAppTheme } from '@/theme/ThemeProvider';

type Pick={card:GlobalCardResult;profile:CardGameProfile|null};
export default function CardCompareScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[q,setQ]=useState('');const[results,setResults]=useState<GlobalCardResult[]>([]);const[picks,setPicks]=useState<Pick[]>([]);const[loading,setLoading]=useState(false);const[workingId,setWorkingId]=useState<string|null>(null);
 useEffect(()=>{const t=setTimeout(async()=>{if(q.trim().length<2){setResults([]);return;}try{setLoading(true);const r=await globalSearch(q);setResults(r.cards.slice(0,12));}finally{setLoading(false);}},250);return()=>clearTimeout(t);},[q]);
 async function pick(card:GlobalCardResult){if(workingId||picks.some(x=>x.card.id===card.id))return;try{setWorkingId(card.id);const profile=await getCardGameProfile(card.id).catch(()=>null);setPicks(v=>v.some(x=>x.card.id===card.id)?v:[...v.slice(-1),{card,profile}]);setQ('');setResults([]);}finally{setWorkingId(null);}}
 const both=picks.length===2;const rows=useMemo(()=>['hp','attack','defense','spAttack','spDefense','speed'] as const,[]);
 return <Screen title="Comparador de Cartas" subtitle="Compare lado a lado os stats usados pelo modo Pokémon Game Boy.">
  <View style={[styles.search,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={19} color={colors.muted}/><TextInput value={q} onChangeText={setQ} placeholder="Buscar Pokémon para comparar..." placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text}]}/>{loading?<ActivityIndicator size="small" color={colors.yellow}/>:null}</View>
  {results.length?<View style={styles.results}>{results.map(card=><Pressable key={card.id} disabled={Boolean(workingId)} onPress={()=>void pick(card)} style={[styles.result,{backgroundColor:colors.surface,borderColor:colors.border}]}>{card.imageSmall?<Image source={{uri:card.imageSmall}} style={styles.thumb} resizeMode="contain"/>:null}<View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{card.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{card.setName}</Text></View><Ionicons name="add-circle" size={20} color={colors.accent}/></Pressable>)}</View>:null}
  <View style={styles.pickGrid}>{[0,1].map(i=>{const p=picks[i];return <View key={i} style={[styles.pick,{backgroundColor:colors.surface,borderColor:p?colors.accent:colors.border}]}>{p?<><Pressable onPress={()=>router.push(('/card/'+p.card.id) as never)}>{p.card.imageSmall?<Image source={{uri:p.card.imageSmall}} style={styles.cardImage} resizeMode="contain"/>:null}<Text numberOfLines={1} style={[styles.pickName,{color:colors.text}]}>{p.card.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{p.profile?.types?.join(' / ').toUpperCase()||'TIPO —'}</Text></Pressable><Pressable onPress={()=>setPicks(v=>v.filter(x=>x.card.id!==p.card.id))}><Text style={[styles.remove,{color:'#FF8792'}]}>REMOVER</Text></Pressable></>:<><Ionicons name="card-outline" size={34} color={colors.muted}/><Text style={[styles.placeholder,{color:colors.muted}]}>Escolha o Pokémon {i+1}</Text></>}</View>;})}</View>
  {both?<View style={[styles.table,{backgroundColor:colors.surface,borderColor:colors.border}]}>{rows.map(key=>{const a=Number(picks[0].profile?.stats?.[key]??0);const b=Number(picks[1].profile?.stats?.[key]??0);return <View key={key} style={[styles.row,{borderBottomColor:colors.border}]}><Text style={[styles.value,{color:a>b?'#65D894':colors.text}]}>{a||'—'}</Text><Text style={[styles.label,{color:colors.muted}]}>{key==='spAttack'?'SP. ATK':key==='spDefense'?'SP. DEF':key.toUpperCase()}</Text><Text style={[styles.value,{color:b>a?'#65D894':colors.text}]}>{b||'—'}</Text></View>;})}</View>:null}
  {both?<View style={styles.moves}>{picks.map(p=><View key={p.card.id} style={[styles.moveBox,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.moveTitle,{color:colors.text}]}>{p.card.name}</Text>{(p.profile?.moves??[]).slice(0,4).map(m=><Text key={m.id} style={[styles.move,{color:colors.muted}]}>• {m.identifier.replaceAll('-',' ')} • {m.power??'status'} poder • {m.pp} PP</Text>)}</View>)}</View>:null}
 </Screen>;
}
const styles=StyleSheet.create({search:{minHeight:50,borderRadius:15,borderWidth:1,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,fontSize:12,fontWeight:'800'},results:{gap:6},result:{minHeight:58,borderRadius:14,borderWidth:1,padding:7,flexDirection:'row',alignItems:'center',gap:8},thumb:{width:40,height:50},name:{fontSize:10,fontWeight:'900'},meta:{fontSize:7.5,marginTop:2},pickGrid:{flexDirection:'row',gap:8,flexWrap:'wrap'},pick:{flex:1,minWidth:145,minHeight:220,borderRadius:17,borderWidth:1,padding:10,alignItems:'center',justifyContent:'center',gap:7},cardImage:{width:120,height:160,alignSelf:'center'},pickName:{fontSize:11,fontWeight:'900',textAlign:'center'},remove:{fontSize:7,fontWeight:'900',marginTop:6},placeholder:{fontSize:9,fontWeight:'800'},table:{borderRadius:17,borderWidth:1,overflow:'hidden'},row:{minHeight:42,borderBottomWidth:1,flexDirection:'row',alignItems:'center'},value:{flex:1,textAlign:'center',fontSize:14,fontWeight:'900'},label:{width:86,textAlign:'center',fontSize:7,fontWeight:'900'},moves:{flexDirection:'row',gap:8,flexWrap:'wrap'},moveBox:{flex:1,minWidth:200,borderRadius:15,borderWidth:1,padding:10},moveTitle:{fontSize:11,fontWeight:'900',marginBottom:5},move:{fontSize:7.5,lineHeight:12}});