import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { deleteCollectorGoal, getCollectorPassDashboard, saveCollectorGoal, type CollectorDashboard, type CollectorGoal } from '@/services/proGamepasses';
import { useAppTheme } from '@/theme/ThemeProvider';

const KINDS:Array<{id:CollectorGoal['kind'];label:string;hint:string}>=[
 {id:'unique',label:'CARTAS ÚNICAS',hint:'Ex.: chegar a 5.000 cartas únicas'},
 {id:'value',label:'VALOR DA COLEÇÃO',hint:'Meta em US$'},
 {id:'set',label:'COMPLETAR SET',hint:'Use o ID do set e a quantidade total'},
 {id:'type',label:'TIPO',hint:'Ex.: Fire com 200 cartas únicas'},
];

export default function CollectorPassScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[data,setData]=useState<CollectorDashboard|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const[kind,setKind]=useState<CollectorGoal['kind']>('unique');const[key,setKey]=useState('');const[label,setLabel]=useState('');const[target,setTarget]=useState('');
 const load=useCallback(async()=>{try{setLoading(true);setError(null);setData(await getCollectorPassDashboard());}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o Collector Pass.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function addGoal(){const value=Number(target.replace(',','.'));if(!label.trim()||!Number.isFinite(value)||value<=0)return;try{setWorking(true);await saveCollectorGoal({kind,key:key.trim(),label:label.trim(),target:value});setLabel('');setTarget('');setNotice('Meta de coleção criada.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível criar a meta.');}finally{setWorking(false);}}
 async function removeGoal(id:string){try{setWorking(true);await deleteCollectorGoal(id);await load();}finally{setWorking(false);}}
 const completion=useMemo(()=>{const sets=data?.bySet??[];if(!sets.length)return{complete:0,avg:0};return{complete:sets.filter(s=>s.percent>=100).length,avg:sets.reduce((a,b)=>a+b.percent,0)/sets.length};},[data]);
 return <Screen title="Collector Pass" subtitle="Progresso por set e tipo, metas e recomendações para a coleção.">
  <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
  <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.yellow}]}><Ionicons name="stats-chart" size={30} color={colors.yellow}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>COLLECTOR PASS ATIVO</Text><Text style={[styles.heroTitle,{color:colors.text}]}>Sua coleção em números</Text><Text style={[styles.helper,{color:colors.muted}]}>Metas e estatísticas usam somente cartas realmente presentes na sua Bag.</Text></View></View>
  {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.noticeText}>{error}</Text></Pressable>:null}{notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={18} color="#59D49A"/><Text style={[styles.noticeText,{color:'#D9FFEC'}]}>{notice}</Text></Pressable>:null}
  {loading&&!data?<ActivityIndicator size="large" color={colors.yellow}/>:null}
  {data?<><View style={styles.metrics}><Metric label="ÚNICAS" value={data.summary.uniqueCards.toLocaleString('pt-BR')} colors={colors}/><Metric label="CÓPIAS" value={data.summary.totalCopies.toLocaleString('pt-BR')} colors={colors}/><Metric label="VALOR" value={'US$ '+Number(data.summary.collectionValueUsd).toFixed(2)} colors={colors}/><Metric label="SETS COMPLETOS" value={String(completion.complete)} colors={colors}/></View>
   <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Metas de coleção</Text><View style={styles.chips}>{KINDS.map(k=><Pressable key={k.id} onPress={()=>setKind(k.id)} style={[styles.chip,{backgroundColor:kind===k.id?colors.accentSoft:colors.surfaceAlt,borderColor:kind===k.id?colors.accent:colors.border}]}><Text style={[styles.chipText,{color:kind===k.id?colors.accent:colors.muted}]}>{k.label}</Text></Pressable>)}</View><Text style={[styles.helper,{color:colors.muted}]}>{KINDS.find(k=>k.id===kind)?.hint}</Text><View style={styles.row}>{kind==='set'||kind==='type'?<TextInput value={key} onChangeText={setKey} placeholder={kind==='set'?'ID do set':'Tipo em inglês'} placeholderTextColor={colors.muted} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/>:null}<TextInput value={label} onChangeText={setLabel} placeholder="Nome da meta" placeholderTextColor={colors.muted} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/><TextInput value={target} onChangeText={setTarget} keyboardType="decimal-pad" placeholder="Alvo" placeholderTextColor={colors.muted} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/><Pressable disabled={working||!label.trim()||!target} onPress={()=>void addGoal()} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="flag" size={17} color="#07111F"/><Text style={styles.primaryText}>CRIAR META</Text></Pressable></View>
    <View style={styles.stack}>{data.goals.map(g=>{const pct=Math.min(100,Number(g.progress)/Math.max(1,Number(g.target))*100);return <View key={g.id} style={[styles.goal,{backgroundColor:colors.surfaceAlt,borderColor:pct>=100?'#59D49A':colors.border}]}><View style={{flex:1}}><View style={styles.rowBetween}><Text style={[styles.goalTitle,{color:colors.text}]}>{g.label}</Text><Text style={[styles.goalPct,{color:pct>=100?'#59D49A':colors.yellow}]}>{pct.toFixed(0)}%</Text></View><View style={[styles.track,{backgroundColor:colors.border}]}><View style={[styles.fill,{backgroundColor:pct>=100?'#59D49A':colors.accent,width:`${pct}%` as any}]}/></View><Text style={[styles.meta,{color:colors.muted}]}>{Number(g.progress).toLocaleString('pt-BR')} / {Number(g.target).toLocaleString('pt-BR')} • {g.kind.toUpperCase()}{g.key?' • '+g.key:''}</Text></View><Pressable onPress={()=>void removeGoal(g.id)}><Ionicons name="trash" size={18} color="#FF8998"/></Pressable></View>;})}</View>
   </View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Sets perto de completar</Text><View style={styles.grid}>{data.nearCompleteSets.slice(0,12).map(s=><Pressable key={s.setId} onPress={()=>router.push(('/set/'+s.setId) as never)} style={[styles.setCard,{backgroundColor:colors.surface,borderColor:s.missing<=5?colors.yellow:colors.border}]}><Text numberOfLines={1} style={[styles.setName,{color:colors.text}]}>{s.setName}</Text><Text style={[styles.setPct,{color:colors.yellow}]}>{s.percent}%</Text><Text style={[styles.meta,{color:colors.muted}]}>{s.owned}/{s.total} • faltam {s.missing}</Text><View style={[styles.track,{backgroundColor:colors.border}]}><View style={[styles.fill,{backgroundColor:colors.accent,width:`${Math.min(100,s.percent)}%` as any}]}/></View></Pressable>)}</View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Progresso por tipo</Text><View style={styles.grid}>{data.byType.slice(0,18).map(t=><View key={t.type} style={[styles.typeCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.typeName,{color:colors.text}]}>{t.type.toUpperCase()}</Text><Text style={[styles.typeValue,{color:colors.accent}]}>{t.owned}</Text><Text style={[styles.meta,{color:colors.muted}]}>{t.copies} cópia(s)</Text></View>)}</View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Progresso geral por set</Text><View style={styles.stack}>{data.bySet.slice(0,30).map(s=><Pressable key={s.setId} onPress={()=>router.push(('/set/'+s.setId) as never)} style={[styles.setRow,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={{flex:1}}><Text numberOfLines={1} style={[styles.setName,{color:colors.text}]}>{s.setName}</Text><Text style={[styles.meta,{color:colors.muted}]}>{s.owned}/{s.total} • faltam {s.missing}</Text><View style={[styles.track,{backgroundColor:colors.border}]}><View style={[styles.fill,{backgroundColor:s.percent>=100?'#59D49A':colors.accent,width:`${Math.min(100,s.percent)}%` as any}]}/></View></View><Text style={[styles.setPct,{color:s.percent>=100?'#59D49A':colors.yellow}]}>{s.percent}%</Text></Pressable>)}</View>
  </>:null}
 </Screen>;
}
function Metric({label,value,colors}:{label:string;value:string;colors:any}){return <View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.metricLabel,{color:colors.muted}]}>{label}</Text><Text numberOfLines={1} style={[styles.metricValue,{color:colors.text}]}>{value}</Text></View>;}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},hero:{borderWidth:1,borderRadius:20,padding:15,flexDirection:'row',gap:11,alignItems:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},heroTitle:{fontSize:18,fontWeight:'900',marginTop:2},helper:{fontSize:9,lineHeight:14,marginTop:3},notice:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',alignItems:'center',gap:8},noticeText:{flex:1,color:'#FFD7DD',fontSize:9,fontWeight:'800'},metrics:{flexDirection:'row',flexWrap:'wrap',gap:7},metric:{flexGrow:1,flexBasis:120,borderWidth:1,borderRadius:13,padding:10},metricLabel:{fontSize:7,fontWeight:'900'},metricValue:{fontSize:15,fontWeight:'900',marginTop:2},panel:{borderWidth:1,borderRadius:18,padding:13,gap:9},title:{fontSize:17,fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900'},chips:{flexDirection:'row',gap:6,flexWrap:'wrap'},chip:{minHeight:34,borderWidth:1,borderRadius:999,paddingHorizontal:9,alignItems:'center',justifyContent:'center'},chipText:{fontSize:7,fontWeight:'900'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},input:{flex:1,minWidth:130,height:44,borderWidth:1,borderRadius:11,paddingHorizontal:11},primary:{minHeight:44,paddingHorizontal:12,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},primaryText:{color:'#07111F',fontSize:8,fontWeight:'900'},stack:{gap:7},goal:{minHeight:80,borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',alignItems:'center',gap:9},rowBetween:{flexDirection:'row',justifyContent:'space-between',gap:8},goalTitle:{fontSize:10,fontWeight:'900'},goalPct:{fontSize:10,fontWeight:'900'},track:{height:6,borderRadius:999,overflow:'hidden',marginTop:6},fill:{height:'100%',borderRadius:999},meta:{fontSize:7.5,marginTop:3},grid:{flexDirection:'row',flexWrap:'wrap',gap:7},setCard:{flexGrow:1,flexBasis:150,minWidth:140,borderWidth:1,borderRadius:13,padding:10},setName:{fontSize:10,fontWeight:'900'},setPct:{fontSize:16,fontWeight:'900',marginTop:3},typeCard:{flexGrow:1,flexBasis:105,minWidth:95,borderWidth:1,borderRadius:13,padding:10},typeName:{fontSize:8,fontWeight:'900'},typeValue:{fontSize:20,fontWeight:'900',marginTop:2},setRow:{minHeight:70,borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',alignItems:'center',gap:10}});
