import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getMyDecks } from '@/services/decks';
import { getMyCollectionRecommendations, type CollectionRecommendations } from '@/services/trainerInsights';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function DeckCoachScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[decks,setDecks]=useState<any[]>([]);const[recs,setRecs]=useState<CollectionRecommendations|null>(null);const[loading,setLoading]=useState(true);const[selected,setSelected]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const[d,r]=await Promise.all([getMyDecks(),getMyCollectionRecommendations()]);setDecks(d);setRecs(r);setSelected(v=>v??d[0]?.id??null);}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 const deck=useMemo(()=>decks.find(d=>d.id===selected)??null,[decks,selected]);const cards=Array.isArray(deck?.deck_cards)?deck.deck_cards:[];
 return <Screen title="Coach de Deck" subtitle="Sugestões baseadas na sua coleção. Nada é alterado automaticamente.">
  {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}
  <View style={styles.deckRow}>{decks.map(d=><Pressable key={d.id} onPress={()=>setSelected(d.id)} style={[styles.deckChip,{backgroundColor:selected===d.id?colors.accentSoft:colors.surface,borderColor:selected===d.id?colors.accent:colors.border}]}><Ionicons name="albums" size={16} color={selected===d.id?colors.accent:colors.muted}/><Text numberOfLines={1} style={[styles.deckText,{color:colors.text}]}>{d.name}</Text></Pressable>)}</View>
  {deck?<View style={[styles.summary,{backgroundColor:colors.surface,borderColor:colors.border}]}><View><Text style={[styles.kicker,{color:colors.yellow}]}>DECK ANALISADO</Text><Text style={[styles.title,{color:colors.text}]}>{deck.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{cards.reduce((s:number,x:any)=>s+Number(x.quantity??1),0)} carta(s) • {deck.is_default?'principal':'alternativo'}</Text></View><Pressable onPress={()=>router.push(('/deck/'+deck.id) as never)} style={[styles.edit,{backgroundColor:colors.yellow}]}><Text style={styles.editText}>EDITAR</Text></Pressable></View>:null}
  <View style={[styles.tip,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Ionicons name="bulb" size={20} color={colors.accent}/><Text style={[styles.tipText,{color:colors.muted}]}>Priorize cobertura de tipos e Pokémon fortes que você já possui. Compare a recomendação com os Pokémon atuais antes de trocar.</Text></View>
  <Text style={[styles.section,{color:colors.text}]}>Melhorias disponíveis na sua coleção</Text>
  <View style={styles.grid}>{(recs?.unusedStrongCards??[]).slice(0,12).map(item=><Pressable key={item.cardId} onPress={()=>router.push(('/card/'+item.cardId) as never)} style={[styles.card,{backgroundColor:colors.surface,borderColor:colors.border}]}>{item.image?<Image source={{uri:item.image}} style={styles.image} resizeMode="contain"/>:<View style={[styles.image,{backgroundColor:colors.surfaceAlt}]}/>}<View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={[styles.cardName,{color:colors.text}]}>{item.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{item.types.join(' / ').toUpperCase()}</Text><Text style={[styles.score,{color:colors.accent}]}>Força combinada {item.score}</Text></View><Ionicons name="chevron-forward" size={16} color={colors.muted}/></Pressable>)}</View>
  <Pressable onPress={()=>router.push('/trainer-insights')} style={[styles.more,{borderColor:colors.border}]}><Ionicons name="analytics" size={17} color={colors.accent}/><Text style={[styles.moreText,{color:colors.text}]}>VER TODOS OS INSIGHTS</Text></Pressable>
 </Screen>;
}
const styles=StyleSheet.create({deckRow:{flexDirection:'row',flexWrap:'wrap',gap:7},deckChip:{minHeight:40,maxWidth:210,borderRadius:13,borderWidth:1,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:6},deckText:{fontSize:8.5,fontWeight:'900',flexShrink:1},summary:{borderRadius:17,borderWidth:1,padding:11,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},kicker:{fontSize:7,fontWeight:'900'},title:{fontSize:15,fontWeight:'900',marginTop:2},meta:{fontSize:7.5,marginTop:2},edit:{height:38,paddingHorizontal:14,borderRadius:11,alignItems:'center',justifyContent:'center'},editText:{color:'#07111F',fontSize:8,fontWeight:'900'},tip:{borderRadius:15,borderWidth:1,padding:10,flexDirection:'row',alignItems:'center',gap:8},tipText:{flex:1,fontSize:8,lineHeight:12},section:{fontSize:17,fontWeight:'900'},grid:{flexDirection:'row',flexWrap:'wrap',gap:7},card:{flexGrow:1,flexBasis:240,minWidth:220,borderRadius:15,borderWidth:1,padding:8,flexDirection:'row',alignItems:'center',gap:8},image:{width:48,height:63,borderRadius:5},cardName:{fontSize:10,fontWeight:'900'},score:{fontSize:7.5,fontWeight:'900',marginTop:3},more:{height:44,borderRadius:13,borderWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},moreText:{fontSize:8,fontWeight:'900'}});