import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, usePathname } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getMyFeedback, submitFeedback, type FeedbackCategory } from '@/services/playerExperience';
import { useAppTheme } from '@/theme/ThemeProvider';

const CATS:Array<[FeedbackCategory,string,keyof typeof Ionicons.glyphMap]>=[['bug','Bug','bug'],['suggestion','Sugestão','bulb'],['balance','Balanceamento','scale'],['ux','Interface/UX','phone-portrait'],['other','Outro','chatbox']];
export default function FeedbackScreen(){
 const{colors}=useAppTheme();const pathname=usePathname();const[category,setCategory]=useState<FeedbackCategory>('bug');const[message,setMessage]=useState('');const[rows,setRows]=useState<any[]>([]);const[working,setWorking]=useState(false);const[notice,setNotice]=useState<string|null>(null);
 const load=useCallback(async()=>{setRows(await getMyFeedback().catch(()=>[]));},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function send(){if(message.trim().length<5||working)return;try{setWorking(true);setNotice(null);await submitFeedback(category,message,pathname,{screen:pathname});setMessage('');setNotice('Feedback enviado. Obrigado por ajudar a melhorar o Trainer Collection.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível enviar.');}finally{setWorking(false);}}
 return <Screen title="Feedback" subtitle="Reporte bugs, ideias, balanceamento ou problemas de interface diretamente pelo app.">
  <View style={[styles.info,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Ionicons name="shield-checkmark" size={21} color={colors.accent}/><Text style={[styles.infoText,{color:colors.muted}]}>Não envie senhas, tokens ou dados pessoais. O contexto técnico é limitado à tela e versão do app.</Text></View>
  <View style={styles.cats}>{CATS.map(([id,label,icon])=><Pressable key={id} onPress={()=>setCategory(id)} style={[styles.cat,{backgroundColor:category===id?colors.accentSoft:colors.surface,borderColor:category===id?colors.accent:colors.border}]}><Ionicons name={icon} size={16} color={category===id?colors.accent:colors.muted}/><Text style={[styles.catText,{color:colors.text}]}>{label}</Text></Pressable>)}</View>
  <TextInput multiline value={message} onChangeText={setMessage} maxLength={2000} placeholder="Explique o que aconteceu ou o que você sugere..." placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,backgroundColor:colors.surface,borderColor:colors.border}]}/>
  <View style={styles.sendRow}><Text style={[styles.count,{color:colors.muted}]}>{message.length}/2000</Text><Pressable disabled={message.trim().length<5||working} onPress={()=>void send()} style={[styles.send,{backgroundColor:colors.yellow},(message.trim().length<5||working)&&{opacity:.4}]}>{working?<ActivityIndicator size="small" color="#07111F"/>:<Ionicons name="send" size={16} color="#07111F"/>}<Text style={styles.sendText}>{working?'ENVIANDO…':'ENVIAR FEEDBACK'}</Text></Pressable></View>
  {notice?<Text style={[styles.notice,{color:notice.startsWith('Feedback enviado')?'#65D894':'#FF9EAA'}]}>{notice}</Text>:null}
  <Text style={[styles.section,{color:colors.text}]}>Seus envios</Text><View style={styles.list}>{rows.map(r=><View key={r.id} style={[styles.row,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.status,{color:r.status==='resolved'?'#65D894':r.status==='planned'?colors.yellow:colors.accent}]}>{String(r.status).toUpperCase()}</Text><Text style={[styles.rowText,{color:colors.text}]}>{r.message}</Text><Text style={[styles.meta,{color:colors.muted}]}>{r.category} • {new Date(r.createdAt).toLocaleString('pt-BR')}</Text>{r.adminNote?<Text style={[styles.adminNote,{color:colors.muted}]}>Resposta: {r.adminNote}</Text>:null}</View>)}</View>
 </Screen>;
}
const styles=StyleSheet.create({info:{borderRadius:15,borderWidth:1,padding:10,flexDirection:'row',alignItems:'center',gap:8},infoText:{flex:1,fontSize:7.5,lineHeight:11},cats:{flexDirection:'row',flexWrap:'wrap',gap:6},cat:{borderRadius:999,borderWidth:1,paddingHorizontal:9,paddingVertical:7,flexDirection:'row',alignItems:'center',gap:5},catText:{fontSize:7.5,fontWeight:'900'},input:{minHeight:150,borderRadius:16,borderWidth:1,padding:12,fontSize:11,textAlignVertical:'top'},sendRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},count:{fontSize:7},send:{minHeight:42,borderRadius:12,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:6},sendText:{fontSize:8,fontWeight:'900',color:'#07111F'},notice:{fontSize:9,fontWeight:'800'},section:{fontSize:18,fontWeight:'900'},list:{gap:7},row:{borderRadius:14,borderWidth:1,padding:10},status:{fontSize:6.5,fontWeight:'900'},rowText:{fontSize:9,lineHeight:13,marginTop:4},meta:{fontSize:7,marginTop:4},adminNote:{fontSize:8,lineHeight:12,marginTop:6,fontStyle:'italic'}});
