import { useCallback, useState } from 'react';
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { getGuildProDashboard, saveGuildProSettings, setGuildProMemberRole, type GuildProDashboard, type GuildProRole } from '@/services/proGamepasses';
import { useAppTheme } from '@/theme/ThemeProvider';

const ROLE_LABELS:Record<GuildProRole,string>={strategist:'ESTRATEGISTA',recruiter:'RECRUTADOR',collector:'COLECIONADOR',defender:'DEFENSOR',event_lead:'LÍDER DE EVENTOS',market_lead:'LÍDER DE MERCADO'};
const ACTION_LABELS:Record<string,string>={set_pro_role:'Cargo Pro alterado',clear_pro_role:'Cargo Pro removido',update_pro_identity:'Identidade Pro atualizada'};

export default function GuildProScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[data,setData]=useState<GuildProDashboard|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);const[selectedMember,setSelectedMember]=useState<GuildProDashboard['members'][number]|null>(null);
 const[accent,setAccent]=useState('#FFD447');const[badge,setBadge]=useState('PRO');const[announcement,setAnnouncement]=useState('');
 const load=useCallback(async()=>{try{setLoading(true);setError(null);const next=await getGuildProDashboard();setData(next);setAccent(next.settings.accentColor??'#FFD447');setBadge(next.settings.badge??'PRO');setAnnouncement(next.settings.announcement??'');}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o Guild Pro.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 async function setRole(role:GuildProRole|null){if(!selectedMember)return;try{setWorking(true);await setGuildProMemberRole(selectedMember.playerId,role);setSelectedMember(null);setNotice(role?`Cargo ${ROLE_LABELS[role]} aplicado.`:'Cargo Pro removido.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível alterar o cargo.');}finally{setWorking(false);}}
 async function saveSettings(){try{setWorking(true);await saveGuildProSettings(accent.trim().toUpperCase(),badge.trim(),announcement.trim());setNotice('Identidade Guild Pro atualizada.');await load();}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar a identidade Pro.');}finally{setWorking(false);}}
 return <Screen title="Guild Pro" subtitle="Cargos organizacionais, histórico administrativo e identidade extra da guilda.">
  <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
  <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:data?.settings.accentColor??colors.yellow}]}><View style={[styles.badge,{backgroundColor:data?.settings.accentColor??colors.yellow}]}><Text style={styles.badgeText}>{data?.settings.badge||'PRO'}</Text></View><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>GUILD PRO ATIVO</Text><Text style={[styles.heroTitle,{color:colors.text}]}>{data?.guild.name??'Sua guilda'}</Text><Text style={[styles.helper,{color:colors.muted}]}>{data?.settings.announcement||'Organize funções sem alterar as permissões-base de líder, oficial e membro.'}</Text></View></View>
  {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.noticeText}>{error}</Text></Pressable>:null}{notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={18} color="#59D49A"/><Text style={[styles.noticeText,{color:'#D9FFEC'}]}>{notice}</Text></Pressable>:null}
  {loading&&!data?<ActivityIndicator size="large" color={colors.yellow}/>:null}
  {data?<><View style={styles.metrics}><Metric label="NÍVEL" value={String(data.guild.level)} colors={colors}/><Metric label="XP" value={Number(data.guild.xp).toLocaleString('pt-BR')} colors={colors}/><Metric label="MEMBROS" value={String(data.members.length)} colors={colors}/><Metric label="SEU CARGO" value={data.guild.baseRole.toUpperCase()} colors={colors}/></View>
   <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Identidade extra da guilda</Text><Text style={[styles.helper,{color:colors.muted}]}>Cor, selo e comunicado aparecem no painel Pro. Não altera dano, recompensa ou poder da guilda.</Text><View style={styles.row}><TextInput editable={data.canManage} value={accent} onChangeText={setAccent} autoCapitalize="characters" maxLength={7} placeholder="#FFD447" placeholderTextColor={colors.muted} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/><TextInput editable={data.canManage} value={badge} onChangeText={setBadge} maxLength={16} placeholder="Selo" placeholderTextColor={colors.muted} style={[styles.input,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/></View><TextInput editable={data.canManage} value={announcement} onChangeText={setAnnouncement} maxLength={180} multiline placeholder="Comunicado da guilda..." placeholderTextColor={colors.muted} style={[styles.textarea,{backgroundColor:colors.surfaceAlt,borderColor:colors.border,color:colors.text}]}/>{data.canManage?<Pressable disabled={working} onPress={()=>void saveSettings()} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="color-palette" size={17} color="#07111F"/><Text style={styles.primaryText}>SALVAR IDENTIDADE PRO</Text></Pressable>:<Text style={[styles.helper,{color:colors.muted}]}>Somente líder ou oficial pode editar a identidade.</Text>}</View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Cargos organizacionais</Text><View style={styles.stack}>{data.members.map(m=><View key={m.playerId} style={[styles.member,{backgroundColor:colors.surface,borderColor:m.proRole?(data.settings.accentColor||colors.accent):colors.border}]}><View style={[styles.memberIcon,{backgroundColor:colors.surfaceAlt}]}><Ionicons name={m.baseRole==='leader'?'trophy':m.baseRole==='officer'?'shield':'person'} size={19} color={m.baseRole==='leader'?colors.yellow:colors.accent}/></View><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={[styles.memberName,{color:colors.text}]}>{m.username}</Text><Text style={[styles.meta,{color:colors.muted}]}>{m.baseRole.toUpperCase()}{m.proRole?' • '+ROLE_LABELS[m.proRole]:''}</Text></View>{data.canManage?<Pressable onPress={()=>setSelectedMember(m)} style={[styles.roleButton,{borderColor:colors.accent}]}><Ionicons name="people-circle" size={17} color={colors.accent}/><Text style={[styles.roleButtonText,{color:colors.accent}]}>CARGO</Text></Pressable>:null}</View>)}</View>
   <View style={[styles.info,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Ionicons name="information-circle" size={19} color={colors.accent}/><Text style={[styles.helper,{color:colors.text,flex:1}]}>Cargos Pro são funções de organização. Eles não concedem poderes de líder/oficial e não alteram permissões de segurança.</Text></View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Histórico administrativo Pro</Text><View style={styles.stack}>{data.audit.length?data.audit.map(a=><View key={a.id} style={[styles.audit,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="time" size={18} color={colors.muted}/><View style={{flex:1}}><Text style={[styles.auditTitle,{color:colors.text}]}>{ACTION_LABELS[a.action]??a.action}</Text><Text style={[styles.meta,{color:colors.muted}]}>{a.actorUsername??'Treinador'}{a.targetUsername?' → '+a.targetUsername:''} • {new Date(a.createdAt).toLocaleString('pt-BR')}</Text>{typeof a.metadata?.role==='string'?<Text style={[styles.meta,{color:colors.yellow}]}>{ROLE_LABELS[a.metadata.role as GuildProRole]??String(a.metadata.role)}</Text>:null}</View></View>):<Text style={[styles.helper,{color:colors.muted}]}>As próximas alterações feitas pelo Guild Pro aparecerão aqui.</Text>}</View>
  </>:null}
  <Modal visible={Boolean(selectedMember)} transparent animationType="fade" onRequestClose={()=>setSelectedMember(null)}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setSelectedMember(null)}/><View style={[styles.modal,{backgroundColor:colors.bg,borderColor:colors.border}]}><View style={styles.modalHead}><View><Text style={[styles.kicker,{color:colors.yellow}]}>CARGO PRO</Text><Text style={[styles.modalTitle,{color:colors.text}]}>{selectedMember?.username}</Text></View><Pressable onPress={()=>setSelectedMember(null)}><Ionicons name="close" size={22} color={colors.text}/></Pressable></View><View style={styles.stack}>{(data?.roleOptions??[]).map(role=><Pressable key={role} disabled={working} onPress={()=>void setRole(role)} style={[styles.roleOption,{backgroundColor:selectedMember?.proRole===role?colors.accentSoft:colors.surface,borderColor:selectedMember?.proRole===role?colors.accent:colors.border}]}><Ionicons name="ribbon" size={19} color={selectedMember?.proRole===role?colors.yellow:colors.accent}/><Text style={[styles.roleOptionText,{color:colors.text}]}>{ROLE_LABELS[role]}</Text>{selectedMember?.proRole===role?<Ionicons name="checkmark-circle" size={19} color={colors.yellow}/>:null}</Pressable>)}<Pressable disabled={working} onPress={()=>void setRole(null)} style={[styles.roleOption,{backgroundColor:colors.surface,borderColor:'#683243'}]}><Ionicons name="close-circle" size={19} color="#FF8998"/><Text style={[styles.roleOptionText,{color:'#FFB7C0'}]}>REMOVER CARGO PRO</Text></Pressable></View></View></View></Modal>
 </Screen>;
}
function Metric({label,value,colors}:{label:string;value:string;colors:any}){return <View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.metricLabel,{color:colors.muted}]}>{label}</Text><Text numberOfLines={1} style={[styles.metricValue,{color:colors.text}]}>{value}</Text></View>;}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},hero:{borderWidth:1,borderRadius:20,padding:15,flexDirection:'row',gap:11,alignItems:'center'},badge:{minWidth:58,height:58,borderRadius:17,alignItems:'center',justifyContent:'center',paddingHorizontal:8},badgeText:{color:'#07111F',fontSize:11,fontWeight:'900'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},heroTitle:{fontSize:20,fontWeight:'900',marginTop:2},helper:{fontSize:9,lineHeight:14,marginTop:3},notice:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',gap:8,alignItems:'center'},noticeText:{flex:1,color:'#FFD7DD',fontSize:9,fontWeight:'800'},metrics:{flexDirection:'row',gap:7,flexWrap:'wrap'},metric:{flexGrow:1,flexBasis:110,borderWidth:1,borderRadius:13,padding:10},metricLabel:{fontSize:7,fontWeight:'900'},metricValue:{fontSize:14,fontWeight:'900',marginTop:2},panel:{borderWidth:1,borderRadius:18,padding:13,gap:9},title:{fontSize:17,fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},input:{flex:1,minWidth:130,height:44,borderWidth:1,borderRadius:11,paddingHorizontal:11},textarea:{minHeight:88,borderWidth:1,borderRadius:11,padding:11,textAlignVertical:'top'},primary:{minHeight:44,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},primaryText:{color:'#07111F',fontSize:8,fontWeight:'900'},stack:{gap:7},member:{minHeight:66,borderWidth:1,borderRadius:13,padding:9,flexDirection:'row',alignItems:'center',gap:9},memberIcon:{width:42,height:42,borderRadius:12,alignItems:'center',justifyContent:'center'},memberName:{fontSize:10,fontWeight:'900'},meta:{fontSize:7.5,marginTop:2},roleButton:{minHeight:34,borderWidth:1,borderRadius:10,paddingHorizontal:9,flexDirection:'row',alignItems:'center',gap:5},roleButtonText:{fontSize:7,fontWeight:'900'},info:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',gap:8,alignItems:'center'},audit:{minHeight:58,borderWidth:1,borderRadius:13,padding:9,flexDirection:'row',gap:8,alignItems:'center'},auditTitle:{fontSize:9,fontWeight:'900'},overlay:{flex:1,backgroundColor:'rgba(2,5,12,.82)',padding:16,justifyContent:'center'},modal:{width:'100%',maxWidth:620,alignSelf:'center',borderWidth:1,borderRadius:20,padding:13,gap:10},modalHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{fontSize:20,fontWeight:'900'},roleOption:{minHeight:52,borderWidth:1,borderRadius:12,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:8},roleOptionText:{flex:1,fontSize:9,fontWeight:'900'}});
