import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { Screen } from '@/components/Screen';
import { getConversationInbox, getMyNotifications, markNotificationRead } from '@/services/notifications';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function InboxScreen(){
  const router=useRouter();const{colors}=useAppTheme();
  const[conversations,setConversations]=useState<any[]>([]);const[notifications,setNotifications]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setLoading(true);setError(null);const[c,n]=await Promise.all([getConversationInbox(),getMyNotifications(40)]);setConversations(c);setNotifications(n);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar sua caixa de entrada.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  async function openNotification(item:any){if(!item.read_at)await markNotificationRead(item.id).catch(()=>null);const data=item.metadata??{};if(data.battleId)router.push(`/battle/${data.battleId}`);else if(data.senderId)router.push(`/chat/${data.senderId}`);else load();}
  const unread=conversations.reduce((s,x)=>s+Number(x.unread_count??0),0);const unreadAlerts=notifications.filter(x=>!x.read_at).length;
  return <Screen title="Inbox" subtitle="Mensagens, desafios e avisos do Trainer Hub.">
    <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
    {error?<View style={styles.error}><Ionicons name="alert-circle" size={19} color="#FF9FAF"/><Text style={styles.errorText}>{error}</Text></View>:null}
    <View style={styles.summary}><View style={[styles.summaryCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.summaryValue,{color:colors.accent}]}>{unread}</Text><Text style={[styles.summaryLabel,{color:colors.muted}]}>mensagens não lidas</Text></View><View style={[styles.summaryCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.summaryValue,{color:colors.yellow}]}>{unreadAlerts}</Text><Text style={[styles.summaryLabel,{color:colors.muted}]}>avisos novos</Text></View></View>
    {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}
    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle,{color:colors.text}]}>Conversas</Text><Text style={[styles.count,{color:colors.muted}]}>{conversations.length}</Text></View>
    {!loading&&conversations.length===0?<View style={[styles.empty,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="chatbubbles-outline" size={34} color={colors.muted}/><Text style={[styles.emptyTitle,{color:colors.text}]}>Nenhuma conversa ainda</Text><Text style={[styles.emptyText,{color:colors.muted}]}>Abra Amigos e mande uma mensagem para começar.</Text></View>:null}
    <View style={styles.list}>{conversations.map(item=><Pressable key={item.conversation_id} onPress={()=>router.push(`/chat/${item.friend_id}`)} style={[styles.row,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.avatar,{backgroundColor:colors.accentSoft}]}><Text style={[styles.avatarText,{color:colors.accent}]}>{String(item.friend_username??'?').slice(0,1).toUpperCase()}</Text></View><View style={styles.body}><View style={styles.topline}><Text style={[styles.name,{color:colors.text}]}>@{item.friend_username}</Text>{item.last_created_at?<Text style={[styles.time,{color:colors.muted}]}>{new Date(item.last_created_at).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'})}</Text>:null}</View><Text numberOfLines={1} style={[styles.preview,{color:colors.muted}]}>{item.last_kind==='battle_invite'?'🎮 ':''}{item.last_body??'Conversa iniciada'}</Text></View>{Number(item.unread_count)>0?<View style={styles.badge}><Text style={styles.badgeText}>{item.unread_count}</Text></View>:<Ionicons name="chevron-forward" size={19} color={colors.muted}/>}</Pressable>)}</View>
    <View style={styles.sectionHeader}><Text style={[styles.sectionTitle,{color:colors.text}]}>Notificações</Text><Text style={[styles.count,{color:colors.muted}]}>{notifications.length}</Text></View>
    <View style={styles.list}>{notifications.map(item=><Pressable key={item.id} onPress={()=>openNotification(item)} style={[styles.alertRow,{backgroundColor:colors.surface,borderColor:item.read_at?colors.border:colors.accent}]}><View style={[styles.alertIcon,{backgroundColor:item.type==='battle_result'?`${colors.yellow}22`:colors.accentSoft}]}><Ionicons name={item.type==='message'?'chatbubble-ellipses':item.type==='battle_invite'?'game-controller':item.type==='battle_result'?'trophy':'notifications'} size={20} color={item.type==='battle_result'?colors.yellow:colors.accent}/></View><View style={styles.body}><Text style={[styles.alertTitle,{color:colors.text}]}>{item.title}</Text><Text numberOfLines={2} style={[styles.alertText,{color:colors.muted}]}>{item.body}</Text><Text style={[styles.alertTime,{color:colors.muted}]}>{new Date(item.created_at).toLocaleString('pt-BR')}</Text></View>{!item.read_at?<View style={[styles.dot,{backgroundColor:colors.accent}]}/>:null}</Pressable>)}</View>
  </Screen>;
}

const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},error:{flexDirection:'row',alignItems:'center',gap:8,padding:12,borderRadius:14,backgroundColor:'#351A24',borderWidth:1,borderColor:'#683243'},errorText:{flex:1,color:'#FFD7DD',fontSize:11,fontWeight:'700'},summary:{flexDirection:'row',gap:9,flexWrap:'wrap'},summaryCard:{flex:1,minWidth:145,borderRadius:18,padding:14,borderWidth:1},summaryValue:{fontSize:26,fontWeight:'900'},summaryLabel:{fontSize:10,fontWeight:'800',marginTop:2},sectionHeader:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginTop:4},sectionTitle:{fontSize:20,fontWeight:'900'},count:{fontSize:10,fontWeight:'900'},list:{gap:8},row:{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:17,borderWidth:1},avatar:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:18,fontWeight:'900'},body:{flex:1,minWidth:0},topline:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},name:{fontSize:13,fontWeight:'900'},time:{fontSize:8},preview:{fontSize:10,marginTop:4},badge:{minWidth:25,height:25,borderRadius:13,paddingHorizontal:6,alignItems:'center',justifyContent:'center',backgroundColor:'#D84B64'},badgeText:{color:'#fff',fontSize:9,fontWeight:'900'},empty:{padding:24,borderRadius:18,borderWidth:1,alignItems:'center',gap:7},emptyTitle:{fontSize:15,fontWeight:'900'},emptyText:{fontSize:10,textAlign:'center'},alertRow:{flexDirection:'row',alignItems:'center',gap:10,padding:12,borderRadius:17,borderWidth:1},alertIcon:{width:43,height:43,borderRadius:14,alignItems:'center',justifyContent:'center'},alertTitle:{fontSize:12,fontWeight:'900'},alertText:{fontSize:10,lineHeight:15,marginTop:3},alertTime:{fontSize:8,marginTop:5},dot:{width:9,height:9,borderRadius:5}});
