import { VIRTUAL_LIST_PERF_PROPS } from '@/performance/scrollPerformance';
import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { searchWishlistCards } from '@/services/retention';
import { getMarketplaceProDashboard, setMarketplaceProWatch, type MarketProDashboard, type MarketProSelected } from '@/services/proGamepasses';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function MarketplaceProScreen(){
 const router=useRouter();const{colors}=useAppTheme();
 const[data,setData]=useState<MarketProDashboard|null>(null);const[selected,setSelected]=useState<MarketProSelected|null>(null);const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState<string|null>(null);const[notice,setNotice]=useState<string|null>(null);
 const[search,setSearch]=useState('');const[results,setResults]=useState<any[]>([]);const[searching,setSearching]=useState(false);const[picker,setPicker]=useState(false);const[targetUsd,setTargetUsd]=useState('');const[targetCoins,setTargetCoins]=useState('');
 const load=useCallback(async(cardId?:string|null)=>{try{setLoading(true);setError(null);const next=await getMarketplaceProDashboard(cardId);setData(next);setSelected(next.selectedCard??null);if(next.selectedCard){setTargetUsd(next.selectedCard.marketPriceUsd?String(Number(next.selectedCard.marketPriceUsd).toFixed(2)):'');setTargetCoins(next.selectedCard.recommendedCoins?String(next.selectedCard.recommendedCoins):'');}}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o Marketplace Pro.');}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{void load(null);},[load]));
 async function doSearch(q:string){setSearch(q);if(q.trim().length<2){setResults([]);return;}try{setSearching(true);setResults(await searchWishlistCards(q));}finally{setSearching(false);}}
 async function choose(card:any){setPicker(false);setSearch('');setResults([]);await load(String(card.id));}
 async function saveWatch(){if(!selected)return;const usd=Number(targetUsd.replace(',','.'));const coins=Number(targetCoins.replace(/\D/g,''));try{setWorking(true);await setMarketplaceProWatch(selected.cardId,Number.isFinite(usd)&&usd>0?usd:null,Number.isFinite(coins)&&coins>0?coins:null,true);setNotice('Alerta avançado salvo.');await load(selected.cardId);}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar o alerta.');}finally{setWorking(false);}}
 async function removeWatch(cardId:string){try{setWorking(true);await setMarketplaceProWatch(cardId,null,null,false);setNotice('Alerta removido.');await load(selected?.cardId??null);}finally{setWorking(false);}}
 const history=selected?.priceHistory??[];const historyStats=useMemo(()=>{if(!history.length)return null;const values=history.map(x=>Number(x.priceUsd)).filter(Number.isFinite);if(!values.length)return null;return{min:Math.min(...values),max:Math.max(...values),first:values[0],last:values[values.length-1],points:values.length};},[history]);
 return <Screen title="Marketplace Pro" subtitle="Alertas avançados, histórico ampliado e ferramentas para anúncios.">
  <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
  <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.yellow}]}><Ionicons name="analytics" size={30} color={colors.yellow}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>MARKETPLACE PRO ATIVO</Text><Text style={[styles.heroTitle,{color:colors.text}]}>Mercado com contexto, não no escuro</Text><Text style={[styles.helper,{color:colors.muted}]}>Acompanhe até 100 cartas e use até 365 pontos de histórico por carta.</Text></View></View>
  {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.noticeText}>{error}</Text></Pressable>:null}
  {notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={18} color="#59D49A"/><Text style={[styles.noticeText,{color:'#D9FFEC'}]}>{notice}</Text></Pressable>:null}
  {loading&&!data?<ActivityIndicator size="large" color={colors.yellow}/>:null}
  {data?<View style={styles.metrics}><Metric label="ANÚNCIOS ATIVOS" value={data.seller.activeListings.toLocaleString('pt-BR')} colors={colors}/><Metric label="VENDIDOS" value={data.seller.soldListings.toLocaleString('pt-BR')} colors={colors}/><Metric label="LÍQUIDO" value={'🪙 '+data.seller.netCoins.toLocaleString('pt-BR')} colors={colors}/></View>:null}

  <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.rowBetween}><View><Text style={[styles.title,{color:colors.text}]}>Analisar uma carta</Text><Text style={[styles.helper,{color:colors.muted}]}>Preço externo + anúncios ativos + recomendação de anúncio.</Text></View><Pressable onPress={()=>setPicker(true)} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="search" size={17} color="#07111F"/><Text style={styles.primaryText}>BUSCAR CARTA</Text></Pressable></View>
   {selected?<View style={[styles.selected,{backgroundColor:colors.surfaceAlt,borderColor:colors.accent}]}>{selected.image?<Image source={{uri:selected.image}} style={styles.cardImage} resizeMode="contain"/>:null}<View style={{flex:1,minWidth:0}}><Text style={[styles.selectedName,{color:colors.text}]}>{selected.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{selected.setName}</Text><Text style={[styles.price,{color:colors.yellow}]}>{selected.marketPriceUsd!=null?'US$ '+Number(selected.marketPriceUsd).toFixed(2):'US$ —'}</Text></View><Pressable onPress={()=>router.push(('/card/'+selected.cardId) as never)}><Ionicons name="open-outline" size={20} color={colors.accent}/></Pressable></View>:null}
  </View>

  {selected?<><View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Ferramenta de anúncio</Text><View style={styles.metrics}><Metric label="MENOR ATIVO" value={selected.listingStats?.minCoins?('🪙 '+Number(selected.listingStats.minCoins).toLocaleString('pt-BR')):'—'} colors={colors}/><Metric label="MÉDIA" value={selected.listingStats?.avgCoins?('🪙 '+Number(selected.listingStats.avgCoins).toLocaleString('pt-BR')):'—'} colors={colors}/><Metric label="RECOMENDADO" value={selected.recommendedCoins?('🪙 '+Number(selected.recommendedCoins).toLocaleString('pt-BR')):'—'} colors={colors}/></View><Text style={[styles.helper,{color:colors.muted}]}>O recomendado usa 98% da média dos anúncios ativos. É uma referência; você continua decidindo o preço.</Text><Pressable onPress={()=>router.push('/marketplace')} style={[styles.secondary,{borderColor:colors.accent}]}><Ionicons name="storefront" size={17} color={colors.accent}/><Text style={[styles.secondaryText,{color:colors.accent}]}>ABRIR MARKETPLACE</Text></Pressable></View>
   <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Histórico de preço ampliado</Text>{historyStats?<><View style={styles.metrics}><Metric label="PONTOS" value={String(historyStats.points)} colors={colors}/><Metric label="MÍNIMO" value={'US$ '+historyStats.min.toFixed(2)} colors={colors}/><Metric label="MÁXIMO" value={'US$ '+historyStats.max.toFixed(2)} colors={colors}/></View><View style={styles.history}>{history.slice(-12).map((p,i)=>{const span=Math.max(.01,historyStats.max-historyStats.min);const pct=10+((Number(p.priceUsd)-historyStats.min)/span)*90;return <View key={p.recordedAt+'-'+i} style={styles.historyCol}><View style={[styles.bar,{height:`${pct}%` as any,backgroundColor:colors.accent}]}/><Text style={[styles.barLabel,{color:colors.muted}]}>{Number(p.priceUsd).toFixed(0)}</Text></View>;})}</View></>:<Text style={[styles.helper,{color:colors.muted}]}>Ainda não há histórico suficiente para esta carta.</Text>}</View>
   <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Alerta Pro</Text><View style={styles.row}><TextInput value={targetUsd} onChangeText={setTargetUsd} keyboardType="decimal-pad" placeholder="Alvo US$" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/><TextInput value={targetCoins} onChangeText={v=>setTargetCoins(v.replace(/\D/g,''))} keyboardType="number-pad" placeholder="Alvo Coins" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text,borderColor:colors.border,backgroundColor:colors.surfaceAlt}]}/><Pressable disabled={working} onPress={()=>void saveWatch()} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="notifications" size={17} color="#07111F"/><Text style={styles.primaryText}>SALVAR ALERTA</Text></Pressable></View><Text style={[styles.helper,{color:colors.muted}]}>O alvo fica salvo no servidor para você reencontrar a carta e comparar com o preço atual.</Text></View></>:null}

  {data?.watches?.length?<><Text style={[styles.sectionTitle,{color:colors.text}]}>Favoritos e alertas avançados</Text><View style={styles.stack}>{data.watches.map(w=><View key={w.cardId} style={[styles.watch,{backgroundColor:colors.surface,borderColor:colors.border}]}>{w.image?<Image source={{uri:w.image}} style={styles.watchImage} resizeMode="contain"/>:null}<Pressable onPress={()=>void load(w.cardId)} style={{flex:1,minWidth:0}}><Text style={[styles.watchName,{color:colors.text}]}>{w.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{w.setName}</Text><Text style={[styles.meta,{color:colors.yellow}]}>{w.targetPriceUsd?`Alvo US$ ${Number(w.targetPriceUsd).toFixed(2)}`:''}{w.targetPriceUsd&&w.targetListingCoins?' • ':''}{w.targetListingCoins?`🪙 ${Number(w.targetListingCoins).toLocaleString('pt-BR')}`:''}</Text></Pressable><Pressable onPress={()=>void removeWatch(w.cardId)}><Ionicons name="trash" size={18} color="#FF8998"/></Pressable></View>)}</View></>:null}

  <Modal visible={picker} animationType="slide" onRequestClose={()=>setPicker(false)}><View style={[styles.modal,{backgroundColor:colors.bg}]}><View style={styles.modalHead}><View><Text style={[styles.kicker,{color:colors.yellow}]}>BUSCA GLOBAL</Text><Text style={[styles.modalTitle,{color:colors.text}]}>Escolher carta</Text></View><Pressable onPress={()=>setPicker(false)}><Ionicons name="close" size={25} color={colors.text}/></Pressable></View><View style={[styles.searchBox,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={18} color={colors.muted}/><TextInput autoFocus value={search} onChangeText={v=>void doSearch(v)} placeholder="Digite pelo menos 2 letras..." placeholderTextColor={colors.muted} style={[styles.searchInput,{color:colors.text}]}/></View>{searching?<ActivityIndicator color={colors.yellow}/>:null}<FlatList {...VIRTUAL_LIST_PERF_PROPS} data={results} keyExtractor={(item)=>String(item.id)} contentContainerStyle={styles.list} renderItem={({item})=><Pressable onPress={()=>void choose(item)} style={[styles.resultRow,{backgroundColor:colors.surface,borderColor:colors.border}]}>{item.image_small?<Image source={{uri:item.image_small}} style={styles.resultImage} resizeMode="contain"/>:<View style={styles.resultImage}/>}<View style={{flex:1}}><Text style={[styles.watchName,{color:colors.text}]}>{item.pokemon_name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{item.set_name} • {item.rarity??'—'}</Text><Text style={[styles.meta,{color:colors.yellow}]}>{item.market_price_usd!=null?'US$ '+Number(item.market_price_usd).toFixed(2):'US$ —'}</Text></View><Ionicons name="chevron-forward" size={20} color={colors.accent}/></Pressable>}/></View></Modal>
 </Screen>;
}
function Metric({label,value,colors}:{label:string;value:string;colors:any}){return <View style={[styles.metric,{backgroundColor:colors.surfaceAlt,borderColor:colors.border}]}><Text style={[styles.metricLabel,{color:colors.muted}]}>{label}</Text><Text numberOfLines={1} style={[styles.metricValue,{color:colors.text}]}>{value}</Text></View>;}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},hero:{borderWidth:1,borderRadius:20,padding:15,flexDirection:'row',gap:11,alignItems:'center'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},heroTitle:{fontSize:18,fontWeight:'900',marginTop:2},helper:{fontSize:9,lineHeight:14,marginTop:3},notice:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',gap:8,alignItems:'center'},noticeText:{flex:1,color:'#FFD7DD',fontSize:9,fontWeight:'800'},metrics:{flexDirection:'row',gap:7,flexWrap:'wrap'},metric:{flexGrow:1,flexBasis:115,borderWidth:1,borderRadius:13,padding:10},metricLabel:{fontSize:7,fontWeight:'900'},metricValue:{fontSize:14,fontWeight:'900',marginTop:2},panel:{borderWidth:1,borderRadius:18,padding:13,gap:10},rowBetween:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:10,flexWrap:'wrap'},title:{fontSize:17,fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900'},primary:{minHeight:42,paddingHorizontal:12,borderRadius:11,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},primaryText:{color:'#07111F',fontSize:8,fontWeight:'900'},secondary:{minHeight:42,paddingHorizontal:12,borderRadius:11,borderWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},secondaryText:{fontSize:8,fontWeight:'900'},selected:{minHeight:96,borderWidth:1,borderRadius:14,padding:9,flexDirection:'row',alignItems:'center',gap:10},cardImage:{width:58,height:78},selectedName:{fontSize:13,fontWeight:'900'},meta:{fontSize:7.5,marginTop:2},price:{fontSize:11,fontWeight:'900',marginTop:3},history:{height:130,flexDirection:'row',alignItems:'flex-end',gap:5,paddingTop:10},historyCol:{flex:1,height:'100%',alignItems:'center',justifyContent:'flex-end'},bar:{width:'80%',minHeight:3,borderRadius:4},barLabel:{fontSize:6,marginTop:3},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},input:{flex:1,minWidth:130,height:44,borderWidth:1,borderRadius:11,paddingHorizontal:11},stack:{gap:7},watch:{minHeight:76,borderWidth:1,borderRadius:13,padding:8,flexDirection:'row',alignItems:'center',gap:9},watchImage:{width:48,height:62},watchName:{fontSize:10,fontWeight:'900'},modal:{flex:1,paddingTop:45},modalHead:{padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{fontSize:24,fontWeight:'900'},searchBox:{marginHorizontal:12,minHeight:46,borderWidth:1,borderRadius:12,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:7},searchInput:{flex:1},list:{padding:12,gap:7},resultRow:{minHeight:80,borderWidth:1,borderRadius:13,padding:8,flexDirection:'row',alignItems:'center',gap:9},resultImage:{width:50,height:66}});
