import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { claimMission, getDailyMissions } from '@/services/missions';
import { gameTheme } from '@/theme/gameTheme';

export default function MissionsScreen(){
  const router=useRouter();const [missions,setMissions]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [working,setWorking]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setLoading(true);setMissions(await getDailyMissions());}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível carregar as missões.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  async function claim(id:string){try{setWorking(id);const reward=await claimMission(id);setNotice(`Recompensa coletada: 🪙 ${Number(reward?.coins??0).toLocaleString('pt-BR')} + ${Number(reward?.xp??0)} XP`);await load();}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível coletar.');}finally{setWorking(null);}}
  return <Screen title="Missões Diárias" subtitle="Jogue, batalhe e abra boosters para alimentar sua economia todos os dias.">
    <Pressable style={styles.backRow} onPress={()=>router.back()}><Ionicons name="arrow-back" size={18} color="#A9BDD7"/><Text style={styles.backText}>Voltar</Text></Pressable>
    {notice?<Pressable style={styles.notice} onPress={()=>setNotice(null)}><Ionicons name="gift" size={19} color={gameTheme.colors.yellow}/><Text style={styles.noticeText}>{notice}</Text></Pressable>:null}
    <View style={styles.hero}><View><Text style={styles.kicker}>RESET DIÁRIO</Text><Text style={styles.heroTitle}>Complete e resgate</Text><Text style={styles.heroText}>As recompensas são registradas no servidor e só podem ser coletadas uma vez por dia.</Text></View><Ionicons name="calendar" size={42} color={gameTheme.colors.yellow}/></View>
    {loading?<ActivityIndicator size="large" color={gameTheme.colors.yellow}/>:null}
    <View style={styles.list}>{missions.map((m)=>{const progress=Math.min(Number(m.progress??0),Number(m.target));const done=progress>=m.target;const pct=Math.min(100,(progress/m.target)*100);return <View key={m.id} style={[styles.card,done&&styles.cardDone]}><View style={styles.top}><View style={styles.icon}><Ionicons name={m.event_type.includes('battle')?'game-controller':m.event_type.includes('pack')?'cube':'star'} size={21} color={done?'#65D894':gameTheme.colors.blue}/></View><View style={{flex:1}}><Text style={styles.title}>{m.title}</Text><Text style={styles.desc}>{m.description}</Text></View><View style={styles.reward}><Text style={styles.coins}>🪙 {m.reward_coins}</Text><Text style={styles.xp}>+{m.reward_xp} XP</Text></View></View><View style={styles.progressRow}><View style={styles.track}><View style={[styles.fill,{width:`${pct}%`}]} /></View><Text style={styles.progressText}>{progress}/{m.target}</Text></View>{m.claimed?<View style={styles.claimed}><Ionicons name="checkmark-circle" size={17} color="#65D894"/><Text style={styles.claimedText}>COLETADA</Text></View>:done?<Pressable style={styles.claimButton} onPress={()=>claim(m.id)} disabled={working===m.id}><Text style={styles.claimText}>{working===m.id?'COLETANDO...':'COLETAR RECOMPENSA'}</Text></Pressable>:null}</View>})}</View>
  </Screen>
}
const styles=StyleSheet.create({backRow:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{color:'#A9BDD7',fontSize:12,fontWeight:'800'},notice:{flexDirection:'row',gap:8,padding:11,borderRadius:14,backgroundColor:'#2B2818',borderWidth:1,borderColor:'#5A5125'},noticeText:{flex:1,color:'#F8EFCB',fontSize:11,fontWeight:'700'},hero:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:16,padding:18,borderRadius:22,backgroundColor:'#10284B',borderWidth:1,borderColor:'#285A9A'},kicker:{color:gameTheme.colors.yellow,fontSize:9,fontWeight:'900',letterSpacing:1.4},heroTitle:{color:'#fff',fontSize:22,fontWeight:'900',marginTop:3},heroText:{color:'#9FB3CF',fontSize:10,lineHeight:15,maxWidth:520,marginTop:3},list:{gap:9},card:{padding:14,borderRadius:18,backgroundColor:'#101D30',borderWidth:1,borderColor:'#263E5C',gap:10},cardDone:{borderColor:'#2D664C'},top:{flexDirection:'row',alignItems:'center',gap:11},icon:{width:44,height:44,borderRadius:14,alignItems:'center',justifyContent:'center',backgroundColor:'#0B1829'},title:{color:'#fff',fontSize:14,fontWeight:'900'},desc:{color:'#8094AF',fontSize:9,lineHeight:14,marginTop:3},reward:{alignItems:'flex-end'},coins:{color:gameTheme.colors.yellow,fontSize:11,fontWeight:'900'},xp:{color:'#82A5D4',fontSize:8,fontWeight:'900',marginTop:2},progressRow:{flexDirection:'row',alignItems:'center',gap:8},track:{flex:1,height:8,borderRadius:999,backgroundColor:'#1B2B40',overflow:'hidden'},fill:{height:'100%',backgroundColor:'#65D894',borderRadius:999},progressText:{color:'#91A5C0',fontSize:9,fontWeight:'900'},claimButton:{alignItems:'center',padding:11,borderRadius:11,backgroundColor:gameTheme.colors.yellow},claimText:{color:'#07111F',fontSize:9,fontWeight:'900'},claimed:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6,padding:8},claimedText:{color:'#65D894',fontSize:8,fontWeight:'900'}});
