import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { getMuseumProDashboard, type MuseumProDashboard } from '@/services/proGamepasses';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function MuseumProScreen(){
 const router=useRouter();const{colors}=useAppTheme();const[data,setData]=useState<MuseumProDashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setError(null);setData(await getMuseumProDashboard());}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o Museum Pro.');}finally{setLoading(false);}},[]);useFocusEffect(useCallback(()=>{void load();},[load]));
 const maxActivity=useMemo(()=>Math.max(1,...(data?.activityByMonth??[]).map(x=>Number(x.packs)+Number(x.battles))),[data]);
 return <Screen title="Museum Pro" subtitle="Uma visão expandida da trajetória, valor e história da sua conta.">
  <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
  <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.yellow}]}><Ionicons name="library" size={31} color={colors.yellow}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>MUSEUM PRO ATIVO</Text><Text style={[styles.heroTitle,{color:colors.text}]}>Sua conta como uma linha do tempo</Text><Text style={[styles.helper,{color:colors.muted}]}>Painel premium somente de leitura: nenhuma carta é consumida ou alterada.</Text></View><Pressable onPress={()=>router.push('/account-museum')} style={[styles.smallButton,{borderColor:colors.accent}]}><Text style={[styles.smallButtonText,{color:colors.accent}]}>MUSEU CLÁSSICO</Text></Pressable></View>
  {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.noticeText}>{error}</Text></Pressable>:null}
  {loading&&!data?<ActivityIndicator size="large" color={colors.yellow}/>:null}
  {data?<><View style={styles.metrics}><Metric label="CARTAS ÚNICAS" value={data.summary.uniqueCards.toLocaleString('pt-BR')} colors={colors}/><Metric label="CÓPIAS" value={data.summary.totalCopies.toLocaleString('pt-BR')} colors={colors}/><Metric label="VALOR" value={'US$ '+Number(data.summary.collectionValueUsd).toFixed(2)} colors={colors}/><Metric label="BOOSTERS" value={data.summary.packsOpened.toLocaleString('pt-BR')} colors={colors}/><Metric label="BATALHAS" value={data.summary.battlesPlayed.toLocaleString('pt-BR')} colors={colors}/><Metric label="VITÓRIAS" value={data.summary.wins.toLocaleString('pt-BR')} colors={colors}/><Metric label="TROCAS" value={data.summary.tradesCompleted.toLocaleString('pt-BR')} colors={colors}/></View>
   <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.title,{color:colors.text}]}>Trajetória dos últimos 12 meses</Text><Text style={[styles.helper,{color:colors.muted}]}>Cada coluna soma boosters abertos e batalhas iniciadas naquele mês.</Text><View style={styles.activity}>{data.activityByMonth.map(m=>{const total=Number(m.packs)+Number(m.battles);return <View key={m.month} style={styles.activityCol}><Text style={[styles.activityValue,{color:colors.text}]}>{total}</Text><View style={[styles.activityTrack,{backgroundColor:colors.surfaceAlt}]}><View style={[styles.activityBar,{backgroundColor:colors.accent,height:`${Math.max(4,total/maxActivity*100)}%` as any}]}/></View><Text style={[styles.month,{color:colors.muted}]}>{m.month.slice(5)}</Text></View>;})}</View></View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>20 cartas mais valiosas</Text><View style={styles.cards}>{data.topCards.map((c,index)=><Pressable key={c.id} onPress={()=>router.push(('/card/'+c.id) as never)} style={[styles.card,{backgroundColor:colors.surface,borderColor:index<3?colors.yellow:colors.border}]}><View style={styles.rank}><Text style={[styles.rankText,{color:index<3?colors.yellow:colors.muted}]}>#{index+1}</Text></View>{c.image?<Image source={{uri:c.image}} style={styles.cardImage} resizeMode="contain"/>:null}<Text numberOfLines={1} style={[styles.cardName,{color:colors.text}]}>{c.name}</Text><Text numberOfLines={1} style={[styles.meta,{color:colors.muted}]}>{c.setName} • {c.rarity??'—'}</Text><Text style={[styles.price,{color:colors.yellow}]}>{c.marketPriceUsd!=null?'US$ '+Number(c.marketPriceUsd).toFixed(2):'US$ —'} • {c.quantity}x</Text></Pressable>)}</View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Sets que mais representam seu patrimônio</Text><View style={styles.stack}>{data.sets.map(s=><Pressable key={s.setId} onPress={()=>router.push(('/set/'+s.setId) as never)} style={[styles.row,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="albums" size={20} color={colors.accent}/><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={[styles.rowName,{color:colors.text}]}>{s.setName}</Text><Text style={[styles.meta,{color:colors.muted}]}>{s.owned} carta(s) única(s)</Text></View><Text style={[styles.rowValue,{color:colors.yellow}]}>US$ {Number(s.valueUsd).toFixed(2)}</Text></Pressable>)}</View>
   <Text style={[styles.sectionTitle,{color:colors.text}]}>Mapa de raridades</Text><View style={styles.rarities}>{data.rarities.map(r=><View key={r.rarity} style={[styles.rarity,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text numberOfLines={1} style={[styles.rarityName,{color:colors.text}]}>{r.rarity}</Text><Text style={[styles.rarityValue,{color:colors.accent}]}>{r.unique}</Text><Text style={[styles.meta,{color:colors.muted}]}>{r.copies} cópia(s)</Text></View>)}</View>
   {data.displayCards.length?<><Text style={[styles.sectionTitle,{color:colors.text}]}>Exposição atual</Text><View style={styles.cards}>{data.displayCards.map(c=><Pressable key={c.slot} onPress={()=>router.push(('/card/'+c.id) as never)} style={[styles.display,{backgroundColor:colors.surface,borderColor:colors.border}]}>{c.image?<Image source={{uri:c.image}} style={styles.displayImage} resizeMode="contain"/>:null}<Text style={[styles.meta,{color:colors.muted}]}>SLOT {c.slot}</Text><Text numberOfLines={1} style={[styles.cardName,{color:colors.text}]}>{c.name}</Text></Pressable>)}</View></>:null}
  </>:null}
 </Screen>;
}
function Metric({label,value,colors}:{label:string;value:string;colors:any}){return <View style={[styles.metric,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.metricLabel,{color:colors.muted}]}>{label}</Text><Text numberOfLines={1} style={[styles.metricValue,{color:colors.text}]}>{value}</Text></View>;}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',alignItems:'center',gap:7},backText:{fontSize:12,fontWeight:'800'},hero:{borderWidth:1,borderRadius:20,padding:15,flexDirection:'row',gap:11,alignItems:'center',flexWrap:'wrap'},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},heroTitle:{fontSize:18,fontWeight:'900',marginTop:2},helper:{fontSize:9,lineHeight:14,marginTop:3},smallButton:{minHeight:36,borderWidth:1,borderRadius:10,paddingHorizontal:9,alignItems:'center',justifyContent:'center'},smallButtonText:{fontSize:7,fontWeight:'900'},notice:{borderWidth:1,borderRadius:13,padding:10,flexDirection:'row',gap:8,alignItems:'center'},noticeText:{flex:1,color:'#FFD7DD',fontSize:9,fontWeight:'800'},metrics:{flexDirection:'row',gap:7,flexWrap:'wrap'},metric:{flexGrow:1,flexBasis:115,borderWidth:1,borderRadius:13,padding:10},metricLabel:{fontSize:7,fontWeight:'900'},metricValue:{fontSize:14,fontWeight:'900',marginTop:2},panel:{borderWidth:1,borderRadius:18,padding:13,gap:9},title:{fontSize:17,fontWeight:'900'},sectionTitle:{fontSize:18,fontWeight:'900'},activity:{height:160,flexDirection:'row',gap:5,alignItems:'flex-end'},activityCol:{flex:1,height:'100%',alignItems:'center',justifyContent:'flex-end'},activityValue:{fontSize:7,fontWeight:'900'},activityTrack:{height:115,width:'80%',borderRadius:7,overflow:'hidden',justifyContent:'flex-end',marginTop:3},activityBar:{width:'100%',borderRadius:7},month:{fontSize:6.5,marginTop:3},cards:{flexDirection:'row',flexWrap:'wrap',gap:7},card:{flexGrow:1,flexBasis:135,maxWidth:180,borderWidth:1,borderRadius:13,padding:7},rank:{position:'absolute',top:6,left:6,zIndex:2,backgroundColor:'rgba(0,0,0,.65)',paddingHorizontal:5,paddingVertical:3,borderRadius:999},rankText:{fontSize:7,fontWeight:'900'},cardImage:{width:'100%',height:155},cardName:{fontSize:9,fontWeight:'900',marginTop:4},meta:{fontSize:7.3,marginTop:2},price:{fontSize:8,fontWeight:'900',marginTop:3},stack:{gap:7},row:{minHeight:62,borderWidth:1,borderRadius:13,padding:9,flexDirection:'row',alignItems:'center',gap:9},rowName:{fontSize:10,fontWeight:'900'},rowValue:{fontSize:10,fontWeight:'900'},rarities:{flexDirection:'row',flexWrap:'wrap',gap:7},rarity:{flexGrow:1,flexBasis:130,minWidth:120,borderWidth:1,borderRadius:13,padding:10},rarityName:{fontSize:8,fontWeight:'900'},rarityValue:{fontSize:20,fontWeight:'900',marginTop:2},display:{flexGrow:1,flexBasis:120,maxWidth:160,borderWidth:1,borderRadius:13,padding:7},displayImage:{width:'100%',height:145}});
