import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, Image, Modal, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { listPacks, type Pack } from '@/services/packs';
import { autoOpenPacks, getBoosterPerks, type BoosterPerks } from '@/services/boosterPerks';
import { useWallet } from '@/wallet/WalletProvider';
import { useAppTheme } from '@/theme/ThemeProvider';
import { VIRTUAL_LIST_PERF_PROPS } from '@/performance/scrollPerformance';

type QueueEntry={id:string;packId:string;quantity:number};
const ROW_HEIGHT=88;

export default function PackQueueScreen(){
  const router=useRouter();const{colors}=useAppTheme();const wallet=useWallet();
  const[packs,setPacks]=useState<Pack[]>([]);const[perks,setPerks]=useState<BoosterPerks|null>(null);const[queue,setQueue]=useState<QueueEntry[]>([]);const[pickerOpen,setPickerOpen]=useState(false);const[search,setSearch]=useState('');const[quantityText,setQuantityText]=useState('5');const[loading,setLoading]=useState(true);const[working,setWorking]=useState(false);const[error,setError]=useState<string|null>(null);const[summary,setSummary]=useState<{packs:number;cards:number;coins:number;diamonds:number}|null>(null);
  const load=useCallback(async()=>{try{setLoading(true);setError(null);const[p,perk]=await Promise.all([listPacks(),getBoosterPerks()]);setPacks(p);setPerks(perk);}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a Pack Queue.');}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  const byId=useMemo(()=>new Map(packs.map(p=>[p.id,p])),[packs]);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return q?packs.filter(p=>p.name.toLowerCase().includes(q)||p.set_id.toLowerCase().includes(q)):packs;},[packs,search]);
  const totals=useMemo(()=>queue.reduce((acc,item)=>{const p=byId.get(item.packId);if(!p)return acc;const cost=p.price*item.quantity;if(p.currency==='diamonds')acc.diamonds+=cost;else acc.coins+=cost;acc.packs+=item.quantity;return acc;},{coins:0,diamonds:0,packs:0}),[byId,queue]);
  function add(pack:Pack){if(queue.length>=8){setError('A fila aceita até 8 linhas por vez para manter a abertura segura e fácil de acompanhar.');setPickerOpen(false);return;}const max=Math.max(1,Number(perks?.maxAutoOpenQuantity??50));const quantity=Math.max(1,Math.min(max,Number(quantityText.replace(/\D/g,''))||1));setQueue(current=>[...current,{id:`${Date.now()}-${Math.random()}`,packId:pack.id,quantity}]);setPickerOpen(false);setSearch('');}
  function changeQuantity(id:string,text:string){const max=Math.max(1,Number(perks?.maxAutoOpenQuantity??50));const n=Math.max(1,Math.min(max,Number(text.replace(/\D/g,''))||1));setQueue(current=>current.map(item=>item.id===id?{...item,quantity:n}:item));}
  async function run(){if(!perks?.packQueueGamepass||!perks.autoOpenGamepass||!queue.length||working)return;if(wallet.coins<totals.coins||wallet.diamonds<totals.diamonds){setError('Saldo insuficiente para o custo máximo da fila.');return;}try{setWorking(true);setError(null);setSummary(null);let opened=0,cards=0,coins=0,diamonds=0;for(const item of queue){const result=await autoOpenPacks(item.packId,item.quantity);opened+=result.quantity;cards+=result.cards.length;coins+=result.totalCoinsSpent;diamonds+=result.totalDiamondsSpent;}setSummary({packs:opened,cards,coins,diamonds});setQueue([]);await Promise.all([wallet.refresh(),load()]);}catch(e){await wallet.refresh().catch(()=>null);setError((e instanceof Error?e.message:'A fila foi interrompida.')+' Os lotes concluídos antes do erro permanecem válidos e não serão cobrados novamente ao repetir.');}finally{setWorking(false);}}
  function confirm(){const message=`Abrir ${totals.packs} booster(s) em ${queue.length} lote(s)?\n\nCusto máximo: 🪙 ${totals.coins.toLocaleString('pt-BR')} • 💎 ${totals.diamonds.toLocaleString('pt-BR')}\n\nCada linha é confirmada pelo servidor e usa idempotência para evitar cobrança duplicada.`;if(Platform.OS==='web'){void run();return;}Alert.alert('Confirmar Pack Queue',message,[{text:'Cancelar',style:'cancel'},{text:'ABRIR FILA',onPress:()=>void run()}]);}
  if(loading&&!perks)return <Screen title="Pack Queue" subtitle="Fila automática de boosters"><ActivityIndicator size="large" color={colors.yellow}/></Screen>;
  return <Screen title="Pack Queue" subtitle="Monte uma sequência com boosters diferentes e veja o custo total antes de começar.">
    <Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>
    <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:perks?.packQueueGamepass?'#59D49A':colors.yellow}]}><Ionicons name={perks?.packQueueGamepass?'list':'lock-closed'} size={29} color={perks?.packQueueGamepass?'#59D49A':colors.yellow}/><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>GAMEPASS PACK QUEUE</Text><Text style={[styles.title,{color:colors.text}]}>{perks?.packQueueGamepass?'FILA LIBERADA':'GAMEPASS NECESSÁRIA'}</Text><Text style={[styles.help,{color:colors.muted}]}>{perks?.packQueueGamepass?'Adicione até 8 lotes. Cada lote respeita o limite da sua Auto Booster.':'Pack Queue é incluída no Trainer Plus ou pode ser ativada separadamente pelo dono.'}</Text></View></View>
    {!perks?.packQueueGamepass?<Pressable onPress={()=>router.push('/gamepasses')} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="diamond" size={18} color="#07111F"/><Text style={styles.primaryText}>VER GAMEPASSES</Text></Pressable>:null}
    {error?<Pressable onPress={()=>setError(null)} style={[styles.notice,{backgroundColor:'#351A24',borderColor:'#683243'}]}><Ionicons name="alert-circle" size={18} color="#FF8998"/><Text style={styles.error}>{error}</Text></Pressable>:null}
    <View style={[styles.panel,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={styles.panelHead}><View><Text style={[styles.section,{color:colors.text}]}>Sua fila</Text><Text style={[styles.help,{color:colors.muted}]}>{queue.length}/8 lote(s) • até {perks?.maxAutoOpenQuantity??50} por linha</Text></View><Pressable disabled={!perks?.packQueueGamepass||queue.length>=8} onPress={()=>setPickerOpen(true)} style={[styles.add,{backgroundColor:colors.yellow},(!perks?.packQueueGamepass||queue.length>=8)&&styles.disabled]}><Ionicons name="add" size={18} color="#07111F"/><Text style={styles.addText}>ADICIONAR</Text></Pressable></View>
      {queue.length===0?<View style={[styles.empty,{backgroundColor:colors.surfaceAlt}]}><Ionicons name="albums-outline" size={31} color={colors.muted}/><Text style={[styles.emptyTitle,{color:colors.text}]}>Fila vazia</Text><Text style={[styles.help,{color:colors.muted}]}>Adicione boosters e escolha a quantidade de cada um.</Text></View>:null}
      {queue.map((item,index)=>{const pack=byId.get(item.packId);if(!pack)return null;return <View key={item.id} style={[styles.queueRow,{backgroundColor:colors.surfaceAlt,borderColor:colors.border}]}>{pack.booster_art_url?<Image source={{uri:pack.booster_art_url}} style={styles.image} resizeMode="contain" resizeMethod="resize" fadeDuration={0}/>:<View style={styles.image}/>}<View style={{flex:1,minWidth:0}}><Text style={[styles.index,{color:colors.accent}]}>#{index+1}</Text><Text numberOfLines={2} style={[styles.name,{color:colors.text}]}>{pack.name}</Text><Text style={[styles.price,{color:colors.yellow}]}>{pack.currency==='diamonds'?'💎':'🪙'} {(pack.price*item.quantity).toLocaleString('pt-BR')}</Text></View><TextInput value={String(item.quantity)} onChangeText={text=>changeQuantity(item.id,text)} keyboardType="number-pad" maxLength={3} style={[styles.qty,{backgroundColor:colors.surface,borderColor:colors.border,color:colors.text}]}/><Pressable disabled={working} onPress={()=>setQueue(current=>current.filter(x=>x.id!==item.id))} style={styles.remove}><Ionicons name="trash" size={16} color="#FF8998"/></Pressable></View>;})}
    </View>
    <View style={[styles.total,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><View><Text style={[styles.totalLabel,{color:colors.muted}]}>BOOSTERS</Text><Text style={[styles.totalValue,{color:colors.text}]}>{totals.packs}</Text></View><View><Text style={[styles.totalLabel,{color:colors.muted}]}>COINS</Text><Text style={[styles.totalValue,{color:colors.yellow}]}>🪙 {totals.coins.toLocaleString('pt-BR')}</Text></View><View><Text style={[styles.totalLabel,{color:colors.muted}]}>DIAMANTES</Text><Text style={[styles.totalValue,{color:colors.yellow}]}>💎 {totals.diamonds.toLocaleString('pt-BR')}</Text></View></View>
    <Pressable disabled={!perks?.packQueueGamepass||!perks?.autoOpenGamepass||!queue.length||working} onPress={confirm} style={[styles.primary,{backgroundColor:colors.yellow},(!perks?.packQueueGamepass||!perks?.autoOpenGamepass||!queue.length||working)&&styles.disabled]}>{working?<ActivityIndicator color="#07111F"/>:<Ionicons name="play" size={19} color="#07111F"/>}<Text style={styles.primaryText}>{working?'PROCESSANDO FILA...':'ABRIR FILA'}</Text></Pressable>
    {summary?<View style={[styles.result,{backgroundColor:'#15392A',borderColor:'#59D49A'}]}><Ionicons name="checkmark-circle" size={24} color="#59D49A"/><View style={{flex:1}}><Text style={styles.resultTitle}>Fila concluída</Text><Text style={styles.resultText}>{summary.packs} booster(s) • {summary.cards} cartas • 🪙 {summary.coins.toLocaleString('pt-BR')} • 💎 {summary.diamonds.toLocaleString('pt-BR')}</Text></View></View>:null}
    <Modal visible={pickerOpen} transparent animationType="fade" onRequestClose={()=>setPickerOpen(false)}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} onPress={()=>setPickerOpen(false)}/><View style={[styles.picker,{backgroundColor:colors.bg,borderColor:colors.border}]}><View style={styles.pickerHead}><View><Text style={[styles.pickerTitle,{color:colors.text}]}>Adicionar booster</Text><Text style={[styles.help,{color:colors.muted}]}>Quantidade inicial para esta linha</Text></View><Pressable onPress={()=>setPickerOpen(false)}><Ionicons name="close" size={23} color={colors.text}/></Pressable></View><TextInput value={quantityText} onChangeText={v=>setQuantityText(v.replace(/\D/g,'').slice(0,3))} keyboardType="number-pad" placeholder="Quantidade" placeholderTextColor={colors.muted} style={[styles.pickerQty,{backgroundColor:colors.surface,borderColor:colors.border,color:colors.text}]}/><View style={[styles.search,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={18} color={colors.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Buscar booster ou set..." placeholderTextColor={colors.muted} style={[styles.searchInput,{color:colors.text}]}/></View><FlatList {...VIRTUAL_LIST_PERF_PROPS} data={filtered} keyExtractor={p=>p.id} getItemLayout={(_,index)=>({length:ROW_HEIGHT,offset:ROW_HEIGHT*index,index})} contentContainerStyle={styles.list} renderItem={({item})=><Pressable onPress={()=>add(item)} style={[styles.pickRow,{backgroundColor:colors.surface,borderColor:colors.border}]}>{item.booster_art_url?<Image source={{uri:item.booster_art_url}} style={styles.pickImage} resizeMode="contain" resizeMethod="resize" fadeDuration={0}/>:<View style={styles.pickImage}/>}<View style={{flex:1}}><Text numberOfLines={2} style={[styles.name,{color:colors.text}]}>{item.name}</Text><Text style={[styles.price,{color:colors.yellow}]}>{item.currency==='diamonds'?'💎':'🪙'} {item.price.toLocaleString('pt-BR')}</Text></View><Ionicons name="add-circle" size={20} color={colors.accent}/></Pressable>}/></View></View></Modal>
  </Screen>;
}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',gap:7,alignItems:'center'},backText:{fontSize:11,fontWeight:'800'},hero:{borderRadius:20,borderWidth:1,padding:14,flexDirection:'row',alignItems:'center',gap:11},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},title:{fontSize:19,fontWeight:'900',marginTop:2},help:{fontSize:8.3,lineHeight:12,marginTop:2},notice:{borderRadius:13,borderWidth:1,padding:10,flexDirection:'row',gap:8},error:{color:'#FFD7DD',fontSize:8.5,lineHeight:13,flex:1},panel:{borderRadius:18,borderWidth:1,padding:12,gap:8},panelHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},section:{fontSize:16,fontWeight:'900'},add:{minHeight:38,borderRadius:10,paddingHorizontal:10,flexDirection:'row',alignItems:'center',gap:5},addText:{fontSize:8,fontWeight:'900',color:'#07111F'},empty:{borderRadius:13,padding:20,alignItems:'center',gap:4},emptyTitle:{fontSize:11,fontWeight:'900'},queueRow:{borderRadius:13,borderWidth:1,padding:7,flexDirection:'row',alignItems:'center',gap:8},image:{width:43,height:60},index:{fontSize:7,fontWeight:'900'},name:{fontSize:9.5,fontWeight:'900'},price:{fontSize:8,fontWeight:'900',marginTop:2},qty:{width:58,height:40,borderRadius:10,borderWidth:1,textAlign:'center',fontWeight:'900'},remove:{width:34,height:34,borderRadius:10,backgroundColor:'#351A24',alignItems:'center',justifyContent:'center'},total:{borderRadius:15,borderWidth:1,padding:11,flexDirection:'row',gap:16,flexWrap:'wrap',justifyContent:'space-between'},totalLabel:{fontSize:7,fontWeight:'900'},totalValue:{fontSize:14,fontWeight:'900',marginTop:2},primary:{minHeight:48,borderRadius:13,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},primaryText:{color:'#07111F',fontSize:9,fontWeight:'900'},disabled:{opacity:.4},result:{borderRadius:15,borderWidth:1,padding:11,flexDirection:'row',gap:9},resultTitle:{color:'#D9FFEC',fontSize:11,fontWeight:'900'},resultText:{color:'#A7EBC8',fontSize:8,lineHeight:12,marginTop:3},overlay:{flex:1,backgroundColor:'rgba(0,0,0,.7)',justifyContent:'flex-end'},picker:{height:'85%',borderTopLeftRadius:24,borderTopRightRadius:24,borderWidth:1},pickerHead:{padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},pickerTitle:{fontSize:22,fontWeight:'900'},pickerQty:{height:44,borderRadius:11,borderWidth:1,marginHorizontal:12,paddingHorizontal:10,fontSize:11},search:{height:44,borderRadius:11,borderWidth:1,margin:12,flexDirection:'row',alignItems:'center',gap:7,paddingHorizontal:10},searchInput:{flex:1,height:'100%',fontSize:10},list:{paddingHorizontal:12,gap:6,paddingBottom:28},pickRow:{height:82,borderRadius:13,borderWidth:1,padding:7,flexDirection:'row',alignItems:'center',gap:9},pickImage:{width:46,height:66}});
