import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect } from 'expo-router';
import { Screen } from '@/components/Screen';
import { useAppTheme } from '@/theme/ThemeProvider';
import { getPokemonMastery, type AdventureHub } from '@/services/adventure';

export default function PokemonMasteryScreen(){
 const{colors}=useAppTheme();const[data,setData]=useState<AdventureHub['mastery']|null>(null);const[loading,setLoading]=useState(true);const[query,setQuery]=useState('');const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setError(null);setData(await getPokemonMastery())}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar a maestria.')}finally{setLoading(false)}},[]);useFocusEffect(useCallback(()=>{void load()},[load]));
 const items=useMemo(()=>{const q=query.trim().toLowerCase();return(data?.items??[]).filter(x=>!q||x.pokemonName.toLowerCase().includes(q))},[data?.items,query]);
 return <Screen title="Maestria Pokémon" subtitle="Use Pokémon em batalhas para subir domínio. A maestria não aumenta dano: ela registra experiência, títulos e prestígio.">
  <View style={[styles.hero,{backgroundColor:colors.surface,borderColor:colors.accent}]}><View style={[styles.icon,{backgroundColor:colors.accentSoft}]}><Ionicons name="ribbon" size={30} color={colors.yellow}/></View><View style={{flex:1}}><Text style={[styles.kicker,{color:colors.yellow}]}>DOMÍNIO DE BATALHA</Text><Text style={[styles.title,{color:colors.text}]}>{data?.total??0} Pokémon usados</Text><Text style={[styles.sub,{color:colors.muted}]}>Maior nível de maestria: {data?.maxLevel??0}/100</Text></View></View>
  <View style={[styles.search,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={17} color={colors.muted}/><TextInput value={query} onChangeText={setQuery} placeholder="Buscar Pokémon" placeholderTextColor={colors.muted} style={[styles.input,{color:colors.text}]}/></View>
  {error?<Pressable onPress={()=>setError(null)} style={[styles.error,{borderColor:colors.red}]}><Text style={{color:colors.red,flex:1}}>{error}</Text><Ionicons name="close" size={16} color={colors.red}/></Pressable>:null}
  {loading?<ActivityIndicator color={colors.accent}/>:items.map((item,index)=>{const next=Math.pow(Math.max(1,item.level)*5,2);const prev=Math.pow(Math.max(0,item.level-1)*5,2);const pct=item.level>=100?100:Math.max(2,Math.min(100,(item.xp-prev)/Math.max(1,next-prev)*100));return <View key={item.pokemonKey} style={[styles.row,{backgroundColor:colors.surface,borderColor:index===0?colors.yellow:colors.border}]}><View style={[styles.rank,{backgroundColor:index===0?'#342D14':colors.surfaceAlt}]}><Text style={[styles.rankText,{color:index===0?colors.yellow:colors.muted}]}>#{index+1}</Text></View><View style={{flex:1}}><View style={styles.rowHead}><Text style={[styles.name,{color:colors.text}]}>{item.pokemonName}</Text><Text style={[styles.level,{color:colors.accent}]}>NV {item.level}</Text></View><Text style={[styles.meta,{color:colors.muted}]}>{item.battles} batalhas • {item.wins} vitórias • {item.xp.toLocaleString('pt-BR')} XP</Text><View style={[styles.track,{backgroundColor:colors.border}]}><View style={[styles.fill,{backgroundColor:item.level>=50?colors.yellow:colors.accent,width:`${pct}%`}]}/></View></View>{item.level>=25?<View style={[styles.badge,{borderColor:item.level>=50?colors.yellow:colors.accent}]}><Ionicons name={item.level>=50?'trophy':'ribbon'} size={13} color={item.level>=50?colors.yellow:colors.accent}/><Text style={[styles.badgeText,{color:item.level>=50?colors.yellow:colors.accent}]}>{item.level>=75?'MESTRE':item.level>=50?'ESPECIALISTA':'DOMINADO'}</Text></View>:null}</View>})}
  {!loading&&!items.length?<View style={[styles.empty,{borderColor:colors.border}]}><Ionicons name="paw-outline" size={30} color={colors.muted}/><Text style={{color:colors.muted,textAlign:'center'}}>Use Pokémon em batalhas para começar a construir sua maestria.</Text></View>:null}
 </Screen>
}
const styles=StyleSheet.create({hero:{borderWidth:1,borderRadius:17,padding:14,flexDirection:'row',gap:12,alignItems:'center'},icon:{width:55,height:55,borderRadius:17,alignItems:'center',justifyContent:'center'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1},title:{fontSize:18,fontWeight:'900',marginTop:2},sub:{fontSize:10,marginTop:3},search:{borderWidth:1,borderRadius:12,paddingHorizontal:11,flexDirection:'row',alignItems:'center',gap:7},input:{flex:1,minHeight:42},error:{borderWidth:1,borderRadius:10,padding:9,flexDirection:'row'},row:{borderWidth:1,borderRadius:14,padding:11,flexDirection:'row',alignItems:'center',gap:9},rank:{width:36,height:36,borderRadius:12,alignItems:'center',justifyContent:'center'},rankText:{fontSize:10,fontWeight:'900'},rowHead:{flexDirection:'row',justifyContent:'space-between',gap:8},name:{fontSize:13,fontWeight:'900',flex:1},level:{fontSize:10,fontWeight:'900'},meta:{fontSize:9,marginTop:2},track:{height:5,borderRadius:99,overflow:'hidden',marginTop:7},fill:{height:'100%'},badge:{borderWidth:1,borderRadius:99,paddingHorizontal:7,paddingVertical:4,flexDirection:'row',alignItems:'center',gap:3},badgeText:{fontSize:7,fontWeight:'900'},empty:{borderWidth:1,borderRadius:14,padding:25,alignItems:'center',gap:8}});
