import { useCallback, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { goBackOrHome } from '@/navigation/goBackOrHome';
import { Screen } from '@/components/Screen';
import { getMyBagPage } from '@/services/bag';
import { getMyShowcase, setShowcaseCard } from '@/services/retention';
import type { OwnedCardEntry } from '@/services/player';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function ShowcaseScreen(){
 const router=useRouter();const {colors}=useAppTheme();const [slots,setSlots]=useState<any[]>([]);const [pickerSlot,setPickerSlot]=useState<number|null>(null);const [cards,setCards]=useState<OwnedCardEntry[]>([]);const [loading,setLoading]=useState(true);const [pickerLoading,setPickerLoading]=useState(false);
 const load=useCallback(async()=>{try{setSlots(await getMyShowcase());}finally{setLoading(false);}},[]);
 useFocusEffect(useCallback(()=>{setLoading(true);void load();},[load]));
 async function open(slot:number){setPickerSlot(slot);try{setPickerLoading(true);const page=await getMyBagPage(0,60,{search:'',setQuery:'',quickFilter:'all',typeFilter:null,rarityFilter:null,generation:null,sortMode:'value'});setCards(page.items);}finally{setPickerLoading(false);}}
 async function choose(cardId:string){if(pickerSlot==null)return;await setShowcaseCard(pickerSlot,cardId);setPickerSlot(null);await load();}
 async function clear(slot:number){await setShowcaseCard(slot,null);await load();}
 const bySlot=new Map(slots.map((r:any)=>[Number(r.slot),r]));
 return <Screen title="Vitrine do Perfil" subtitle="Escolha até 6 cartas para representar sua coleção no perfil público."><Pressable style={styles.back} onPress={()=>goBackOrHome(router)}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable>{loading?<ActivityIndicator color={colors.yellow}/>:null}<View style={styles.grid}>{[1,2,3,4,5,6].map((slot)=>{const row:any=bySlot.get(slot);const rel=Array.isArray(row?.cards)?row.cards[0]:row?.cards;return <View key={slot} style={[styles.slot,{backgroundColor:colors.surface,borderColor:rel?colors.yellow:colors.border}]}><Text style={[styles.slotLabel,{color:colors.muted}]}>SLOT {slot}</Text>{rel?.image_small?<Image source={{uri:rel.image_small}} resizeMode="contain" style={styles.image}/>:<View style={[styles.placeholder,{backgroundColor:colors.surfaceAlt}]}><Ionicons name="albums-outline" size={34} color={colors.muted}/></View>}<Text numberOfLines={1} style={[styles.name,{color:colors.text}]}>{rel?.pokemon_name??'Vazio'}</Text><View style={styles.actions}><Pressable onPress={()=>void open(slot)} style={[styles.action,{borderColor:colors.accent}]}><Text style={[styles.actionText,{color:colors.accent}]}>{rel?'TROCAR':'ESCOLHER'}</Text></Pressable>{rel?<Pressable onPress={()=>void clear(slot)} style={[styles.action,{borderColor:'#683243'}]}><Ionicons name="trash" size={15} color="#FF8290"/></Pressable>:null}</View></View>;})}</View><Modal visible={pickerSlot!=null} animationType="slide" onRequestClose={()=>setPickerSlot(null)}><View style={[styles.modal,{backgroundColor:colors.bg}]}><View style={styles.modalHead}><Text style={[styles.modalTitle,{color:colors.text}]}>Escolher carta</Text><Pressable onPress={()=>setPickerSlot(null)}><Ionicons name="close" size={25} color={colors.text}/></Pressable></View>{pickerLoading?<ActivityIndicator color={colors.yellow}/>:null}<FlatList data={cards} keyExtractor={(item,index)=>item.cards?.id??String(index)} contentContainerStyle={styles.list} renderItem={({item})=><Pressable disabled={!item.cards} onPress={()=>item.cards&&void choose(item.cards.id)} style={[styles.row,{backgroundColor:colors.surface,borderColor:colors.border}]}>{item.cards?.image_small?<Image source={{uri:item.cards.image_small}} resizeMode="contain" style={styles.rowImage}/>:<View style={styles.rowImage}/>}<View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{item.cards?.pokemon_name??'Carta'}</Text><Text style={[styles.meta,{color:colors.muted}]}>{item.cards?.rarity??'Sem raridade'}</Text></View><Ionicons name="add-circle" size={22} color={colors.accent}/></Pressable>}/></View></Modal></Screen>;
}
const styles=StyleSheet.create({back:{alignSelf:'flex-start',flexDirection:'row',gap:7,alignItems:'center'},backText:{fontSize:11,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},slot:{width:'48%',minHeight:260,borderRadius:18,borderWidth:1,padding:9},slotLabel:{fontSize:8,fontWeight:'900'},image:{width:'100%',height:180,marginTop:5},placeholder:{height:180,borderRadius:12,alignItems:'center',justifyContent:'center',marginTop:5},name:{fontSize:11,fontWeight:'900',marginTop:5},actions:{flexDirection:'row',gap:6,marginTop:7},action:{minHeight:36,borderRadius:10,borderWidth:1,paddingHorizontal:9,alignItems:'center',justifyContent:'center'},actionText:{fontSize:8,fontWeight:'900'},modal:{flex:1,paddingTop:45},modalHead:{padding:14,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},modalTitle:{fontSize:25,fontWeight:'900'},list:{padding:12,gap:7},row:{minHeight:76,borderRadius:14,borderWidth:1,padding:8,flexDirection:'row',alignItems:'center',gap:9},rowImage:{width:48,height:62},meta:{fontSize:8,marginTop:2}});
