import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Image, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PremiumBackground } from '@/components/PremiumBackground';
import { TrainerNavigation } from '@/components/TrainerNavigation';
import { formatUsd } from '@/services/market';
import { getWishlist, searchWishlistCards, setCardWishlist, type WishlistCard } from '@/services/retention';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function WishlistScreen(){
  const router=useRouter();const {colors}=useAppTheme();
  const [wishlist,setWishlist]=useState<WishlistCard[]>([]);const [search,setSearch]=useState('');const [results,setResults]=useState<any[]>([]);
  const [loading,setLoading]=useState(true);const [searching,setSearching]=useState(false);const [working,setWorking]=useState<string|null>(null);const [notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setWishlist(await getWishlist());}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{setLoading(true);void load();},[load]));
  useEffect(()=>{const q=search.trim();if(q.length<2){setResults([]);return;}const t=setTimeout(async()=>{try{setSearching(true);setResults(await searchWishlistCards(q));}finally{setSearching(false);}},280);return()=>clearTimeout(t);},[search]);
  async function toggle(cardId:string,wanted:boolean){if(working)return;try{setWorking(cardId);await setCardWishlist(cardId,wanted);setNotice(wanted?'Carta adicionada ao Card Chase.':'Carta removida da wishlist.');await load();}catch(e){setNotice(e instanceof Error?e.message:'Não foi possível atualizar.');}finally{setWorking(null);}}
  const wantedIds=new Set(wishlist.map((w)=>w.cardId));
  const header=<View style={styles.header}><TrainerNavigation/><Pressable style={styles.back} onPress={()=>router.back()}><Ionicons name="arrow-back" size={18} color={colors.muted}/><Text style={[styles.backText,{color:colors.muted}]}>Voltar</Text></Pressable><View><Text style={[styles.kicker,{color:colors.yellow}]}>CARD CHASE</Text><Text style={[styles.title,{color:colors.text}]}>Wishlist</Text><Text style={[styles.sub,{color:colors.muted}]}>Escolha as cartas que você mais quer. Quando aparecerem no mercado, você recebe um alerta.</Text></View>{notice?<Pressable onPress={()=>setNotice(null)} style={[styles.notice,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Text style={[styles.noticeText,{color:colors.text}]}>{notice}</Text></Pressable>:null}<View style={[styles.searchBox,{backgroundColor:colors.surface,borderColor:colors.border}]}><Ionicons name="search" size={19} color={colors.muted}/><TextInput value={search} onChangeText={setSearch} placeholder="Buscar qualquer Pokémon..." placeholderTextColor={colors.muted} style={[styles.searchInput,{color:colors.text}]}/>{searching?<ActivityIndicator size="small" color={colors.yellow}/>:null}</View>{results.length?<View style={styles.results}>{results.slice(0,12).map((card)=>{const wanted=wantedIds.has(card.id);return <Pressable key={card.id} onPress={()=>void toggle(card.id,!wanted)} style={[styles.result,{backgroundColor:colors.surface,borderColor:wanted?colors.yellow:colors.border}]}>{card.image_small?<Image source={{uri:card.image_small}} resizeMode="contain" style={styles.thumb}/>:<View style={styles.thumb}/>}<View style={{flex:1}}><Text style={[styles.cardName,{color:colors.text}]}>{card.pokemon_name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{card.set_name} • {card.rarity??'Sem raridade'}</Text></View><Ionicons name={wanted?'star':'star-outline'} size={21} color={wanted?colors.yellow:colors.muted}/></Pressable>;})}</View>:null}<View style={styles.sectionRow}><Text style={[styles.sectionTitle,{color:colors.text}]}>Minhas caçadas</Text><Text style={[styles.count,{color:colors.yellow}]}>{wishlist.length}</Text></View></View>;
  return <SafeAreaView style={[styles.safe,{backgroundColor:colors.bg}]}><PremiumBackground/><FlatList data={wishlist} keyExtractor={(item)=>item.cardId} ListHeaderComponent={header} contentContainerStyle={styles.content} initialNumToRender={8} maxToRenderPerBatch={8} windowSize={7} ListEmptyComponent={!loading?<View style={[styles.empty,{borderColor:colors.border,backgroundColor:colors.surface}]}><Ionicons name="star-outline" size={35} color={colors.muted}/><Text style={[styles.emptyTitle,{color:colors.text}]}>Sua wishlist está vazia</Text><Text style={[styles.sub,{color:colors.muted}]}>Busque uma carta acima e marque a primeira caçada.</Text></View>:<ActivityIndicator color={colors.yellow}/>} renderItem={({item})=><View style={[styles.cardRow,{backgroundColor:colors.surface,borderColor:colors.border}]}><Pressable style={styles.cardBody} onPress={()=>router.push(`/card/${item.cardId}`)}>{item.card.image?<Image source={{uri:item.card.image}} resizeMode="contain" style={styles.image}/>:<View style={styles.image}/>}<View style={{flex:1}}><Text style={[styles.cardName,{color:colors.text}]}>{item.card.name}</Text><Text style={[styles.meta,{color:colors.muted}]}>{item.card.setName} • {item.card.rarity??'Sem raridade'}</Text><Text style={[styles.price,{color:colors.yellow}]}>{item.card.marketPriceUsd==null?'Preço indisponível':formatUsd(item.card.marketPriceUsd)}</Text></View></Pressable><Pressable disabled={working===item.cardId} onPress={()=>void toggle(item.cardId,false)} style={styles.remove}><Ionicons name="trash" size={18} color="#FF8290"/></Pressable></View>}/></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,overflow:'hidden'},content:{width:'100%',maxWidth:900,alignSelf:'center',padding:14,paddingBottom:80,gap:8},header:{gap:12,marginBottom:4},back:{alignSelf:'flex-start',flexDirection:'row',gap:7,alignItems:'center'},backText:{fontSize:11,fontWeight:'800'},kicker:{fontSize:9,fontWeight:'900',letterSpacing:1.5},title:{fontSize:30,fontWeight:'900'},sub:{fontSize:10,lineHeight:15},notice:{borderRadius:13,borderWidth:1,padding:10},noticeText:{fontSize:10,fontWeight:'800'},searchBox:{height:50,borderRadius:15,borderWidth:1,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:8},searchInput:{flex:1,fontSize:13},results:{gap:6},result:{minHeight:58,borderRadius:14,borderWidth:1,padding:7,flexDirection:'row',alignItems:'center',gap:8},thumb:{width:42,height:52},cardName:{fontSize:12,fontWeight:'900'},meta:{fontSize:8,marginTop:2},sectionRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},sectionTitle:{fontSize:18,fontWeight:'900'},count:{fontSize:13,fontWeight:'900'},cardRow:{minHeight:92,borderRadius:17,borderWidth:1,padding:8,flexDirection:'row',alignItems:'center',gap:7},cardBody:{flex:1,flexDirection:'row',alignItems:'center',gap:10},image:{width:58,height:74},price:{fontSize:11,fontWeight:'900',marginTop:5},remove:{width:42,height:42,alignItems:'center',justifyContent:'center'},empty:{borderRadius:18,borderWidth:1,padding:28,alignItems:'center',gap:7},emptyTitle:{fontSize:15,fontWeight:'900'}});
