import { useCallback, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getMyBag, getMyProfile } from '@/services/player';
import { claimDailyReward } from '@/services/playerActions';
import { getMyTrades } from '@/services/trades';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function HomeScreen() {
  const router = useRouter();
  const { colors, isLight } = useAppTheme();
  const [profile,setProfile]=useState<any>(null);const[bag,setBag]=useState<any[]>([]);const[trades,setTrades]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[claiming,setClaiming]=useState(false);const[notice,setNotice]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setLoading(true);const[p,b,t]=await Promise.all([getMyProfile(),getMyBag(),getMyTrades()]);setProfile(p);setBag(b??[]);setTrades(t??[]);}finally{setLoading(false);}},[]);
  useFocusEffect(useCallback(()=>{load();},[load]));
  const stats=useMemo(()=>{const totalCards=bag.reduce((sum,item)=>sum+Number(item.quantity??0),0);const species=new Set(bag.map((item)=>item.cards?.pokedex_numbers?.[0]).filter((v)=>typeof v==='number')).size;const completedTrades=trades.filter((trade)=>trade.status==='completed').length;return{totalCards,species,completedTrades};},[bag,trades]);
  const canClaimDaily=useMemo(()=>!profile?.last_daily_claim_at||Date.now()-new Date(profile.last_daily_claim_at).getTime()>=24*60*60*1000,[profile?.last_daily_claim_at]);
  async function claimDaily(){if(!canClaimDaily||claiming)return;try{setClaiming(true);const reward=await claimDailyReward();setNotice(`Recompensa recebida: +${reward.rewardCoins} moedas e +${reward.rewardXp} XP.`);await load();}catch(err){setNotice(err instanceof Error?err.message:'Não foi possível receber a recompensa.');}finally{setClaiming(false);}}
  return <Screen title={`Olá, ${profile?.username??'Trainer'}`} subtitle="Sua coleção, seus boosters e suas trocas em um só lugar.">
    {loading?<ActivityIndicator color={colors.yellow} size="large"/>:null}
    {notice?<View style={[styles.notice,{backgroundColor:isLight?'#FFF7D6':'#2B2818',borderColor:isLight?'#E5C95E':'#5A5125'}]}><Ionicons name="gift" size={20} color={colors.yellow}/><Text style={[styles.noticeText,{color:colors.text}]}>{notice}</Text><Pressable onPress={()=>setNotice(null)}><Ionicons name="close" size={18} color={colors.text}/></Pressable></View>:null}
    <View style={[styles.hero,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}>
      <View style={styles.heroTop}><View style={[styles.coinBadge,{backgroundColor:colors.surface}]}><Ionicons name="sparkles" color={colors.yellow} size={16}/><Text style={[styles.coinText,{color:colors.yellow}]}>{Number(profile?.coins??0).toLocaleString('pt-BR')}</Text></View><Text style={[styles.level,{color:colors.accent}]}>LV. {profile?.level??1}</Text></View>
      <Text style={[styles.heroEyebrow,{color:colors.accent}]}>PRÓXIMO PULL PODE SER O RARO</Text><Text style={[styles.heroTitle,{color:colors.text}]}>Abra um booster e aumente sua coleção.</Text><Text style={[styles.heroText,{color:colors.muted}]}>Todos os resultados são sorteados e registrados pelo servidor.</Text>
      <View style={styles.heroActions}><Pressable style={[styles.primaryButton,{backgroundColor:colors.yellow}]} onPress={()=>router.push('/(tabs)/packs')}><Ionicons name="cube" color="#07111F" size={19}/><Text style={styles.primaryButtonText}>IR PARA OS PACKS</Text></Pressable><Pressable style={[styles.dailyButton,{backgroundColor:canClaimDaily?colors.accent:colors.surfaceAlt}]} onPress={claimDaily} disabled={!canClaimDaily||claiming}><Ionicons name="gift-outline" color={canClaimDaily?'#fff':colors.muted} size={18}/><Text style={[styles.dailyText,{color:canClaimDaily?'#fff':colors.muted}]}>{claiming?'RECEBENDO...':canClaimDaily?'RECOMPENSA DIÁRIA':'VOLTE AMANHÃ'}</Text></Pressable><Pressable style={[styles.dailyButton,{backgroundColor:colors.surface}]} onPress={()=>router.push('/missions')}><Ionicons name="checkbox-outline" color={colors.accent} size={18}/><Text style={[styles.dailyText,{color:colors.text}]}>MISSÕES</Text></Pressable></View>
    </View>
    <View style={styles.statsGrid}><Stat icon="albums" label="Cards" value={stats.totalCards.toLocaleString('pt-BR')} onPress={()=>router.push('/(tabs)/bag')}/><Stat icon="paw" label="Pokédex" value={String(stats.species)} onPress={()=>router.push('/pokedex')}/><Stat icon="swap-horizontal" label="Trocas" value={String(stats.completedTrades)} onPress={()=>router.push('/(tabs)/trade')}/><Stat icon="flash" label="XP" value={Number(profile?.xp??0).toLocaleString('pt-BR')}/></View>
    <View style={styles.sectionHeader}><View><Text style={[styles.sectionKicker,{color:colors.yellow}]}>JORNADA</Text><Text style={[styles.sectionTitle,{color:colors.text}]}>Seu progresso</Text></View></View>
    <View style={[styles.progressCard,{backgroundColor:colors.surface,borderColor:colors.border}]}><View style={[styles.progressIcon,{backgroundColor:colors.accentSoft}]}><Ionicons name="trophy" size={24} color={colors.yellow}/></View><View style={styles.progressBody}><Text style={[styles.progressTitle,{color:colors.text}]}>Colecionador nível {profile?.level??1}</Text><Text style={[styles.progressText,{color:colors.muted}]}>Packs, missões e batalhas concedem XP para sua conta.</Text><View style={[styles.progressTrack,{backgroundColor:colors.surfaceAlt}]}><View style={[styles.progressFill,{backgroundColor:colors.yellow,width:`${Math.min(100,(Number(profile?.xp??0)%250)/2.5)}%`}]}/></View><Text style={[styles.progressMeta,{color:colors.muted}]}>{Number(profile?.xp??0)%250} / 250 XP para o próximo nível</Text></View></View>
  </Screen>
}
function Stat({icon,label,value,onPress}:{icon:keyof typeof Ionicons.glyphMap;label:string;value:string;onPress?:()=>void}){const{colors}=useAppTheme();const content=<><View style={[styles.statIcon,{backgroundColor:colors.accentSoft}]}><Ionicons name={icon} size={19} color={colors.accent}/></View><Text style={[styles.statValue,{color:colors.text}]}>{value}</Text><View style={styles.statBottom}><Text style={[styles.statLabel,{color:colors.muted}]}>{label}</Text>{onPress?<Ionicons name="chevron-forward" size={14} color={colors.muted}/>:null}</View></>;const style=[styles.statCard,{backgroundColor:colors.surface,borderColor:colors.border}] as any;return onPress?<Pressable onPress={onPress} style={style}>{content}</Pressable>:<View style={style}>{content}</View>}
const styles=StyleSheet.create({notice:{flexDirection:'row',alignItems:'center',gap:9,borderRadius:15,padding:12,borderWidth:1},noticeText:{flex:1,fontWeight:'700',fontSize:12},hero:{borderRadius:26,padding:20,borderWidth:1,gap:10,overflow:'hidden'},heroTop:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},coinBadge:{flexDirection:'row',alignItems:'center',gap:6,paddingHorizontal:11,paddingVertical:8,borderRadius:999},coinText:{fontWeight:'900',fontSize:14},level:{fontWeight:'900',fontSize:12},heroEyebrow:{fontSize:10,fontWeight:'900',letterSpacing:1.4,marginTop:6},heroTitle:{fontSize:25,lineHeight:30,fontWeight:'900',maxWidth:410},heroText:{lineHeight:20,fontSize:14},heroActions:{marginTop:6,flexDirection:'row',flexWrap:'wrap',gap:9},primaryButton:{flexDirection:'row',gap:8,alignItems:'center',paddingHorizontal:16,paddingVertical:12,borderRadius:14},primaryButtonText:{color:'#07111F',fontWeight:'900',fontSize:12,letterSpacing:.4},dailyButton:{flexDirection:'row',gap:8,alignItems:'center',paddingHorizontal:16,paddingVertical:12,borderRadius:14},dailyText:{fontWeight:'900',fontSize:11},statsGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},statCard:{width:'48.5%',borderRadius:20,padding:15,borderWidth:1},statIcon:{width:34,height:34,borderRadius:12,alignItems:'center',justifyContent:'center',marginBottom:13},statValue:{fontSize:23,fontWeight:'900'},statBottom:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},statLabel:{fontSize:12,fontWeight:'700',marginTop:2},sectionHeader:{flexDirection:'row',alignItems:'flex-end',justifyContent:'space-between',marginTop:4},sectionKicker:{fontSize:10,fontWeight:'900',letterSpacing:1.3},sectionTitle:{fontSize:21,fontWeight:'900',marginTop:2},progressCard:{flexDirection:'row',gap:14,padding:16,borderRadius:20,borderWidth:1},progressIcon:{width:48,height:48,borderRadius:16,alignItems:'center',justifyContent:'center'},progressBody:{flex:1},progressTitle:{fontSize:16,fontWeight:'900'},progressText:{fontSize:12,lineHeight:18,marginTop:4},progressTrack:{height:7,borderRadius:999,marginTop:12,overflow:'hidden'},progressFill:{height:'100%',borderRadius:999},progressMeta:{fontSize:9,fontWeight:'800',marginTop:5}});
