import { useCallback, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useLocalSearchParams, useRouter } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getBattlePostgameInsights, type PostgameInsights } from '@/services/playerExperienceV2';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function BattleSummaryScreen(){
 const{id}=useLocalSearchParams<{id:string}>();const router=useRouter();const{colors}=useAppTheme();const[data,setData]=useState<PostgameInsights|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!id)return;try{setLoading(true);setError(null);setData(await getBattlePostgameInsights(String(id)));}catch(e){setError(e instanceof Error?e.message:'Não foi possível explicar essa batalha.');}finally{setLoading(false);}},[id]);
 useFocusEffect(useCallback(()=>{void load();},[load]));
 return <Screen title="Resumo da Batalha" subtitle="Entenda o resultado sem alterar a lógica que decidiu a partida.">
  {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}
  {error?<View style={[styles.error,{borderColor:'#6B303A'}]}><Ionicons name="alert-circle" size={18} color="#FF8792"/><Text style={[styles.errorText,{color:colors.text}]}>{error}</Text></View>:null}
  {data?<><View style={[styles.hero,{backgroundColor:colors.surface,borderColor:data.won?'#65D894':'#FF8792'}]}><Ionicons name={data.won?'trophy':'analytics'} size={36} color={data.won?'#65D894':'#FF8792'}/><View style={{flex:1}}><Text style={[styles.kicker,{color:data.won?'#65D894':'#FF8792'}]}>{data.won?'VITÓRIA':'DERROTA'}</Text><Text style={[styles.score,{color:colors.text}]}>{data.myScore} × {data.enemyScore}</Text><Text style={[styles.meta,{color:colors.muted}]}>{data.mode.toUpperCase()} • {data.wonRounds} rodada(s) vencida(s) • {data.lostRounds} perdida(s)</Text></View><View style={[styles.elo,{backgroundColor:colors.surfaceAlt}]}><Text style={[styles.eloValue,{color:data.ratingDelta>=0?'#65D894':'#FF8792'}]}>{data.ratingDelta>0?'+':''}{data.ratingDelta}</Text><Text style={[styles.eloLabel,{color:colors.muted}]}>ELO</Text></View></View>
  <View style={[styles.reason,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Ionicons name="bulb" size={21} color={colors.accent}/><View style={{flex:1}}><Text style={[styles.reasonTitle,{color:colors.text}]}>Por que esse resultado aconteceu?</Text><Text style={[styles.reasonText,{color:colors.muted}]}>{data.reason}</Text></View></View>
  <Text style={[styles.section,{color:colors.text}]}>Rodada por rodada</Text>
  <View style={styles.list}>{data.rounds.map(r=><View key={r.round} style={[styles.round,{backgroundColor:colors.surface,borderColor:r.won?'#65D894':'#FF879255'}]}><View style={[styles.badge,{backgroundColor:r.won?'#163323':'#321A20'}]}><Text style={{color:r.won?'#65D894':'#FF8792',fontSize:8,fontWeight:'900'}}>R{r.round}</Text></View><View style={{flex:1}}><Text style={[styles.roundTitle,{color:colors.text}]}>{r.myCardName??'Seu Pokémon'} × {r.enemyCardName??'Adversário'}</Text><Text style={[styles.meta,{color:colors.muted}]}>Poder {r.myPower??'—'} × {r.enemyPower??'—'} • {r.won?'você venceu':'adversário venceu'}</Text></View>{r.myCardId?<Pressable onPress={()=>router.push(('/card/'+r.myCardId) as never)}><Ionicons name="open-outline" size={18} color={colors.accent}/></Pressable>:null}</View>)}</View>
  <View style={styles.actions}><Pressable onPress={()=>router.push(data.replayRoute as never)} style={[styles.primary,{backgroundColor:colors.yellow}]}><Ionicons name="play-back" size={17} color="#07111F"/><Text style={styles.primaryText}>VER REPLAY</Text></Pressable><Pressable onPress={()=>router.push('/card-compare')} style={[styles.secondary,{borderColor:colors.border}]}><Ionicons name="git-compare" size={17} color={colors.accent}/><Text style={[styles.secondaryText,{color:colors.text}]}>COMPARAR CARTAS</Text></Pressable></View></>:null}
 </Screen>;
}
const styles=StyleSheet.create({error:{borderRadius:14,borderWidth:1,padding:10,flexDirection:'row',alignItems:'center',gap:7},errorText:{flex:1,fontSize:9},hero:{borderRadius:18,borderWidth:1,padding:13,flexDirection:'row',alignItems:'center',gap:10},kicker:{fontSize:8,fontWeight:'900',letterSpacing:1},score:{fontSize:24,fontWeight:'900'},meta:{fontSize:8,lineHeight:12,marginTop:2},elo:{borderRadius:12,padding:9,alignItems:'center',minWidth:58},eloValue:{fontSize:18,fontWeight:'900'},eloLabel:{fontSize:6,fontWeight:'900'},reason:{borderRadius:16,borderWidth:1,padding:11,flexDirection:'row',gap:8,alignItems:'flex-start'},reasonTitle:{fontSize:11,fontWeight:'900'},reasonText:{fontSize:8,lineHeight:13,marginTop:3},section:{fontSize:17,fontWeight:'900'},list:{gap:7},round:{borderRadius:15,borderWidth:1,padding:9,flexDirection:'row',alignItems:'center',gap:8},badge:{width:34,height:34,borderRadius:10,alignItems:'center',justifyContent:'center'},roundTitle:{fontSize:10,fontWeight:'900'},actions:{flexDirection:'row',gap:8,flexWrap:'wrap'},primary:{minHeight:44,flex:1,minWidth:150,borderRadius:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},primaryText:{color:'#07111F',fontSize:8,fontWeight:'900'},secondary:{minHeight:44,flex:1,minWidth:150,borderRadius:12,borderWidth:1,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:6},secondaryText:{fontSize:8,fontWeight:'900'}});