-- Pokémon visual themes, fixed rank snapshot, high-value pack economy and Diamond exchange.
alter table public.packs add column if not exists currency text not null default 'coins';
alter table public.packs drop constraint if exists packs_currency_check;
alter table public.packs add constraint packs_currency_check check(currency in ('coins','diamonds'));

create table if not exists public.diamond_exchange_log(
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  diamonds integer not null check(diamonds>0),
  coins_spent bigint not null check(coins_spent>0),
  created_at timestamptz not null default now()
);
alter table public.diamond_exchange_log enable row level security;
grant select on public.diamond_exchange_log to authenticated;
drop policy if exists "own diamond exchanges readable" on public.diamond_exchange_log;
create policy "own diamond exchanges readable" on public.diamond_exchange_log
for select to authenticated using ((select auth.uid())=player_id);
create index if not exists diamond_exchange_log_player_idx
on public.diamond_exchange_log(player_id,created_at desc);

alter table public.player_settings drop constraint if exists player_settings_theme_check;
alter table public.player_settings add constraint player_settings_theme_check
check(theme in (
  'trainer','midnight','poke_red','electric','ghost','fire','water','grass','psychic',
  'dragon','fighting','steel','fairy','darkness','kanto','johto','hoenn','sinnoh'
));

CREATE OR REPLACE FUNCTION private.exchange_coins_for_diamonds(p_diamonds integer DEFAULT 1)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_rate bigint:=500000;
  v_cost bigint;
  v_coins bigint;
  v_diamonds integer;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  if p_diamonds<1 or p_diamonds>20 then raise exception 'INVALID_DIAMOND_AMOUNT'; end if;
  v_cost:=v_rate*p_diamonds;
  select coins,diamonds into v_coins,v_diamonds
  from public.players
  where id=v_player and account_status='active'
  for update;
  if not found then raise exception 'PLAYER_NOT_AVAILABLE'; end if;
  if v_coins<v_cost then raise exception 'NOT_ENOUGH_COINS'; end if;
  update public.players
  set coins=coins-v_cost,diamonds=diamonds+p_diamonds
  where id=v_player
  returning coins,diamonds into v_coins,v_diamonds;
  insert into public.diamond_exchange_log(player_id,diamonds,coins_spent)
  values(v_player,p_diamonds,v_cost);
  return jsonb_build_object('diamondsBought',p_diamonds,'coinsSpent',v_cost,'rate',v_rate,'coins',v_coins,'diamonds',v_diamonds);
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_my_rank_snapshot()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_battle_rank bigint; v_battle_total bigint; v_collection_rank bigint; v_collection_total bigint;
  v_collection_value numeric:=0; v_rating integer:=1000;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  with ranked as (
    select p.id,p.battle_rating,row_number() over(order by p.battle_rating desc,p.battle_wins desc,p.username) rn,count(*) over() total
    from public.players p where p.account_status<>'banned'
  )
  select rn,total,battle_rating into v_battle_rank,v_battle_total,v_rating from ranked where id=v_player;
  with values_by_player as (
    select p.id,coalesce(sum(case when pc.quantity>0 then coalesce(c.market_price_usd,0) else 0 end),0)::numeric value_usd
    from public.players p
    left join public.player_cards pc on pc.player_id=p.id and pc.quantity>0
    left join public.cards c on c.id=pc.card_id
    where p.account_status<>'banned'
    group by p.id
  ), ranked as (
    select id,value_usd,row_number() over(order by value_usd desc,id) rn,count(*) over() total from values_by_player
  )
  select rn,total,value_usd into v_collection_rank,v_collection_total,v_collection_value from ranked where id=v_player;
  return jsonb_build_object(
    'battle',jsonb_build_object('rank',coalesce(v_battle_rank,0),'total',coalesce(v_battle_total,0),'rating',coalesce(v_rating,1000)),
    'collection',jsonb_build_object('rank',coalesce(v_collection_rank,0),'total',coalesce(v_collection_total,0),'valueUsd',coalesce(v_collection_value,0))
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.refresh_pack_economy()
 RETURNS integer
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare v_rows integer;
begin
  with priced as (
    select id,
      case when release_date is not null and release_date <= current_date - interval '5 years' then 'diamonds' else 'coins' end currency,
      case
        when release_date is null then 40000::bigint
        when extract(year from age(current_date,release_date)) >= 25 then 140::bigint
        when extract(year from age(current_date,release_date)) >= 20 then 100::bigint
        when extract(year from age(current_date,release_date)) >= 15 then 70::bigint
        when extract(year from age(current_date,release_date)) >= 10 then 45::bigint
        when extract(year from age(current_date,release_date)) >= 7 then 30::bigint
        when extract(year from age(current_date,release_date)) >= 5 then 20::bigint
        when extract(year from age(current_date,release_date)) >= 4 then 300000::bigint
        when extract(year from age(current_date,release_date)) >= 3 then 200000::bigint
        when extract(year from age(current_date,release_date)) >= 2 then 120000::bigint
        when extract(year from age(current_date,release_date)) >= 1 then 70000::bigint
        else 40000::bigint
      end price
    from public.packs
    where active
  )
  update public.packs p
  set currency=x.currency,price=x.price
  from priced x
  where p.id=x.id and (p.currency is distinct from x.currency or p.price is distinct from x.price);
  get diagnostics v_rows=row_count;
  return v_rows;
end;
$function$;


CREATE OR REPLACE FUNCTION public.exchange_coins_for_diamonds(p_diamonds integer DEFAULT 1)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.exchange_coins_for_diamonds(p_diamonds); $function$;


CREATE OR REPLACE FUNCTION public.get_my_rank_snapshot()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$ select private.get_my_rank_snapshot(); $function$;


CREATE OR REPLACE FUNCTION public.server_background_tick()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_battles integer;
  v_push integer;
  v_catalog jsonb;
  v_market_pending integer;
  v_restored_suspensions integer;
  v_season text;
begin
  update public.players
  set account_status='active',suspended_until=null,moderation_reason=null
  where account_status='suspended'
    and suspended_until is not null and suspended_until<=now();
  get diagnostics v_restored_suspensions=row_count;

  v_season:=private.ensure_active_season();
  perform private.refresh_pack_economy();

  perform private.ensure_weekly_guild_wars();
  perform private.ensure_active_tournament();

  update public.market_offers
  set status='expired',updated_at=now()
  where status='pending' and expires_at<=now();

  v_battles:=public.server_process_expired_battles();
  v_push:=public.server_dispatch_push_notifications();

  if exists(select 1 from public.catalog_refresh_state where job_name='full_tcg_refresh' and status='running') then
    begin
      v_catalog:=public.server_refresh_catalog_batch(2);
    exception when others then
      v_catalog:=jsonb_build_object('error',sqlerrm);
    end;
  else
    v_catalog:=jsonb_build_object('status','idle');
  end if;

  select count(*)::integer into v_market_pending
  from private.market_price_sync_sets
  where status in ('pending','running','retry');

  return jsonb_build_object(
    'battles',v_battles,'pushes',v_push,'catalog',v_catalog,
    'season',v_season,
    'guildWars','checked',
    'tournaments','checked',
    'moderation',jsonb_build_object('restoredSuspensions',v_restored_suspensions),
    'marketPrices',jsonb_build_object(
      'status',case when v_market_pending>0 then 'syncing' else 'ready' end,
      'pendingSets',v_market_pending,'source','pokemontcg:tcgplayer_market_v3'
    ),
    'at',now()
  );
end;
$function$;


CREATE OR REPLACE FUNCTION public.server_open_pack(p_player_id uuid, p_pack_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_pack public.packs%rowtype;
  v_coins bigint;
  v_diamonds integer;
  v_currency text;
  v_status text;
  v_until timestamptz;
  v_cards jsonb;
  v_opening_id uuid;
  v_count integer;
  v_new_coins bigint;
  v_new_diamonds integer;
  v_new_xp bigint;
  v_new_level integer;
  v_effective_price bigint;
  v_free_until timestamptz;
  v_pity_misses integer := 0;
  v_highest_tier integer := 1;
  v_new_cards integer := 0;
  v_wishlist_hits integer := 0;
  v_rare_multiplier numeric := 1;
  v_xp_gain integer := 20;
begin
  select * into v_pack from public.packs
  where id = p_pack_id and active = true for share;
  if not found then raise exception 'PACK_NOT_FOUND'; end if;

  select max(ends_at)
  into v_free_until
  from public.admin_game_events
  where event_type = 'free_boosters'
    and active = true and starts_at <= now() and ends_at > now();

  v_effective_price := case when v_free_until is null then v_pack.price else 0 end;
  v_currency := coalesce(v_pack.currency,'coins');

  select greatest(1,coalesce(max(
    case
      when event_type='rare_boost'
        then greatest(1,least(3,coalesce(nullif(payload->>'multiplier','')::numeric,1.5)))
      when event_type='featured_set' and payload->>'setId'=v_pack.set_id
        then greatest(1,least(3,coalesce(nullif(payload->>'multiplier','')::numeric,1.5)))
      else 1
    end
  ),1))
  into v_rare_multiplier
  from public.admin_game_events
  where active and starts_at<=now() and ends_at>now()
    and event_type in ('rare_boost','featured_set');

  select case when exists(
    select 1 from public.admin_game_events
    where event_type='double_xp' and active and starts_at<=now() and ends_at>now()
  ) then 40 else 20 end
  into v_xp_gain;

  select coins, diamonds, account_status, suspended_until
  into v_coins, v_diamonds, v_status, v_until
  from public.players where id = p_player_id for update;
  if not found then raise exception 'PLAYER_NOT_FOUND'; end if;

  if v_status = 'banned' then raise exception 'ACCOUNT_BANNED'; end if;
  if v_status = 'suspended' and v_until is not null and v_until > now()
    then raise exception 'ACCOUNT_SUSPENDED'; end if;
  if v_status = 'suspended' and (v_until is null or v_until <= now()) then
    update public.players set account_status='active',suspended_until=null,moderation_reason=null
    where id=p_player_id;
  end if;
  if v_currency='diamonds' and v_diamonds < v_effective_price then
    raise exception 'NOT_ENOUGH_DIAMONDS';
  elsif v_currency='coins' and v_coins < v_effective_price then
    raise exception 'NOT_ENOUGH_COINS';
  end if;

  select count(*) into v_count from public.cards where set_id = v_pack.set_id;
  if v_count < 1 then raise exception 'EMPTY_PACK_POOL'; end if;

  insert into private.player_pack_pity(player_id,set_id,misses)
  values(p_player_id,v_pack.set_id,0)
  on conflict(player_id,set_id) do nothing;
  select misses into v_pity_misses
  from private.player_pack_pity
  where player_id=p_player_id and set_id=v_pack.set_id
  for update;

  with common_pick as (
    select id,pokemon_name,rarity,image_small,image_large,set_id,card_number
    from public.cards
    where set_id=v_pack.set_id and public.rarity_tier(rarity)=1
    order by random()
    limit greatest(v_pack.cards_per_pack-3,0)
  ), uncommon_pick as (
    select id,pokemon_name,rarity,image_small,image_large,set_id,card_number
    from public.cards
    where set_id=v_pack.set_id and public.rarity_tier(rarity)=2
      and id not in(select id from common_pick)
    order by random()
    limit least(2,greatest(v_pack.cards_per_pack-1,0))
  ), rare_pick as (
    select id,pokemon_name,rarity,image_small,image_large,set_id,card_number
    from public.cards
    where set_id=v_pack.set_id
      and public.rarity_tier(rarity)>=3
      and id not in(select id from common_pick)
      and id not in(select id from uncommon_pick)
      and (
        v_pity_misses<15
        or not exists(select 1 from public.cards c2 where c2.set_id=v_pack.set_id and public.rarity_tier(c2.rarity)>=4)
        or public.rarity_tier(rarity)>=4
      )
    order by (
      -ln(greatest(random(),0.0000001))
      /
      greatest(
        0.000001,
        public.rarity_pull_weight(rarity)
        * case when public.rarity_tier(rarity)>=4
            then (1 + least(v_pity_misses,15)*0.12) * v_rare_multiplier
            else 1 end
      )
    )
    limit case when v_pack.cards_per_pack>0 then 1 else 0 end
  ), preset as (
    select * from common_pick union all
    select * from uncommon_pick union all
    select * from rare_pick
  ), filler as (
    select id,pokemon_name,rarity,image_small,image_large,set_id,card_number
    from public.cards
    where set_id=v_pack.set_id and id not in(select id from preset)
    order by (
      -ln(greatest(random(),0.0000001))
      /
      greatest(
        0.000001,
        public.rarity_pull_weight(rarity)
        * case when public.rarity_tier(rarity)>=4
            then (1 + least(v_pity_misses,15)*0.06) * v_rare_multiplier
            else 1 end
      )
    )
    limit greatest(v_pack.cards_per_pack-(select count(*) from preset),0)
  ), picked as (
    select * from preset union all select * from filler
  ), annotated as (
    select p.*,
      coalesce(pc.quantity,0)>0 as already_owned,
      exists(select 1 from public.card_wishlist w where w.player_id=p_player_id and w.card_id=p.id) as wishlist_hit
    from picked p
    left join public.player_cards pc on pc.player_id=p_player_id and pc.card_id=p.id
  ), upserted as (
    insert into public.player_cards(player_id,card_id,quantity)
    select p_player_id,id,1 from annotated
    on conflict(player_id,card_id)
    do update set quantity=public.player_cards.quantity+1
    returning card_id
  )
  select jsonb_agg(jsonb_build_object(
      'id',a.id,'name',a.pokemon_name,'rarity',a.rarity,
      'image',coalesce(nullif(a.image_large,''),nullif(a.image_small,''),concat('https://images.pokemontcg.io/',a.set_id,'/',a.card_number,'.png')),
      'imageLarge',nullif(a.image_large,''),'imageSmall',nullif(a.image_small,''),
      'imageFallback',concat('https://images.pokemontcg.io/',a.set_id,'/',a.card_number,'.png'),
      'imageFallbackLarge',concat('https://images.pokemontcg.io/',a.set_id,'/',a.card_number,'_hires.png'),
      'isNew',not a.already_owned,'wishlistHit',a.wishlist_hit
    )),
    coalesce(max(public.rarity_tier(a.rarity)),1),
    count(*) filter(where not a.already_owned),
    count(*) filter(where a.wishlist_hit)
  into v_cards,v_highest_tier,v_new_cards,v_wishlist_hits
  from annotated a;

  delete from public.card_wishlist w
  where w.player_id=p_player_id and w.card_id in(
    select elem->>'id' from jsonb_array_elements(coalesce(v_cards,'[]'::jsonb)) elem
    where coalesce((elem->>'wishlistHit')::boolean,false)
  );

  update private.player_pack_pity
  set misses=case when v_highest_tier>=4 then 0 else least(misses+1,30) end,updated_at=now()
  where player_id=p_player_id and set_id=v_pack.set_id;

  update public.players
  set coins=coins-case when v_currency='coins' then v_effective_price else 0 end,
      diamonds=diamonds-case when v_currency='diamonds' then v_effective_price::integer else 0 end,
      xp=xp+v_xp_gain,
      level=greatest(level,1+floor((xp+v_xp_gain)/250.0)::integer)
  where id=p_player_id
  returning coins,diamonds,xp,level into v_new_coins,v_new_diamonds,v_new_xp,v_new_level;

  insert into public.pack_openings(player_id,pack_id,cards_received)
  values(p_player_id,p_pack_id,coalesce(v_cards,'[]'::jsonb))
  returning id into v_opening_id;

  insert into public.player_daily_missions(player_id,mission_date,mission_id,progress)
  values(p_player_id,current_date,'open_2_packs',1)
  on conflict(player_id,mission_date,mission_id)
  do update set progress=public.player_daily_missions.progress+1,updated_at=now();

  perform public.server_refresh_player_achievements(p_player_id);

  return jsonb_build_object(
    'openingId',v_opening_id,'cards',coalesce(v_cards,'[]'::jsonb),
    'coins',v_new_coins,'diamonds',v_new_diamonds,'xp',v_new_xp,'level',v_new_level,'xpGained',v_xp_gain,
    'pricePaid',v_effective_price,'currency',v_currency,'freeBoostersUntil',v_free_until,
    'newCards',v_new_cards,'wishlistHits',v_wishlist_hits,
    'rareMultiplier',v_rare_multiplier
  );
end;
$function$;


revoke all on function private.refresh_pack_economy() from public,anon,authenticated;
grant execute on function private.refresh_pack_economy() to service_role;
revoke all on function private.exchange_coins_for_diamonds(integer) from public,anon;
grant execute on function private.exchange_coins_for_diamonds(integer) to authenticated,service_role;
revoke all on function public.exchange_coins_for_diamonds(integer) from public,anon;
grant execute on function public.exchange_coins_for_diamonds(integer) to authenticated;
revoke all on function private.get_my_rank_snapshot() from public,anon;
grant execute on function private.get_my_rank_snapshot() to authenticated,service_role;
revoke all on function public.get_my_rank_snapshot() from public,anon;
grant execute on function public.get_my_rank_snapshot() to authenticated;
revoke all on function public.server_open_pack(uuid,uuid) from public,anon,authenticated;
grant execute on function public.server_open_pack(uuid,uuid) to service_role;
revoke all on function public.server_background_tick() from public,anon,authenticated;
grant execute on function public.server_background_tick() to service_role;

select private.refresh_pack_economy();
