-- Social realtime: global chat, online visibility and in-app update log.
-- Live schema was applied first; this migration keeps Git history/reproducibility aligned.

alter table public.players
  add column if not exists show_online_status boolean not null default true;

create table if not exists public.global_chat_messages (
  id uuid primary key default gen_random_uuid(),
  player_id uuid not null references public.players(id) on delete cascade,
  body text not null,
  sender_username text not null,
  sender_profile_icon text not null default 'pokeball',
  created_at timestamptz not null default now(),
  deleted_at timestamptz,
  constraint global_chat_messages_body_check
    check (char_length(trim(body)) between 1 and 280)
);

create index if not exists global_chat_messages_created_idx
  on public.global_chat_messages(created_at desc)
  where deleted_at is null;

create index if not exists global_chat_messages_player_created_idx
  on public.global_chat_messages(player_id,created_at desc);

alter table public.global_chat_messages enable row level security;

revoke all on table public.global_chat_messages from anon,authenticated;
grant select on table public.global_chat_messages to authenticated;

drop policy if exists "authenticated read global chat" on public.global_chat_messages;
create policy "authenticated read global chat"
  on public.global_chat_messages
  for select to authenticated
  using (deleted_at is null);

create table if not exists public.app_update_logs (
  id bigint generated by default as identity primary key,
  version text not null,
  title text not null,
  summary text not null,
  changes text[] not null default '{}'::text[],
  published_at timestamptz not null default now(),
  active boolean not null default true
);

create index if not exists app_update_logs_published_idx
  on public.app_update_logs(active,published_at desc);

alter table public.app_update_logs enable row level security;

revoke all on table public.app_update_logs from anon,authenticated;
grant select on table public.app_update_logs to authenticated;

drop policy if exists "authenticated read update logs" on public.app_update_logs;
create policy "authenticated read update logs"
  on public.app_update_logs
  for select to authenticated
  using (active=true);

create or replace function public.set_my_online_visibility(p_visible boolean)
returns boolean
language plpgsql
security definer
set search_path=''
as $$
declare
  v_id uuid := auth.uid();
begin
  if v_id is null then raise exception 'UNAUTHENTICATED'; end if;

  update public.players
  set show_online_status=coalesce(p_visible,true)
  where id=v_id;

  if not found then raise exception 'PLAYER_NOT_FOUND'; end if;
  return coalesce(p_visible,true);
end;
$$;

revoke all on function public.set_my_online_visibility(boolean) from public,anon,authenticated;
grant execute on function public.set_my_online_visibility(boolean) to authenticated;

create or replace function public.send_global_chat_message(p_body text)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_player_id uuid := auth.uid();
  v_body text := trim(coalesce(p_body,''));
  v_username text;
  v_profile_icon text;
  v_row public.global_chat_messages%rowtype;
begin
  if v_player_id is null then raise exception 'UNAUTHENTICATED'; end if;
  if char_length(v_body) < 1 or char_length(v_body) > 280 then
    raise exception 'INVALID_MESSAGE';
  end if;

  select username,profile_icon
  into v_username,v_profile_icon
  from public.players
  where id=v_player_id and account_status='active';

  if v_username is null then raise exception 'ACCOUNT_RESTRICTED'; end if;

  if exists(
    select 1
    from public.global_chat_messages
    where player_id=v_player_id
      and created_at > now() - interval '2 seconds'
  ) then
    raise exception 'CHAT_RATE_LIMIT';
  end if;

  insert into public.global_chat_messages(
    player_id,body,sender_username,sender_profile_icon
  )
  values(
    v_player_id,
    v_body,
    v_username,
    coalesce(v_profile_icon,'pokeball')
  )
  returning * into v_row;

  return jsonb_build_object(
    'id',v_row.id,
    'playerId',v_row.player_id,
    'body',v_row.body,
    'createdAt',v_row.created_at,
    'username',v_row.sender_username,
    'profileIcon',v_row.sender_profile_icon
  );
end;
$$;

revoke all on function public.send_global_chat_message(text) from public,anon,authenticated;
grant execute on function public.send_global_chat_message(text) to authenticated;

insert into public.app_update_logs(version,title,summary,changes,published_at,active)
select
  '0.1.1 • OTA 28/08',
  'Social e qualidade de vida',
  'Atualização focada em navegação, social, administração e acompanhamento da coleção.',
  array[
    'Passe de Batalha com 50 níveis, trilhas Grátis e VIP, missões e títulos exclusivos',
    'Valor em US$ das cartas na loja e diretamente no resultado dos boosters',
    'Correção do topo duplicado e painel administrativo recolhível',
    'Correção segura de Coins e Diamantes pelo administrador com auditoria',
    'Chat global em tempo real na página inicial',
    'Status online dos amigos com opção de privacidade',
    'Botões Voltar com retorno seguro para a página inicial'
  ]::text[],
  now(),
  true
where not exists (
  select 1
  from public.app_update_logs
  where version='0.1.1 • OTA 28/08'
);

do $$
begin
  begin
    alter publication supabase_realtime add table public.global_chat_messages;
  exception
    when duplicate_object then null;
  end;
end $$;
