-- Battle Pass Season 1: server-owned progression, missions, rewards and VIP.
-- Battle Pass XP is intentionally separate from the account level XP.

create table if not exists public.battle_pass_seasons (
  id text primary key,
  name text not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  max_level integer not null default 50 check (max_level between 1 and 100),
  vip_price_diamonds integer not null default 25 check (vip_price_diamonds >= 0),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);
create index if not exists battle_pass_seasons_active_window_idx on public.battle_pass_seasons(active,starts_at,ends_at);

create table if not exists public.battle_pass_reward_definitions (
  season_id text not null references public.battle_pass_seasons(id) on delete cascade,
  level integer not null check (level between 1 and 100),
  track text not null check (track in ('free','vip')),
  label text not null,
  reward jsonb not null default '{}'::jsonb,
  primary key (season_id,level,track)
);
create index if not exists battle_pass_rewards_season_level_idx on public.battle_pass_reward_definitions(season_id,level);

create table if not exists public.battle_pass_missions (
  id text primary key,
  season_id text not null references public.battle_pass_seasons(id) on delete cascade,
  title text not null,
  description text not null default '',
  event_key text not null,
  period text not null check (period in ('daily','weekly','season')),
  target integer not null check (target > 0),
  xp_reward integer not null check (xp_reward > 0),
  sort_order integer not null default 0,
  active boolean not null default true
);
create index if not exists battle_pass_missions_event_idx on public.battle_pass_missions(season_id,event_key,active);
create index if not exists battle_pass_missions_display_idx on public.battle_pass_missions(season_id,period,sort_order);

create table if not exists public.battle_pass_player_progress (
  player_id uuid not null references public.players(id) on delete cascade,
  season_id text not null references public.battle_pass_seasons(id) on delete cascade,
  xp bigint not null default 0 check (xp >= 0),
  level integer not null default 1 check (level between 1 and 100),
  vip_unlocked boolean not null default false,
  vip_unlocked_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (player_id,season_id)
);
create index if not exists battle_pass_player_progress_season_level_idx on public.battle_pass_player_progress(season_id,level desc);

create table if not exists public.battle_pass_mission_progress (
  player_id uuid not null references public.players(id) on delete cascade,
  mission_id text not null references public.battle_pass_missions(id) on delete cascade,
  period_key text not null,
  progress integer not null default 0 check (progress >= 0),
  xp_awarded boolean not null default false,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (player_id,mission_id,period_key)
);
create index if not exists battle_pass_mission_progress_player_idx on public.battle_pass_mission_progress(player_id,updated_at desc);
create index if not exists battle_pass_mission_progress_mission_idx on public.battle_pass_mission_progress(mission_id,updated_at desc);

create table if not exists public.battle_pass_reward_claims (
  player_id uuid not null references public.players(id) on delete cascade,
  season_id text not null references public.battle_pass_seasons(id) on delete cascade,
  level integer not null,
  track text not null check (track in ('free','vip')),
  reward jsonb not null,
  claimed_at timestamptz not null default now(),
  primary key (player_id,season_id,level,track)
);
create index if not exists battle_pass_reward_claims_player_idx on public.battle_pass_reward_claims(player_id,season_id,claimed_at desc);
create index if not exists battle_pass_reward_claims_season_idx on public.battle_pass_reward_claims(season_id,claimed_at desc);

create table if not exists public.battle_pass_admin_grants (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.players(id) on delete restrict,
  target_id uuid not null references public.players(id) on delete cascade,
  season_id text not null references public.battle_pass_seasons(id) on delete cascade,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists battle_pass_admin_grants_target_idx on public.battle_pass_admin_grants(target_id,created_at desc);
create index if not exists battle_pass_admin_grants_actor_idx on public.battle_pass_admin_grants(actor_id,created_at desc);
create index if not exists battle_pass_admin_grants_season_idx on public.battle_pass_admin_grants(season_id,created_at desc);

alter table public.battle_pass_seasons enable row level security;
alter table public.battle_pass_reward_definitions enable row level security;
alter table public.battle_pass_missions enable row level security;
alter table public.battle_pass_player_progress enable row level security;
alter table public.battle_pass_mission_progress enable row level security;
alter table public.battle_pass_reward_claims enable row level security;
alter table public.battle_pass_admin_grants enable row level security;

revoke all on table public.battle_pass_seasons from anon,authenticated;
revoke all on table public.battle_pass_reward_definitions from anon,authenticated;
revoke all on table public.battle_pass_missions from anon,authenticated;
revoke all on table public.battle_pass_player_progress from anon,authenticated;
revoke all on table public.battle_pass_mission_progress from anon,authenticated;
revoke all on table public.battle_pass_reward_claims from anon,authenticated;
revoke all on table public.battle_pass_admin_grants from anon,authenticated;

grant select on table public.battle_pass_seasons to authenticated;
grant select on table public.battle_pass_reward_definitions to authenticated;
grant select on table public.battle_pass_missions to authenticated;
grant select on table public.battle_pass_player_progress to authenticated;
grant select on table public.battle_pass_mission_progress to authenticated;
grant select on table public.battle_pass_reward_claims to authenticated;

drop policy if exists "battle pass seasons readable" on public.battle_pass_seasons;
create policy "battle pass seasons readable" on public.battle_pass_seasons for select to authenticated using (true);
drop policy if exists "battle pass rewards readable" on public.battle_pass_reward_definitions;
create policy "battle pass rewards readable" on public.battle_pass_reward_definitions for select to authenticated using (true);
drop policy if exists "battle pass missions readable" on public.battle_pass_missions;
create policy "battle pass missions readable" on public.battle_pass_missions for select to authenticated using (active=true);
drop policy if exists "players read own battle pass progress" on public.battle_pass_player_progress;
create policy "players read own battle pass progress" on public.battle_pass_player_progress for select to authenticated using ((select auth.uid())=player_id);
drop policy if exists "players read own battle pass mission progress" on public.battle_pass_mission_progress;
create policy "players read own battle pass mission progress" on public.battle_pass_mission_progress for select to authenticated using ((select auth.uid())=player_id);
drop policy if exists "players read own battle pass reward claims" on public.battle_pass_reward_claims;
create policy "players read own battle pass reward claims" on public.battle_pass_reward_claims for select to authenticated using ((select auth.uid())=player_id);

insert into public.battle_pass_seasons(id,name,starts_at,ends_at,max_level,vip_price_diamonds,active)
values ('season_2026_01','Temporada 1 — Kanto Ascendente','2026-08-28T00:00:00Z','2026-09-28T00:00:00Z',50,25,true)
on conflict(id) do update set name=excluded.name,starts_at=excluded.starts_at,ends_at=excluded.ends_at,max_level=excluded.max_level,vip_price_diamonds=excluded.vip_price_diamonds,active=true;

insert into public.battle_pass_reward_definitions(season_id,level,track,label,reward)
select 'season_2026_01',lvl,'free',
  case when lvl % 10 = 0
    then format('🪙 %s + 💎 %s',(5000+lvl*1000)::text,(case lvl when 10 then 1 when 20 then 1 when 30 then 2 when 40 then 2 when 50 then 4 else 0 end)::text)
    else format('🪙 %s',(5000+lvl*1000)::text)
  end,
  jsonb_strip_nulls(jsonb_build_object(
    'coins',5000+lvl*1000,
    'diamonds',case lvl when 10 then 1 when 20 then 1 when 30 then 2 when 40 then 2 when 50 then 4 else null end
  ))
from generate_series(1,50) lvl
on conflict(season_id,level,track) do update set label=excluded.label,reward=excluded.reward;

insert into public.battle_pass_reward_definitions(season_id,level,track,label,reward)
select 'season_2026_01',lvl,'vip',
  case when lvl % 5 = 0
    then format('🪙 %s + 💎 %s',(8000+lvl*1500)::text,(case when lvl=50 then 5 else 2 end)::text)
    else format('🪙 %s',(8000+lvl*1500)::text)
  end,
  jsonb_strip_nulls(jsonb_build_object(
    'coins',8000+lvl*1500,
    'diamonds',case when lvl % 5=0 then case when lvl=50 then 5 else 2 end else null end
  ))
from generate_series(1,50) lvl
on conflict(season_id,level,track) do update set label=excluded.label,reward=excluded.reward;

insert into public.battle_pass_missions(season_id,id,title,description,event_key,period,target,xp_reward,sort_order,active)
values
('season_2026_01','daily_open_2','Abrir 2 boosters','Abra 2 boosters hoje.','open_pack','daily',2,120,10,true),
('season_2026_01','daily_battle_2','Jogar 2 batalhas','Complete 2 batalhas hoje.','play_battle','daily',2,120,20,true),
('season_2026_01','daily_win_1','Vencer 1 batalha','Vença uma batalha hoje.','win_battle','daily',1,150,30,true),
('season_2026_01','daily_trade_1','Concluir 1 troca','Finalize uma troca com outro treinador hoje.','complete_trade','daily',1,100,40,true),
('season_2026_01','daily_list_1','Anunciar 1 carta','Coloque uma carta à venda no mercado hoje.','market_list','daily',1,80,50,true),
('season_2026_01','weekly_open_12','Abrir 12 boosters','Abra 12 boosters nesta semana.','open_pack','weekly',12,500,100,true),
('season_2026_01','weekly_battle_12','Jogar 12 batalhas','Complete 12 batalhas nesta semana.','play_battle','weekly',12,500,110,true),
('season_2026_01','weekly_win_5','Vencer 5 batalhas','Vença 5 batalhas nesta semana.','win_battle','weekly',5,600,120,true),
('season_2026_01','weekly_ranked_win_3','Vencer 3 ranqueadas','Vença 3 batalhas ranqueadas nesta semana.','ranked_win','weekly',3,500,130,true),
('season_2026_01','weekly_trade_3','Concluir 3 trocas','Finalize 3 trocas nesta semana.','complete_trade','weekly',3,400,140,true),
('season_2026_01','weekly_buy_2','Comprar 2 cartas','Compre 2 anúncios do mercado nesta semana.','market_buy','weekly',2,250,150,true),
('season_2026_01','weekly_sell_2','Vender 2 cartas','Venda 2 anúncios do mercado nesta semana.','market_sell','weekly',2,250,160,true),
('season_2026_01','season_open_25','Colecionador I','Abra 25 boosters na temporada.','open_pack','season',25,1200,200,true),
('season_2026_01','season_open_75','Colecionador II','Abra 75 boosters na temporada.','open_pack','season',75,2500,210,true),
('season_2026_01','season_open_150','Colecionador III','Abra 150 boosters na temporada.','open_pack','season',150,4500,220,true),
('season_2026_01','season_battle_25','Combatente I','Complete 25 batalhas na temporada.','play_battle','season',25,1500,230,true),
('season_2026_01','season_battle_60','Combatente II','Complete 60 batalhas na temporada.','play_battle','season',60,3000,240,true),
('season_2026_01','season_win_10','Vencedor I','Vença 10 batalhas na temporada.','win_battle','season',10,1500,250,true),
('season_2026_01','season_win_30','Vencedor II','Vença 30 batalhas na temporada.','win_battle','season',30,3500,260,true),
('season_2026_01','season_ranked_10','Ranqueado I','Vença 10 batalhas ranqueadas na temporada.','ranked_win','season',10,2000,270,true),
('season_2026_01','season_ranked_25','Ranqueado II','Vença 25 batalhas ranqueadas na temporada.','ranked_win','season',25,4000,280,true),
('season_2026_01','season_trade_10','Negociador I','Conclua 10 trocas na temporada.','complete_trade','season',10,1800,290,true),
('season_2026_01','season_trade_25','Negociador II','Conclua 25 trocas na temporada.','complete_trade','season',25,3500,300,true),
('season_2026_01','season_buy_5','Comprador I','Compre 5 cartas no mercado na temporada.','market_buy','season',5,1200,310,true),
('season_2026_01','season_buy_15','Comprador II','Compre 15 cartas no mercado na temporada.','market_buy','season',15,2500,320,true),
('season_2026_01','season_sell_5','Vendedor I','Venda 5 cartas no mercado na temporada.','market_sell','season',5,1200,330,true),
('season_2026_01','season_sell_15','Vendedor II','Venda 15 cartas no mercado na temporada.','market_sell','season',15,2500,340,true),
('season_2026_01','season_list_10','Lojista I','Publique 10 anúncios na temporada.','market_list','season',10,1000,350,true),
('season_2026_01','season_list_30','Lojista II','Publique 30 anúncios na temporada.','market_list','season',30,2000,360,true)
on conflict(id) do update set season_id=excluded.season_id,title=excluded.title,description=excluded.description,event_key=excluded.event_key,period=excluded.period,target=excluded.target,xp_reward=excluded.xp_reward,sort_order=excluded.sort_order,active=true;

create or replace function private.battle_pass_xp_to_reach_level(p_level integer)
returns bigint language sql immutable set search_path='' as $$
  select coalesce(sum((500+(g-1)*30)::bigint),0)
  from generate_series(1,greatest(0,least(coalesce(p_level,1),50)-1)) g;
$$;

create or replace function private.battle_pass_level_for_xp(p_xp bigint)
returns integer language sql immutable set search_path='' as $$
  select coalesce(max(lvl),1) from generate_series(1,50) lvl
  where greatest(coalesce(p_xp,0),0)>=private.battle_pass_xp_to_reach_level(lvl);
$$;

create or replace function private.battle_pass_period_key(p_period text,p_season_id text,p_at timestamptz default now())
returns text language sql stable set search_path='' as $$
  select case p_period
    when 'daily' then to_char(timezone('America/Sao_Paulo',p_at),'YYYY-MM-DD')
    when 'weekly' then to_char(timezone('America/Sao_Paulo',p_at),'IYYY-"W"IW')
    else p_season_id
  end;
$$;

create or replace function private.battle_pass_record_event(p_player_id uuid,p_event_key text,p_amount integer default 1)
returns void language plpgsql security definer set search_path='' as $$
declare
  v_season public.battle_pass_seasons%rowtype;
  v_mission public.battle_pass_missions%rowtype;
  v_period_key text;
  v_progress integer;
  v_xp_gain bigint:=0;
  v_cap bigint:=private.battle_pass_xp_to_reach_level(50);
begin
  if p_player_id is null or p_amount is null or p_amount<=0 then return; end if;
  select * into v_season from public.battle_pass_seasons
  where active=true and starts_at<=now() and ends_at>now()
  order by starts_at desc limit 1;
  if v_season.id is null then return; end if;

  insert into public.battle_pass_player_progress(player_id,season_id)
  values(p_player_id,v_season.id) on conflict(player_id,season_id) do nothing;

  for v_mission in
    select * from public.battle_pass_missions
    where season_id=v_season.id and active=true and event_key=p_event_key
    order by sort_order
  loop
    v_period_key:=private.battle_pass_period_key(v_mission.period,v_season.id,now());
    insert into public.battle_pass_mission_progress(player_id,mission_id,period_key,progress,updated_at)
    values(p_player_id,v_mission.id,v_period_key,least(v_mission.target,p_amount),now())
    on conflict(player_id,mission_id,period_key) do update
    set progress=least(v_mission.target,public.battle_pass_mission_progress.progress+excluded.progress),updated_at=now()
    returning progress into v_progress;

    if v_progress>=v_mission.target then
      update public.battle_pass_mission_progress
      set xp_awarded=true,completed_at=coalesce(completed_at,now()),updated_at=now()
      where player_id=p_player_id and mission_id=v_mission.id and period_key=v_period_key and xp_awarded=false;
      if found then v_xp_gain:=v_xp_gain+v_mission.xp_reward; end if;
    end if;
  end loop;

  if v_xp_gain>0 then
    update public.battle_pass_player_progress
    set xp=least(v_cap,xp+v_xp_gain),
        level=private.battle_pass_level_for_xp(least(v_cap,xp+v_xp_gain)),
        updated_at=now()
    where player_id=p_player_id and season_id=v_season.id;
  end if;
end;
$$;

create or replace function public.get_my_battle_pass()
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_player_id uuid:=auth.uid();
  v_season public.battle_pass_seasons%rowtype;
  v_progress public.battle_pass_player_progress%rowtype;
  v_rewards jsonb:='[]'::jsonb;
  v_missions jsonb:='[]'::jsonb;
  v_level_start bigint;
  v_next_level_cost bigint;
begin
  if v_player_id is null then raise exception 'UNAUTHENTICATED'; end if;
  select * into v_season from public.battle_pass_seasons
  where active=true and starts_at<=now() and ends_at>now()
  order by starts_at desc limit 1;
  if v_season.id is null then return null; end if;

  insert into public.battle_pass_player_progress(player_id,season_id)
  values(v_player_id,v_season.id) on conflict(player_id,season_id) do nothing;
  select * into v_progress from public.battle_pass_player_progress
  where player_id=v_player_id and season_id=v_season.id;

  v_level_start:=private.battle_pass_xp_to_reach_level(v_progress.level);
  v_next_level_cost:=case when v_progress.level>=v_season.max_level then 0
    else private.battle_pass_xp_to_reach_level(v_progress.level+1)-v_level_start end;

  select coalesce(jsonb_agg(jsonb_build_object(
    'level',r.level,'track',r.track,'label',r.label,'reward',r.reward,'claimed',(c.player_id is not null)
  ) order by r.level,case when r.track='free' then 0 else 1 end),'[]'::jsonb)
  into v_rewards
  from public.battle_pass_reward_definitions r
  left join public.battle_pass_reward_claims c
    on c.player_id=v_player_id and c.season_id=r.season_id and c.level=r.level and c.track=r.track
  where r.season_id=v_season.id and r.level between 1 and v_season.max_level;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id',m.id,'title',m.title,'description',m.description,'eventKey',m.event_key,
    'period',m.period,'periodKey',private.battle_pass_period_key(m.period,v_season.id,now()),
    'target',m.target,'xpReward',m.xp_reward,'progress',least(m.target,coalesce(mp.progress,0)),
    'completed',coalesce(mp.xp_awarded,false),'completedAt',mp.completed_at
  ) order by case m.period when 'daily' then 0 when 'weekly' then 1 else 2 end,m.sort_order),'[]'::jsonb)
  into v_missions
  from public.battle_pass_missions m
  left join public.battle_pass_mission_progress mp
    on mp.player_id=v_player_id and mp.mission_id=m.id
   and mp.period_key=private.battle_pass_period_key(m.period,v_season.id,now())
  where m.season_id=v_season.id and m.active=true;

  return jsonb_build_object(
    'season',jsonb_build_object(
      'id',v_season.id,'name',v_season.name,'startsAt',v_season.starts_at,'endsAt',v_season.ends_at,
      'maxLevel',v_season.max_level,'vipPriceDiamonds',v_season.vip_price_diamonds,
      'totalXpRequired',private.battle_pass_xp_to_reach_level(v_season.max_level)
    ),
    'progress',jsonb_build_object(
      'xp',v_progress.xp,'level',v_progress.level,'vipUnlocked',v_progress.vip_unlocked,
      'vipUnlockedAt',v_progress.vip_unlocked_at,'xpIntoLevel',greatest(0,v_progress.xp-v_level_start),
      'xpForNextLevel',v_next_level_cost
    ),
    'rewards',v_rewards,'missions',v_missions
  );
end;
$$;

create or replace function public.purchase_battle_pass_vip()
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_player_id uuid:=auth.uid();
  v_season public.battle_pass_seasons%rowtype;
  v_progress public.battle_pass_player_progress%rowtype;
  v_balance bigint;
begin
  if v_player_id is null then raise exception 'UNAUTHENTICATED'; end if;
  if exists(select 1 from public.app_runtime_status where id=1 and maintenance_enabled=true) then raise exception 'APP_MAINTENANCE'; end if;

  select * into v_season from public.battle_pass_seasons
  where active=true and starts_at<=now() and ends_at>now()
  order by starts_at desc limit 1;
  if v_season.id is null then raise exception 'NO_ACTIVE_BATTLE_PASS'; end if;

  insert into public.battle_pass_player_progress(player_id,season_id)
  values(v_player_id,v_season.id) on conflict(player_id,season_id) do nothing;
  select * into v_progress from public.battle_pass_player_progress
  where player_id=v_player_id and season_id=v_season.id for update;

  if v_progress.vip_unlocked then
    select diamonds into v_balance from public.players where id=v_player_id;
    return jsonb_build_object('vipUnlocked',true,'diamonds',v_balance,'alreadyUnlocked',true);
  end if;

  update public.players set diamonds=diamonds-v_season.vip_price_diamonds
  where id=v_player_id and diamonds>=v_season.vip_price_diamonds
  returning diamonds into v_balance;
  if not found then raise exception 'NOT_ENOUGH_DIAMONDS'; end if;

  update public.battle_pass_player_progress
  set vip_unlocked=true,vip_unlocked_at=now(),updated_at=now()
  where player_id=v_player_id and season_id=v_season.id;

  return jsonb_build_object('vipUnlocked',true,'diamonds',v_balance,'priceDiamonds',v_season.vip_price_diamonds,'alreadyUnlocked',false);
end;
$$;

create or replace function public.claim_battle_pass_reward(p_level integer,p_track text)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_player_id uuid:=auth.uid();
  v_season public.battle_pass_seasons%rowtype;
  v_progress public.battle_pass_player_progress%rowtype;
  v_reward jsonb;
  v_coins bigint:=0;
  v_diamonds bigint:=0;
  v_new_coins bigint;
  v_new_diamonds bigint;
begin
  if v_player_id is null then raise exception 'UNAUTHENTICATED'; end if;
  if p_track not in ('free','vip') then raise exception 'INVALID_TRACK'; end if;
  if exists(select 1 from public.app_runtime_status where id=1 and maintenance_enabled=true) then raise exception 'APP_MAINTENANCE'; end if;

  select * into v_season from public.battle_pass_seasons
  where active=true and starts_at<=now() and ends_at>now()
  order by starts_at desc limit 1;
  if v_season.id is null then raise exception 'NO_ACTIVE_BATTLE_PASS'; end if;
  if p_level<1 or p_level>v_season.max_level then raise exception 'INVALID_LEVEL'; end if;

  insert into public.battle_pass_player_progress(player_id,season_id)
  values(v_player_id,v_season.id) on conflict(player_id,season_id) do nothing;
  select * into v_progress from public.battle_pass_player_progress
  where player_id=v_player_id and season_id=v_season.id for update;

  if p_level>v_progress.level then raise exception 'LEVEL_LOCKED'; end if;
  if p_track='vip' and not v_progress.vip_unlocked then raise exception 'VIP_REQUIRED'; end if;

  select reward into v_reward from public.battle_pass_reward_definitions
  where season_id=v_season.id and level=p_level and track=p_track;
  if v_reward is null then raise exception 'REWARD_NOT_FOUND'; end if;

  insert into public.battle_pass_reward_claims(player_id,season_id,level,track,reward)
  values(v_player_id,v_season.id,p_level,p_track,v_reward)
  on conflict(player_id,season_id,level,track) do nothing;
  if not found then raise exception 'REWARD_ALREADY_CLAIMED'; end if;

  v_coins:=coalesce((v_reward->>'coins')::bigint,0);
  v_diamonds:=coalesce((v_reward->>'diamonds')::bigint,0);
  update public.players set coins=coins+v_coins,diamonds=diamonds+v_diamonds
  where id=v_player_id returning coins,diamonds into v_new_coins,v_new_diamonds;
  if not found then raise exception 'PLAYER_NOT_FOUND'; end if;

  return jsonb_build_object('level',p_level,'track',p_track,'reward',v_reward,'coins',v_new_coins,'diamonds',v_new_diamonds);
end;
$$;

create or replace function public.server_admin_grant_battle_pass_vip(p_actor_id uuid,p_target_ids uuid[],p_note text default null)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
  v_season public.battle_pass_seasons%rowtype;
  v_count integer:=0;
  v_recipients jsonb:='[]'::jsonb;
begin
  if p_actor_id is null or not exists(select 1 from public.admin_members where player_id=p_actor_id) then raise exception 'FORBIDDEN'; end if;
  if p_target_ids is null or coalesce(array_length(p_target_ids,1),0)<1 or array_length(p_target_ids,1)>100 then raise exception 'INVALID_TARGETS'; end if;

  select * into v_season from public.battle_pass_seasons
  where active=true and starts_at<=now() and ends_at>now()
  order by starts_at desc limit 1;
  if v_season.id is null then raise exception 'NO_ACTIVE_BATTLE_PASS'; end if;

  with targets as (select distinct x as player_id from unnest(p_target_ids) x),
  valid as (select p.id,p.username from public.players p join targets t on t.player_id=p.id),
  granted as (
    insert into public.battle_pass_player_progress(player_id,season_id,vip_unlocked,vip_unlocked_at,updated_at)
    select id,v_season.id,true,now(),now() from valid
    on conflict(player_id,season_id) do update
      set vip_unlocked=true,
          vip_unlocked_at=coalesce(public.battle_pass_player_progress.vip_unlocked_at,excluded.vip_unlocked_at),
          updated_at=now()
    returning player_id
  )
  select count(*) into v_count from granted;

  insert into public.battle_pass_admin_grants(actor_id,target_id,season_id,note)
  select p_actor_id,p.id,v_season.id,nullif(trim(coalesce(p_note,'')),'')
  from public.players p where p.id in (select distinct x from unnest(p_target_ids) x);

  select coalesce(jsonb_agg(jsonb_build_object('id',p.id,'username',p.username) order by p.username),'[]'::jsonb)
  into v_recipients from public.players p
  where p.id in (select distinct x from unnest(p_target_ids) x);

  return jsonb_build_object('seasonId',v_season.id,'recipientCount',v_count,'recipients',v_recipients);
end;
$$;

revoke all on function private.battle_pass_xp_to_reach_level(integer) from public,anon,authenticated;
revoke all on function private.battle_pass_level_for_xp(bigint) from public,anon,authenticated;
revoke all on function private.battle_pass_period_key(text,text,timestamptz) from public,anon,authenticated;
revoke all on function private.battle_pass_record_event(uuid,text,integer) from public,anon,authenticated;
revoke all on function public.get_my_battle_pass() from public,anon,authenticated;
grant execute on function public.get_my_battle_pass() to authenticated;
revoke all on function public.purchase_battle_pass_vip() from public,anon,authenticated;
grant execute on function public.purchase_battle_pass_vip() to authenticated;
revoke all on function public.claim_battle_pass_reward(integer,text) from public,anon,authenticated;
grant execute on function public.claim_battle_pass_reward(integer,text) to authenticated;
revoke all on function public.server_admin_grant_battle_pass_vip(uuid,uuid[],text) from public,anon,authenticated;
grant execute on function public.server_admin_grant_battle_pass_vip(uuid,uuid[],text) to service_role;

create or replace function private.trg_battle_pass_pack()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  perform private.battle_pass_record_event(new.player_id,'open_pack',1);
  return new;
end;
$$;

create or replace function private.trg_battle_pass_battle()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.status='completed' and old.status is distinct from new.status then
    perform private.battle_pass_record_event(new.challenger_id,'play_battle',1);
    perform private.battle_pass_record_event(new.opponent_id,'play_battle',1);
    if new.winner_id is not null then
      perform private.battle_pass_record_event(new.winner_id,'win_battle',1);
      if coalesce(new.is_ranked,false) then perform private.battle_pass_record_event(new.winner_id,'ranked_win',1); end if;
    end if;
  end if;
  return new;
end;
$$;

create or replace function private.trg_battle_pass_trade()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.status='completed' and old.status is distinct from new.status then
    perform private.battle_pass_record_event(new.sender_id,'complete_trade',1);
    perform private.battle_pass_record_event(new.receiver_id,'complete_trade',1);
  end if;
  return new;
end;
$$;

create or replace function private.trg_battle_pass_market_insert()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.status='active' then perform private.battle_pass_record_event(new.seller_id,'market_list',1); end if;
  return new;
end;
$$;

create or replace function private.trg_battle_pass_market_sold()
returns trigger language plpgsql security definer set search_path='' as $$
begin
  if new.status='sold' and old.status is distinct from new.status then
    perform private.battle_pass_record_event(new.seller_id,'market_sell',1);
    if new.buyer_id is not null then perform private.battle_pass_record_event(new.buyer_id,'market_buy',1); end if;
  end if;
  return new;
end;
$$;

revoke all on function private.trg_battle_pass_pack() from public,anon,authenticated;
revoke all on function private.trg_battle_pass_battle() from public,anon,authenticated;
revoke all on function private.trg_battle_pass_trade() from public,anon,authenticated;
revoke all on function private.trg_battle_pass_market_insert() from public,anon,authenticated;
revoke all on function private.trg_battle_pass_market_sold() from public,anon,authenticated;

drop trigger if exists trg_battle_pass_pack on public.pack_openings;
create trigger trg_battle_pass_pack after insert on public.pack_openings for each row execute function private.trg_battle_pass_pack();

drop trigger if exists trg_battle_pass_battle on public.battles;
create trigger trg_battle_pass_battle after update of status on public.battles for each row execute function private.trg_battle_pass_battle();

drop trigger if exists trg_battle_pass_trade on public.trades;
create trigger trg_battle_pass_trade after update of status on public.trades for each row execute function private.trg_battle_pass_trade();

drop trigger if exists trg_battle_pass_market_insert on public.market_listings;
create trigger trg_battle_pass_market_insert after insert on public.market_listings for each row execute function private.trg_battle_pass_market_insert();

drop trigger if exists trg_battle_pass_market_sold on public.market_listings;
create trigger trg_battle_pass_market_sold after update of status on public.market_listings for each row execute function private.trg_battle_pass_market_sold();
