-- Granular delegated administration and complete player account auditing.
-- Owner keeps unrestricted access; delegated admins only receive explicit capabilities.

create table if not exists private.admin_member_permissions (
  player_id uuid primary key references public.admin_members(player_id) on delete cascade,
  permissions text[] not null default '{}'::text[],
  updated_by uuid null references public.players(id) on delete set null,
  updated_at timestamptz not null default now(),
  constraint admin_member_permissions_allowed_check
    check (
      permissions <@ array[
        'audit_users',
        'moderate_users',
        'economy_grant',
        'economy_remove',
        'battlepass_grant',
        'codes_manage',
        'announcements_manage',
        'events_manage',
        'maintenance_manage',
        'guilds_manage'
      ]::text[]
    )
);

create index if not exists admin_member_permissions_updated_by_idx
  on private.admin_member_permissions(updated_by)
  where updated_by is not null;

alter table private.admin_member_permissions enable row level security;
revoke all on private.admin_member_permissions from public, anon, authenticated;
grant select,insert,update,delete on private.admin_member_permissions to service_role;

create table if not exists private.admin_access_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid not null references public.players(id) on delete restrict,
  target_id uuid not null references public.players(id) on delete cascade,
  action text not null check (action in ('grant_admin','update_permissions','revoke_admin')),
  permissions text[] not null default '{}'::text[],
  created_at timestamptz not null default now()
);

create index if not exists admin_access_audit_target_created_idx
  on private.admin_access_audit(target_id,created_at desc);
create index if not exists admin_access_audit_actor_created_idx
  on private.admin_access_audit(actor_id,created_at desc);

alter table private.admin_access_audit enable row level security;
revoke all on private.admin_access_audit from public, anon, authenticated;
grant select,insert on private.admin_access_audit to service_role;

CREATE OR REPLACE FUNCTION private.admin_has_permission(p_actor_id uuid, p_permission text)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
  select exists (
    select 1
    from public.admin_members am
    left join private.admin_member_permissions amp on amp.player_id=am.player_id
    where am.player_id=p_actor_id
      and (
        am.role='owner'
        or p_permission=any(coalesce(amp.permissions,'{}'::text[]))
      )
  );
$function$;

CREATE OR REPLACE FUNCTION private.guild_action(p_action text, p_guild_id text DEFAULT NULL::text, p_target_id uuid DEFAULT NULL::uuid, p_role text DEFAULT NULL::text, p_invite_id uuid DEFAULT NULL::uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid := auth.uid();
  v_invite public.guild_invites%rowtype;
  v_old_leader uuid;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;
  if p_action not in ('join','leave','invite','respond_accept','respond_decline','kick','set_role','admin_set_leader') then
    raise exception 'INVALID_GUILD_ACTION';
  end if;

  if p_action = 'join' then
    if not exists (select 1 from public.guilds where id=p_guild_id) then raise exception 'GUILD_NOT_FOUND'; end if;
    if exists (select 1 from public.guild_members where player_id=v_actor) then raise exception 'ALREADY_IN_GUILD'; end if;
    insert into public.guild_members(player_id,guild_id,role) values(v_actor,p_guild_id,'member');
    update public.guild_invites set status='accepted', responded_at=now()
      where invited_player_id=v_actor and guild_id=p_guild_id and status='pending';
    return jsonb_build_object('status','joined','guildId',p_guild_id);
  end if;

  if p_action = 'leave' then
    if exists (select 1 from public.guilds where leader_id=v_actor) then raise exception 'LEADER_CANNOT_LEAVE'; end if;
    delete from public.guild_members where player_id=v_actor;
    if not found then raise exception 'NOT_IN_GUILD'; end if;
    return jsonb_build_object('status','left');
  end if;

  if p_action = 'invite' then
    if p_target_id is null or p_target_id=v_actor then raise exception 'INVALID_TARGET'; end if;
    if not exists (select 1 from public.guilds where id=p_guild_id and leader_id=v_actor) then raise exception 'LEADER_ONLY'; end if;
    if exists (select 1 from public.guild_members where player_id=p_target_id) then raise exception 'TARGET_ALREADY_IN_GUILD'; end if;
    insert into public.guild_invites(guild_id,invited_player_id,invited_by)
    values(p_guild_id,p_target_id,v_actor)
    on conflict (guild_id,invited_player_id) where status='pending'
    do update set invited_by=excluded.invited_by, created_at=now();
    return jsonb_build_object('status','invited','targetId',p_target_id);
  end if;

  if p_action in ('respond_accept','respond_decline') then
    select * into v_invite from public.guild_invites
      where id=p_invite_id and invited_player_id=v_actor and status='pending'
      for update;
    if not found then raise exception 'INVITE_NOT_FOUND'; end if;
    if p_action='respond_decline' then
      update public.guild_invites set status='declined',responded_at=now() where id=v_invite.id;
      return jsonb_build_object('status','declined');
    end if;
    if exists (select 1 from public.guilds where leader_id=v_actor) then raise exception 'LEADER_CANNOT_MOVE'; end if;
    delete from public.guild_members where player_id=v_actor;
    insert into public.guild_members(player_id,guild_id,role) values(v_actor,v_invite.guild_id,'member');
    update public.guild_invites set status='accepted',responded_at=now() where id=v_invite.id;
    update public.guild_invites set status='cancelled',responded_at=now()
      where invited_player_id=v_actor and status='pending' and id<>v_invite.id;
    return jsonb_build_object('status','joined','guildId',v_invite.guild_id);
  end if;

  if p_action = 'kick' then
    if not exists (select 1 from public.guilds where id=p_guild_id and leader_id=v_actor) then raise exception 'LEADER_ONLY'; end if;
    if p_target_id is null or p_target_id=v_actor then raise exception 'INVALID_TARGET'; end if;
    delete from public.guild_members where player_id=p_target_id and guild_id=p_guild_id and role<>'leader';
    if not found then raise exception 'MEMBER_NOT_FOUND'; end if;
    return jsonb_build_object('status','kicked','targetId',p_target_id);
  end if;

  if p_action = 'set_role' then
    if not exists (select 1 from public.guilds where id=p_guild_id and leader_id=v_actor) then raise exception 'LEADER_ONLY'; end if;
    if p_role not in ('officer','member') or p_target_id is null or p_target_id=v_actor then raise exception 'INVALID_ROLE_OR_TARGET'; end if;
    update public.guild_members set role=p_role where player_id=p_target_id and guild_id=p_guild_id and role<>'leader';
    if not found then raise exception 'MEMBER_NOT_FOUND'; end if;
    return jsonb_build_object('status','role_updated','targetId',p_target_id,'role',p_role);
  end if;

  if p_action = 'admin_set_leader' then
    if not private.admin_has_permission(v_actor,'guilds_manage') then raise exception 'FORBIDDEN'; end if;
    if not exists (select 1 from public.guilds where id=p_guild_id) then raise exception 'GUILD_NOT_FOUND'; end if;
    select leader_id into v_old_leader from public.guilds where id=p_guild_id for update;
    if p_target_id is null then
      update public.guilds set leader_id=null where id=p_guild_id;
      update public.guild_members set role='officer' where player_id=v_old_leader and guild_id=p_guild_id;
      return jsonb_build_object('status','leader_cleared','guildId',p_guild_id);
    end if;
    if not exists (select 1 from public.players where id=p_target_id and account_status<>'banned') then raise exception 'PLAYER_NOT_FOUND'; end if;
    update public.guilds set leader_id=null where leader_id=p_target_id and id<>p_guild_id;
    delete from public.guild_members where player_id=p_target_id;
    if v_old_leader is not null and v_old_leader<>p_target_id then
      update public.guild_members set role='officer' where player_id=v_old_leader and guild_id=p_guild_id;
    end if;
    insert into public.guild_members(player_id,guild_id,role)
      values(p_target_id,p_guild_id,'leader')
      on conflict(player_id) do update set guild_id=excluded.guild_id,role='leader',joined_at=now();
    update public.guilds set leader_id=p_target_id where id=p_guild_id;
    return jsonb_build_object('status','leader_set','guildId',p_guild_id,'leaderId',p_target_id);
  end if;

  raise exception 'INVALID_GUILD_ACTION';
end;
$function$;

CREATE OR REPLACE FUNCTION public.server_admin_access(p_actor_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_role text;
  v_permissions text[];
begin
  select am.role,
         case
           when am.role='owner' then array[
             'audit_users','moderate_users','economy_grant','economy_remove',
             'battlepass_grant','codes_manage','announcements_manage','events_manage',
             'maintenance_manage','guilds_manage'
           ]::text[]
           else coalesce(amp.permissions,'{}'::text[])
         end
  into v_role,v_permissions
  from public.admin_members am
  left join private.admin_member_permissions amp on amp.player_id=am.player_id
  where am.player_id=p_actor_id;

  if v_role is null then raise exception 'FORBIDDEN'; end if;

  return jsonb_build_object(
    'playerId',p_actor_id,
    'role',v_role,
    'isOwner',v_role='owner',
    'permissions',to_jsonb(v_permissions)
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.server_admin_account_audit(p_actor_id uuid, p_target_id uuid, p_pack_offset integer DEFAULT 0, p_pack_limit integer DEFAULT 25)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_offset integer := greatest(0,coalesce(p_pack_offset,0));
  v_limit integer := greatest(10,least(50,coalesce(p_pack_limit,25)));
  v_account jsonb;
  v_collection jsonb;
  v_pack_stats jsonb;
  v_pack_history jsonb;
  v_economy jsonb;
  v_activity jsonb;
  v_moderation jsonb;
  v_progression jsonb;
  v_social jsonb;
  v_flags jsonb := '[]'::jsonb;
  v_total_packs bigint := 0;
  v_max_per_minute integer := 0;
  v_packs_24h bigint := 0;
  v_legacy_special bigint := 0;
  v_admin_event_openings bigint := 0;
begin
  if not private.admin_has_permission(p_actor_id,'audit_users') then
    raise exception 'FORBIDDEN_AUDIT_USERS';
  end if;

  if not exists(select 1 from public.players where id=p_target_id) then
    raise exception 'PLAYER_NOT_FOUND';
  end if;

  select jsonb_build_object(
    'id',p.id,
    'username',p.username,
    'coins',p.coins,
    'diamonds',p.diamonds,
    'level',p.level,
    'xp',p.xp,
    'createdAt',p.created_at,
    'lastDailyClaimAt',p.last_daily_claim_at,
    'battleRating',p.battle_rating,
    'battleWins',p.battle_wins,
    'battleLosses',p.battle_losses,
    'battleStreak',p.battle_streak,
    'bestBattleStreak',p.best_battle_streak,
    'profileIcon',p.profile_icon,
    'equippedTitleId',p.equipped_title_id,
    'equippedFrameId',p.equipped_frame_id,
    'equippedBackgroundId',p.equipped_background_id,
    'accountStatus',p.account_status,
    'suspendedUntil',p.suspended_until,
    'moderationReason',p.moderation_reason,
    'warningCount',p.warning_count,
    'auth',jsonb_build_object(
      'email',u.email,
      'phone',u.phone,
      'createdAt',u.created_at,
      'updatedAt',u.updated_at,
      'lastSignInAt',u.last_sign_in_at,
      'confirmedAt',u.confirmed_at,
      'bannedUntil',u.banned_until,
      'deletedAt',u.deleted_at,
      'providers',coalesce(u.raw_app_meta_data->'providers','[]'::jsonb)
    ),
    'admin',case when am.player_id is null then null else jsonb_build_object(
      'role',am.role,
      'since',am.created_at,
      'permissions',case when am.role='owner'
        then to_jsonb(array[
          'audit_users','moderate_users','economy_grant','economy_remove',
          'battlepass_grant','codes_manage','announcements_manage','events_manage',
          'maintenance_manage','guilds_manage'
        ]::text[])
        else to_jsonb(coalesce(amp.permissions,'{}'::text[])) end
    ) end
  )
  into v_account
  from public.players p
  left join auth.users u on u.id=p.id
  left join public.admin_members am on am.player_id=p.id
  left join private.admin_member_permissions amp on amp.player_id=p.id
  where p.id=p_target_id;

  select jsonb_build_object(
    'uniqueCards',count(*) filter(where pc.quantity>0),
    'totalCopies',coalesce(sum(pc.quantity) filter(where pc.quantity>0),0),
    'duplicateCopies',coalesce(sum(greatest(pc.quantity-1,0)) filter(where pc.quantity>0),0),
    'marketValueUsd',coalesce(round(sum(pc.quantity*coalesce(c.market_price_usd,0)) filter(where pc.quantity>0),2),0),
    'pricedUniqueCards',count(*) filter(where pc.quantity>0 and c.market_price_usd>0),
    'mostValuableCards',(
      select coalesce(jsonb_agg(to_jsonb(top_card)),'[]'::jsonb)
      from (
        select c.id,c.pokemon_name as name,c.set_name,c.rarity,c.market_price_usd as "marketPriceUsd",
               pc2.quantity,c.image_small as image
        from public.player_cards pc2
        join public.cards c on c.id=pc2.card_id
        where pc2.player_id=p_target_id and pc2.quantity>0
        order by c.market_price_usd desc nulls last
        limit 12
      ) top_card
    )
  )
  into v_collection
  from public.player_cards pc
  join public.cards c on c.id=pc.card_id
  where pc.player_id=p_target_id;

  select count(*),
         count(*) filter(where opened_at>=now()-interval '24 hours')
  into v_total_packs,v_packs_24h
  from public.pack_openings
  where player_id=p_target_id;

  select coalesce(max(openings),0)::integer
  into v_max_per_minute
  from (
    select count(*)::integer openings
    from public.pack_openings
    where player_id=p_target_id
    group by date_trunc('minute',opened_at)
  ) per_minute;

  with rare_sets as (
    select c.set_id
    from public.cards c
    group by c.set_id
    having count(*)>0
       and count(*) filter(where public.rarity_tier(c.rarity)>=3)::numeric/count(*)>=0.80
  )
  select count(*)
  into v_legacy_special
  from public.pack_openings po
  join public.packs p on p.id=po.pack_id
  where po.player_id=p_target_id
    and po.opened_at < timestamptz '2026-08-29 15:20:00+00'
    and p.set_id in (select set_id from rare_sets);

  select count(*)
  into v_admin_event_openings
  from public.pack_openings po
  where po.player_id=p_target_id
    and exists (
      select 1
      from public.admin_game_events e
      where e.event_type='free_boosters'
        and po.opened_at>=e.starts_at
        and po.opened_at<=e.ends_at
    );

  v_pack_stats := jsonb_build_object(
    'total',v_total_packs,
    'last24h',v_packs_24h,
    'maxPerMinute',v_max_per_minute,
    'legacySpecialPricingOpenings',v_legacy_special,
    'adminAbuseEventOpenings',v_admin_event_openings,
    'offset',v_offset,
    'limit',v_limit,
    'hasMore',v_offset+v_limit<v_total_packs
  );

  select coalesce(jsonb_agg(to_jsonb(opening_row) order by opening_row."openedAt" desc),'[]'::jsonb)
  into v_pack_history
  from (
    select
      po.id,
      po.opened_at as "openedAt",
      p.id as "packId",
      p.name as "packName",
      p.set_id as "setId",
      p.currency,
      p.price as "currentPackPrice",
      jsonb_array_length(coalesce(po.cards_received,'[]'::jsonb)) as "cardCount",
      coalesce((
        select round(sum(coalesce(c.market_price_usd,0)),2)
        from jsonb_array_elements(coalesce(po.cards_received,'[]'::jsonb)) item
        left join public.cards c on c.id=item->>'id'
      ),0) as "currentValueUsd",
      po.cards_received as cards
    from public.pack_openings po
    left join public.packs p on p.id=po.pack_id
    where po.player_id=p_target_id
    order by po.opened_at desc
    offset v_offset
    limit v_limit
  ) opening_row;

  select jsonb_build_object(
    'adminCurrencyAdjustments',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."createdAt" desc),'[]'::jsonb)
      from (
        select 'coins'::text currency,id,amount,"balance_before" as "balanceBefore",
               "balance_after" as "balanceAfter",note,created_at as "createdAt",admin_id as "actorId"
        from public.admin_coin_adjustments where target_id=p_target_id
        union all
        select 'diamonds'::text currency,id,amount,"balance_before","balance_after",note,created_at,admin_id
        from public.admin_diamond_adjustments where target_id=p_target_id
        order by "createdAt" desc
        limit 60
      ) q
    ),
    'duplicateSales',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."createdAt" desc),'[]'::jsonb)
      from (
        select s.id,s.card_id as "cardId",c.pokemon_name as "cardName",s.quantity,
               s.unit_market_price_usd as "unitMarketPriceUsd",s.unit_coins as "unitCoins",
               s.total_coins as "totalCoins",s.created_at as "createdAt"
        from private.card_duplicate_sales s
        left join public.cards c on c.id=s.card_id
        where s.player_id=p_target_id
        order by s.created_at desc
        limit 50
      ) q
    ),
    'diamondExchanges',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."createdAt" desc),'[]'::jsonb)
      from (
        select id,diamonds,coins_spent as "coinsSpent",created_at as "createdAt"
        from public.diamond_exchange_log
        where player_id=p_target_id
        order by created_at desc
        limit 50
      ) q
    ),
    'codeRedemptions',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."redeemedAt" desc),'[]'::jsonb)
      from (
        select cr.code_id as "codeId",rc.code,cr.reward_snapshot as reward,
               cr.redeemed_at as "redeemedAt"
        from public.code_redemptions cr
        left join public.redeem_codes rc on rc.id=cr.code_id
        where cr.player_id=p_target_id
        order by cr.redeemed_at desc
        limit 50
      ) q
    )
  )
  into v_economy;

  select jsonb_build_object(
    'trades',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."updatedAt" desc),'[]'::jsonb)
      from (
        select t.id,t.status::text,t.sender_id as "senderId",sp.username as "senderUsername",
               t.receiver_id as "receiverId",rp.username as "receiverUsername",
               t.sender_confirmed as "senderConfirmed",t.receiver_confirmed as "receiverConfirmed",
               t.created_at as "createdAt",t.updated_at as "updatedAt"
        from public.trades t
        left join public.players sp on sp.id=t.sender_id
        left join public.players rp on rp.id=t.receiver_id
        where t.sender_id=p_target_id or t.receiver_id=p_target_id
        order by t.updated_at desc
        limit 40
      ) q
    ),
    'battles',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."updatedAt" desc),'[]'::jsonb)
      from (
        select b.id,b.mode,b.status,b.is_ranked as "isRanked",b.wager_coins as "wagerCoins",
               b.challenger_id as "challengerId",cp.username as "challengerUsername",
               b.opponent_id as "opponentId",op.username as "opponentUsername",
               b.winner_id as "winnerId",b.forfeited_by as "forfeitedBy",
               b.forfeit_rating_neutral as "forfeitRatingNeutral",
               b.created_at as "createdAt",b.updated_at as "updatedAt",b.completed_at as "completedAt"
        from public.battles b
        left join public.players cp on cp.id=b.challenger_id
        left join public.players op on op.id=b.opponent_id
        where b.challenger_id=p_target_id or b.opponent_id=p_target_id
        order by b.updated_at desc
        limit 40
      ) q
    )
  )
  into v_activity;

  select coalesce(jsonb_agg(to_jsonb(q) order by q."createdAt" desc),'[]'::jsonb)
  into v_moderation
  from (
    select a.id,a.action,a.reason,a.suspended_until as "suspendedUntil",
           a.created_at as "createdAt",a.admin_id as "actorId",p.username as "actorUsername"
    from public.admin_moderation_actions a
    left join public.players p on p.id=a.admin_id
    where a.target_id=p_target_id
    order by a.created_at desc
    limit 60
  ) q;

  select jsonb_build_object(
    'battlePass',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."updatedAt" desc),'[]'::jsonb)
      from (
        select season_id as "seasonId",xp,level,vip_unlocked as "vipUnlocked",
               vip_unlocked_at as "vipUnlockedAt",updated_at as "updatedAt"
        from public.battle_pass_player_progress
        where player_id=p_target_id
        order by updated_at desc
        limit 10
      ) q
    ),
    'battlePassClaims',(
      select coalesce(jsonb_agg(to_jsonb(q) order by q."claimedAt" desc),'[]'::jsonb)
      from (
        select season_id as "seasonId",level,track,reward,claimed_at as "claimedAt"
        from public.battle_pass_reward_claims
        where player_id=p_target_id
        order by claimed_at desc
        limit 40
      ) q
    ),
    'dailyMissions',(
      select jsonb_build_object(
        'rows',count(*),
        'claimed',count(*) filter(where claimed),
        'latestUpdate',max(updated_at)
      )
      from public.player_daily_missions
      where player_id=p_target_id
    ),
    'missionsV2',(
      select jsonb_build_object(
        'rows',count(*),
        'claimed',count(*) filter(where claimed),
        'latestUpdate',max(updated_at)
      )
      from public.player_missions_v2
      where player_id=p_target_id
    )
  )
  into v_progression;

  select jsonb_build_object(
    'guild',(
      select to_jsonb(q)
      from (
        select gm.guild_id as "guildId",g.name as "guildName",gm.role,gm.joined_at as "joinedAt"
        from public.guild_members gm
        join public.guilds g on g.id=gm.guild_id
        where gm.player_id=p_target_id
        limit 1
      ) q
    ),
    'acceptedFriends',(
      select count(*)
      from public.friendships f
      where f.status='accepted'
        and (f.requester_id=p_target_id or f.addressee_id=p_target_id)
    ),
    'guildBoosterClaims',(
      select count(*) from public.guild_collective_booster_claims where player_id=p_target_id
    ),
    'guildWeeklyRewards',(
      select jsonb_build_object(
        'claims',count(*),
        'coins',coalesce(sum(reward_coins),0),
        'diamonds',coalesce(sum(reward_diamonds),0)
      )
      from public.guild_weekly_reward_claims
      where player_id=p_target_id
    )
  )
  into v_social;

  if v_max_per_minute>=20 then
    v_flags := v_flags || jsonb_build_array(jsonb_build_object(
      'severity','high','code','PACK_BURST',
      'title','Muitas aberturas no mesmo minuto',
      'detail',v_max_per_minute||' boosters em um único minuto.'
    ));
  elsif v_max_per_minute>=10 then
    v_flags := v_flags || jsonb_build_array(jsonb_build_object(
      'severity','medium','code','PACK_BURST',
      'title','Ritmo alto de aberturas',
      'detail',v_max_per_minute||' boosters em um único minuto.'
    ));
  end if;

  if v_packs_24h>=250 then
    v_flags := v_flags || jsonb_build_array(jsonb_build_object(
      'severity','medium','code','PACK_VOLUME_24H',
      'title','Volume muito alto em 24h',
      'detail',v_packs_24h||' boosters nas últimas 24 horas.'
    ));
  end if;

  if v_legacy_special>0 then
    v_flags := v_flags || jsonb_build_array(jsonb_build_object(
      'severity','info','code','LEGACY_SPECIAL_PRICING',
      'title','Exposição a preços antigos de packs especiais',
      'detail',v_legacy_special||' abertura(s) de packs raros antes do rebalanceamento de 29/08.'
    ));
  end if;

  if v_admin_event_openings>0 then
    v_flags := v_flags || jsonb_build_array(jsonb_build_object(
      'severity','info','code','ADMIN_EVENT_OPENINGS',
      'title','Aberturas durante Admin Abuse',
      'detail',v_admin_event_openings||' abertura(s) ocorreram dentro de evento oficial de boosters.'
    ));
  end if;

  return jsonb_build_object(
    'generatedAt',now(),
    'account',v_account,
    'collection',v_collection,
    'packs',v_pack_stats,
    'packHistory',v_pack_history,
    'economy',v_economy,
    'activity',v_activity,
    'moderation',v_moderation,
    'progression',v_progression,
    'social',v_social,
    'flags',v_flags
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.server_owner_admin_team(p_actor_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_data jsonb;
begin
  if not exists (
    select 1 from public.admin_members
    where player_id=p_actor_id and role='owner'
  ) then
    raise exception 'OWNER_ONLY';
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
    'playerId',am.player_id,
    'username',p.username,
    'role',am.role,
    'createdAt',am.created_at,
    'permissions',case
      when am.role='owner' then to_jsonb(array[
        'audit_users','moderate_users','economy_grant','economy_remove',
        'battlepass_grant','codes_manage','announcements_manage','events_manage',
        'maintenance_manage','guilds_manage'
      ]::text[])
      else to_jsonb(coalesce(amp.permissions,'{}'::text[]))
    end,
    'permissionsUpdatedAt',amp.updated_at
  ) order by (am.role='owner') desc,am.created_at), '[]'::jsonb)
  into v_data
  from public.admin_members am
  join public.players p on p.id=am.player_id
  left join private.admin_member_permissions amp on amp.player_id=am.player_id;

  return v_data;
end;
$function$;

CREATE OR REPLACE FUNCTION public.server_owner_set_admin_access(p_actor_id uuid, p_target_id uuid, p_enabled boolean, p_permissions text[] DEFAULT '{}'::text[])
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_allowed constant text[] := array[
    'audit_users','moderate_users','economy_grant','economy_remove',
    'battlepass_grant','codes_manage','announcements_manage','events_manage',
    'maintenance_manage','guilds_manage'
  ]::text[];
  v_permissions text[];
  v_username text;
  v_action text;
begin
  if not exists (
    select 1 from public.admin_members
    where player_id=p_actor_id and role='owner'
  ) then
    raise exception 'OWNER_ONLY';
  end if;

  if p_target_id is null or p_target_id=p_actor_id then
    raise exception 'INVALID_ADMIN_TARGET';
  end if;

  select username into v_username
  from public.players
  where id=p_target_id;
  if v_username is null then raise exception 'PLAYER_NOT_FOUND'; end if;

  if exists (
    select 1 from public.admin_members
    where player_id=p_target_id and role='owner'
  ) then
    raise exception 'OWNER_IMMUTABLE';
  end if;

  select coalesce(array_agg(distinct permission order by permission),'{}'::text[])
  into v_permissions
  from unnest(coalesce(p_permissions,'{}'::text[])) permission
  where permission=any(v_allowed);

  if p_enabled then
    v_action := case
      when exists(select 1 from public.admin_members where player_id=p_target_id)
        then 'update_permissions'
      else 'grant_admin'
    end;

    insert into public.admin_members(player_id,role)
    values(p_target_id,'admin')
    on conflict(player_id) do update set role='admin';

    insert into private.admin_member_permissions(player_id,permissions,updated_by,updated_at)
    values(p_target_id,v_permissions,p_actor_id,now())
    on conflict(player_id) do update
      set permissions=excluded.permissions,
          updated_by=excluded.updated_by,
          updated_at=excluded.updated_at;
  else
    v_action := 'revoke_admin';
    delete from public.admin_members
    where player_id=p_target_id and role='admin';
    v_permissions := '{}'::text[];
  end if;

  insert into private.admin_access_audit(actor_id,target_id,action,permissions)
  values(p_actor_id,p_target_id,v_action,v_permissions);

  return jsonb_build_object(
    'targetId',p_target_id,
    'username',v_username,
    'enabled',p_enabled,
    'permissions',to_jsonb(v_permissions),
    'action',v_action
  );
end;
$function$;

revoke all on function private.admin_has_permission(uuid,text) from public,anon,authenticated;
grant execute on function private.admin_has_permission(uuid,text) to service_role;

revoke all on function public.server_admin_access(uuid) from public,anon,authenticated;
grant execute on function public.server_admin_access(uuid) to service_role;

revoke all on function public.server_owner_set_admin_access(uuid,uuid,boolean,text[]) from public,anon,authenticated;
grant execute on function public.server_owner_set_admin_access(uuid,uuid,boolean,text[]) to service_role;

revoke all on function public.server_owner_admin_team(uuid) from public,anon,authenticated;
grant execute on function public.server_owner_admin_team(uuid) to service_role;

revoke all on function public.server_admin_account_audit(uuid,uuid,integer,integer) from public,anon,authenticated;
grant execute on function public.server_admin_account_audit(uuid,uuid,integer,integer) to service_role;

update public.app_update_logs
set changes=(
  select array_agg(distinct item order by item)
  from unnest(changes || array[
    'Histórico de packs virtualizado e paginado para reduzir travamentos durante o scroll',
    'Nova auditoria administrativa completa de contas com histórico de packs, economia, coleção, batalhas, trocas, progressão e sinais de abuso',
    'Admins de confiança agora podem receber permissões granulares escolhidas pelo dono do jogo',
    'Admins delegados só visualizam e executam os controles administrativos que receberam'
  ]::text[]) item
)
where version='0.1.1 • OTA 28/08';
