-- Economy 2.0 sinks and guardrails. Applied to production as Supabase migration 20260831024233.

create table if not exists private.market_fee_log (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.market_listings(id) on delete cascade,
  offer_id uuid references public.market_offers(id) on delete set null,
  buyer_id uuid not null references public.players(id) on delete cascade,
  seller_id uuid not null references public.players(id) on delete cascade,
  gross_coins bigint not null check (gross_coins >= 0),
  fee_coins bigint not null check (fee_coins >= 0),
  seller_net_coins bigint not null check (seller_net_coins >= 0),
  sale_kind text not null check (sale_kind in ('listing','offer')),
  created_at timestamptz not null default now()
);

create index if not exists market_fee_log_created_idx on private.market_fee_log(created_at desc);
create index if not exists market_fee_log_seller_idx on private.market_fee_log(seller_id,created_at desc);

create or replace function private.duplicate_sale_coin_value(p_card_id text)
returns bigint
language sql
stable
set search_path=''
as $$
  with target as (
    select c.id,c.set_id,c.rarity,c.market_price_usd,
      private.duplicate_sale_base_value(c.market_price_usd) as base_coins,
      private.duplicate_sale_rarity_multiplier(c.rarity) as rarity_multiplier,
      private.duplicate_sale_drop_multiplier(c.id) as drop_multiplier
    from public.cards c where c.id=p_card_id
  ), calc as (
    select t.*,
      greatest(10,round((t.base_coins*t.rarity_multiplier*t.drop_multiplier)/10.0)*10)::bigint as raw_coins,
      (select min(ceil(p.price::numeric*1.5))::bigint
       from public.packs p where p.active=true and p.set_id=t.set_id and p.currency='coins') as coin_pack_cap
    from target t
  )
  select case
    when market_price_usd is null or market_price_usd<=0 then 0
    when coin_pack_cap is not null then least(raw_coins,coin_pack_cap)
    else raw_coins
  end
  from calc
$$;

create or replace function public.get_my_duplicate_sale_cards()
returns jsonb
language sql
security definer
set search_path=''
as $$
  with me as (select auth.uid() as player_id),
  owned as (
    select pc.quantity,c.id,c.pokemon_name,c.set_name,c.set_id,c.rarity,c.image_small,
      c.market_price_usd,c.market_price_source,public.rarity_tier(c.rarity) as rarity_tier,
      public.rarity_pull_weight(c.rarity) as rarity_weight
    from public.player_cards pc join public.cards c on c.id=pc.card_id cross join me
    where me.player_id is not null and pc.player_id=me.player_id and pc.quantity>1
  ),
  owned_sets as (select distinct set_id from owned),
  set_rare_totals as (
    select c.set_id,
      sum(public.rarity_pull_weight(c.rarity)) filter(where public.rarity_tier(c.rarity)>=3) as rare_weight_total
    from public.cards c join owned_sets s on s.set_id=c.set_id group by c.set_id
  ),
  set_caps as (
    select p.set_id,min(ceil(p.price::numeric*1.5))::bigint as coin_pack_cap
    from public.packs p join owned_sets s on s.set_id=p.set_id
    where p.active=true and p.currency='coins' group by p.set_id
  ),
  quoted as (
    select o.*,private.duplicate_sale_base_value(o.market_price_usd) as base_coins,
      private.duplicate_sale_rarity_multiplier(o.rarity) as rarity_multiplier,
      case when o.rarity_tier>=3 and rt.rare_weight_total>0 then o.rarity_weight/rt.rare_weight_total else null end as drop_chance,
      cap.coin_pack_cap
    from owned o left join set_rare_totals rt on rt.set_id=o.set_id left join set_caps cap on cap.set_id=o.set_id
  ),
  multiplied as (
    select q.*,
      case
        when rarity_tier<=1 then 0.80 when rarity_tier=2 then 0.90
        when drop_chance>=0.05 then 0.85 when drop_chance>=0.02 then 1.00
        when drop_chance>=0.01 then 1.10 when drop_chance>=0.005 then 1.20
        when drop_chance>=0.002 then 1.35 when drop_chance>=0.001 then 1.50
        when drop_chance>=0.0005 then 1.70 else 2.00 end::numeric as drop_multiplier
    from quoted q
  ),
  final_quotes as (
    select m.*,
      case when market_price_usd is null or market_price_usd<=0 then 0
        else least(greatest(10,round((base_coins*rarity_multiplier*drop_multiplier)/10.0)*10)::bigint,
          coalesce(coin_pack_cap,9223372036854775807::bigint))
      end as unit_coins
    from multiplied m
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'quantity',quantity,
    'cards',jsonb_build_object('id',id,'pokemon_name',pokemon_name,'set_name',set_name,'rarity',rarity,
      'image_small',image_small,'market_price_usd',market_price_usd,'market_price_source',market_price_source),
    'sale',jsonb_build_object('baseCoins',base_coins,'rarityTier',rarity_tier,'rarityMultiplier',rarity_multiplier,
      'dropChancePct',case when drop_chance is null then null else drop_chance*100 end,
      'dropMultiplier',drop_multiplier,'coinPackCap',coin_pack_cap,'unitCoins',unit_coins)
  ) order by unit_coins desc,market_price_usd desc nulls last,pokemon_name),'[]'::jsonb)
  from final_quotes
$$;
