-- Economy 2.0 sinks and guardrails. Applied to production as Supabase migration 20260831024233.

create table if not exists private.market_fee_log (
  id bigint generated by default as identity primary key,
  listing_id uuid not null references public.market_listings(id) on delete cascade,
  offer_id uuid references public.market_offers(id) on delete set null,
  buyer_id uuid not null references public.players(id) on delete cascade,
  seller_id uuid not null references public.players(id) on delete cascade,
  gross_coins bigint not null check (gross_coins >= 0),
  fee_coins bigint not null check (fee_coins >= 0),
  seller_net_coins bigint not null check (seller_net_coins >= 0),
  sale_kind text not null check (sale_kind in ('listing','offer')),
  created_at timestamptz not null default now()
);

create index if not exists market_fee_log_created_idx on private.market_fee_log(created_at desc);
create index if not exists market_fee_log_seller_idx on private.market_fee_log(seller_id,created_at desc);

create or replace function private.duplicate_sale_coin_value(p_card_id text)
returns bigint
language sql
stable
set search_path=''
as $$
  with target as (
    select c.id,c.set_id,c.rarity,c.market_price_usd,
      private.duplicate_sale_base_value(c.market_price_usd) as base_coins,
      private.duplicate_sale_rarity_multiplier(c.rarity) as rarity_multiplier,
      private.duplicate_sale_drop_multiplier(c.id) as drop_multiplier
    from public.cards c where c.id=p_card_id
  ), calc as (
    select t.*,
      greatest(10,round((t.base_coins*t.rarity_multiplier*t.drop_multiplier)/10.0)*10)::bigint as raw_coins,
      (select min(ceil(p.price::numeric*1.5))::bigint
       from public.packs p where p.active=true and p.set_id=t.set_id and p.currency='coins') as coin_pack_cap
    from target t
  )
  select case
    when market_price_usd is null or market_price_usd<=0 then 0
    when coin_pack_cap is not null then least(raw_coins,coin_pack_cap)
    else raw_coins
  end
  from calc
$$;

create or replace function public.get_my_duplicate_sale_cards()
returns jsonb
language sql
security definer
set search_path=''
as $$
  with me as (select auth.uid() as player_id),
  owned as (
    select pc.quantity,c.id,c.pokemon_name,c.set_name,c.set_id,c.rarity,c.image_small,
      c.market_price_usd,c.market_price_source,public.rarity_tier(c.rarity) as rarity_tier,
      public.rarity_pull_weight(c.rarity) as rarity_weight
    from public.player_cards pc join public.cards c on c.id=pc.card_id cross join me
    where me.player_id is not null and pc.player_id=me.player_id and pc.quantity>1
  ),
  owned_sets as (select distinct set_id from owned),
  set_rare_totals as (
    select c.set_id,
      sum(public.rarity_pull_weight(c.rarity)) filter(where public.rarity_tier(c.rarity)>=3) as rare_weight_total
    from public.cards c join owned_sets s on s.set_id=c.set_id group by c.set_id
  ),
  set_caps as (
    select p.set_id,min(ceil(p.price::numeric*1.5))::bigint as coin_pack_cap
    from public.packs p join owned_sets s on s.set_id=p.set_id
    where p.active=true and p.currency='coins' group by p.set_id
  ),
  quoted as (
    select o.*,private.duplicate_sale_base_value(o.market_price_usd) as base_coins,
      private.duplicate_sale_rarity_multiplier(o.rarity) as rarity_multiplier,
      case when o.rarity_tier>=3 and rt.rare_weight_total>0 then o.rarity_weight/rt.rare_weight_total else null end as drop_chance,
      cap.coin_pack_cap
    from owned o left join set_rare_totals rt on rt.set_id=o.set_id left join set_caps cap on cap.set_id=o.set_id
  ),
  multiplied as (
    select q.*,
      case
        when rarity_tier<=1 then 0.80 when rarity_tier=2 then 0.90
        when drop_chance>=0.05 then 0.85 when drop_chance>=0.02 then 1.00
        when drop_chance>=0.01 then 1.10 when drop_chance>=0.005 then 1.20
        when drop_chance>=0.002 then 1.35 when drop_chance>=0.001 then 1.50
        when drop_chance>=0.0005 then 1.70 else 2.00 end::numeric as drop_multiplier
    from quoted q
  ),
  final_quotes as (
    select m.*,
      case when market_price_usd is null or market_price_usd<=0 then 0
        else least(greatest(10,round((base_coins*rarity_multiplier*drop_multiplier)/10.0)*10)::bigint,
          coalesce(coin_pack_cap,9223372036854775807::bigint))
      end as unit_coins
    from multiplied m
  )
  select coalesce(jsonb_agg(jsonb_build_object(
    'quantity',quantity,
    'cards',jsonb_build_object('id',id,'pokemon_name',pokemon_name,'set_name',set_name,'rarity',rarity,
      'image_small',image_small,'market_price_usd',market_price_usd,'market_price_source',market_price_source),
    'sale',jsonb_build_object('baseCoins',base_coins,'rarityTier',rarity_tier,'rarityMultiplier',rarity_multiplier,
      'dropChancePct',case when drop_chance is null then null else drop_chance*100 end,
      'dropMultiplier',drop_multiplier,'coinPackCap',coin_pack_cap,'unitCoins',unit_coins)
  ) order by unit_coins desc,market_price_usd desc nulls last,pokemon_name),'[]'::jsonb)
  from final_quotes
$$;


create or replace function public.sell_duplicate_cards(p_card_id text,p_quantity integer default 1)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_player_id uuid:=auth.uid(); v_inventory integer; v_market_price numeric; v_rarity text;
  v_rarity_tier smallint; v_base_coins bigint; v_rarity_multiplier numeric;
  v_drop_chance numeric; v_drop_multiplier numeric; v_coin_pack_cap bigint;
  v_unit_coins bigint; v_total_coins bigint; v_new_balance bigint;
begin
  if v_player_id is null then raise exception 'UNAUTHENTICATED'; end if;
  if p_card_id is null or btrim(p_card_id)='' or p_quantity is null or p_quantity<1 or p_quantity>10000
    then raise exception 'INVALID_SALE'; end if;
  if exists(select 1 from public.app_runtime_status where id=1 and maintenance_enabled=true)
    then raise exception 'APP_MAINTENANCE'; end if;

  if exists(select 1 from public.admin_game_events
    where event_type='free_boosters' and active=true and starts_at<=now() and ends_at>now())
    then raise exception 'DUPLICATE_SALES_PAUSED_DURING_FREE_EVENT'; end if;

  perform 1 from public.players where id=v_player_id and account_status='active' for update;
  if not found then raise exception 'PLAYER_NOT_AVAILABLE'; end if;

  select pc.quantity,c.market_price_usd,c.rarity
  into v_inventory,v_market_price,v_rarity
  from public.player_cards pc join public.cards c on c.id=pc.card_id
  where pc.player_id=v_player_id and pc.card_id=p_card_id for update of pc;

  if not found then raise exception 'CARD_NOT_OWNED'; end if;
  if v_market_price is null or v_market_price<=0 then raise exception 'CARD_WITHOUT_MARKET_PRICE'; end if;
  if v_inventory<=1 then raise exception 'NO_DUPLICATES'; end if;
  if p_quantity>(v_inventory-1) then raise exception 'KEEP_ONE_COPY'; end if;

  v_rarity_tier:=public.rarity_tier(v_rarity);
  v_base_coins:=private.duplicate_sale_base_value(v_market_price);
  v_rarity_multiplier:=private.duplicate_sale_rarity_multiplier(v_rarity);
  v_drop_chance:=private.duplicate_sale_drop_chance(p_card_id);
  v_drop_multiplier:=private.duplicate_sale_drop_multiplier(p_card_id);
  select min(ceil(p.price::numeric*1.5))::bigint into v_coin_pack_cap
  from public.packs p join public.cards c on c.set_id=p.set_id
  where c.id=p_card_id and p.active=true and p.currency='coins';

  v_unit_coins:=private.duplicate_sale_coin_value(p_card_id);
  if v_unit_coins<=0 then raise exception 'CARD_WITHOUT_MARKET_PRICE'; end if;
  v_total_coins:=v_unit_coins*p_quantity;

  update public.player_cards set quantity=quantity-p_quantity
  where player_id=v_player_id and card_id=p_card_id;
  update public.players set coins=coins+v_total_coins where id=v_player_id returning coins into v_new_balance;

  insert into private.card_duplicate_sales(
    player_id,card_id,quantity,unit_market_price_usd,unit_coins,total_coins,
    rarity_tier,rarity_multiplier,drop_chance_pct,drop_multiplier,coin_pack_cap
  ) values(
    v_player_id,p_card_id,p_quantity,v_market_price,v_unit_coins,v_total_coins,
    v_rarity_tier,v_rarity_multiplier,case when v_drop_chance is null then null else v_drop_chance*100 end,
    v_drop_multiplier,v_coin_pack_cap
  );

  perform private.battle_pass_record_event(v_player_id,'market_sell',1);

  return jsonb_build_object('ok',true,'cardId',p_card_id,'quantitySold',p_quantity,
    'remainingQuantity',v_inventory-p_quantity,'marketPriceUsd',v_market_price,
    'baseCoins',v_base_coins,'rarityTier',v_rarity_tier,'rarityMultiplier',v_rarity_multiplier,
    'dropChancePct',case when v_drop_chance is null then null else v_drop_chance*100 end,
    'dropMultiplier',v_drop_multiplier,'coinPackCap',v_coin_pack_cap,'unitCoins',v_unit_coins,
    'coinsEarned',v_total_coins,'coins',v_new_balance);
end;
$$;

create or replace function private.marketplace_action(
  p_action text,p_listing_id uuid default null,p_card_id text default null,
  p_quantity integer default null,p_price bigint default null,p_shop_name text default null,
  p_theme_style text default null
)
returns jsonb
language plpgsql
security definer
set search_path=''
as $$
declare
  v_actor uuid:=auth.uid(); v_username text; v_name text; v_listing public.market_listings%rowtype;
  v_inventory integer; v_buyer_coins bigint; v_buyer_after bigint; v_seller_after bigint;
  v_fee bigint; v_seller_credit bigint;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;
  select username into v_username from public.players where id=v_actor and account_status='active';
  if not found then raise exception 'PLAYER_NOT_AVAILABLE'; end if;

  if p_action='save_shop' then
    v_name:=regexp_replace(trim(coalesce(p_shop_name,'')),'\s+',' ','g');
    if char_length(v_name)<3 or char_length(v_name)>32 then raise exception 'INVALID_SHOP_NAME'; end if;
    if coalesce(p_theme_style,'guild')<>all(array['guild','classic','night']) then raise exception 'INVALID_SHOP_THEME'; end if;
    insert into public.player_shops(player_id,name,theme_style)
    values(v_actor,v_name,coalesce(p_theme_style,'guild'))
    on conflict(player_id) do update set name=excluded.name,theme_style=excluded.theme_style,updated_at=now();
    return jsonb_build_object('ok',true,'shopName',v_name,'themeStyle',coalesce(p_theme_style,'guild'));
  end if;

  if p_action='list' then
    if p_card_id is null or p_quantity is null or p_quantity<1 or p_quantity>99
      or p_price is null or p_price<1 or p_price>100000000 then raise exception 'INVALID_LISTING'; end if;
    if (select count(*) from public.market_listings where seller_id=v_actor and status='active')>=100
      then raise exception 'LISTING_LIMIT_REACHED'; end if;
    insert into public.player_shops(player_id,name) values(v_actor,left(v_username||' Card Shop',32))
    on conflict(player_id) do nothing;
    select quantity into v_inventory from public.player_cards
    where player_id=v_actor and card_id=p_card_id for update;
    if not found or v_inventory<p_quantity then raise exception 'NOT_ENOUGH_CARDS'; end if;
    update public.player_cards set quantity=quantity-p_quantity where player_id=v_actor and card_id=p_card_id;
    insert into public.market_listings(seller_id,card_id,quantity,unit_price_coins)
    values(v_actor,p_card_id,p_quantity,p_price) returning * into v_listing;
    return jsonb_build_object('ok',true,'listingId',v_listing.id,'marketFeePercent',8);
  end if;

  if p_action='cancel' then
    select * into v_listing from public.market_listings where id=p_listing_id for update;
    if not found then raise exception 'LISTING_NOT_FOUND'; end if;
    if v_listing.seller_id<>v_actor then raise exception 'FORBIDDEN'; end if;
    if v_listing.status<>'active' then raise exception 'LISTING_NOT_ACTIVE'; end if;
    update public.market_listings set status='cancelled',updated_at=now() where id=v_listing.id;
    insert into public.player_cards(player_id,card_id,quantity)
    values(v_actor,v_listing.card_id,v_listing.quantity)
    on conflict(player_id,card_id) do update set quantity=public.player_cards.quantity+excluded.quantity;
    return jsonb_build_object('ok',true,'listingId',v_listing.id);
  end if;

  if p_action='buy' then
    select * into v_listing from public.market_listings where id=p_listing_id for update;
    if not found then raise exception 'LISTING_NOT_FOUND'; end if;
    if v_listing.status<>'active' then raise exception 'LISTING_NOT_ACTIVE'; end if;
    if v_listing.seller_id=v_actor then raise exception 'CANNOT_BUY_OWN_LISTING'; end if;

    perform 1 from public.players where id in (v_actor,v_listing.seller_id) order by id for update;
    select coins into v_buyer_coins from public.players where id=v_actor and account_status='active';
    if not found then raise exception 'PLAYER_NOT_AVAILABLE'; end if;
    if v_buyer_coins<v_listing.unit_price_coins then raise exception 'NOT_ENOUGH_COINS'; end if;

    v_fee:=least(v_listing.unit_price_coins,greatest(1,ceil(v_listing.unit_price_coins::numeric*.08)::bigint));
    v_seller_credit:=v_listing.unit_price_coins-v_fee;

    update public.players set coins=coins-v_listing.unit_price_coins where id=v_actor returning coins into v_buyer_after;
    update public.players set coins=coins+v_seller_credit where id=v_listing.seller_id returning coins into v_seller_after;
    insert into public.player_cards(player_id,card_id,quantity)
    values(v_actor,v_listing.card_id,v_listing.quantity)
    on conflict(player_id,card_id) do update set quantity=public.player_cards.quantity+excluded.quantity;
    update public.market_listings set status='sold',buyer_id=v_actor,sold_at=now(),updated_at=now() where id=v_listing.id;

    insert into private.market_fee_log(listing_id,buyer_id,seller_id,gross_coins,fee_coins,seller_net_coins,sale_kind)
    values(v_listing.id,v_actor,v_listing.seller_id,v_listing.unit_price_coins,v_fee,v_seller_credit,'listing');

    return jsonb_build_object('ok',true,'listingId',v_listing.id,'coins',v_buyer_after,
      'sellerCoins',v_seller_after,'quantity',v_listing.quantity,'cardId',v_listing.card_id,
      'marketFeeCoins',v_fee,'marketFeePercent',8,'sellerNetCoins',v_seller_credit);
  end if;

  raise exception 'INVALID_MARKETPLACE_ACTION';
end;
$$;
