-- Engagement expansion: market negotiation/history, Guild Wars,
-- collective Guild booster, tournament bracket, and unlockable profile cosmetics.

create table if not exists public.card_market_price_history (
  id bigint generated by default as identity primary key,
  card_id text not null references public.cards(id) on delete cascade,
  price_usd numeric(12,2) not null check(price_usd>=0),
  source text not null default 'tcgplayer',
  recorded_at timestamptz not null default now()
);
alter table public.card_market_price_history enable row level security;
grant select on public.card_market_price_history to authenticated;
drop policy if exists "price history readable" on public.card_market_price_history;
create policy "price history readable" on public.card_market_price_history for select to authenticated using (true);
create index if not exists card_market_price_history_card_time_idx on public.card_market_price_history(card_id,recorded_at desc);

create table if not exists public.market_offers (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.market_listings(id) on delete cascade,
  buyer_id uuid not null references public.players(id) on delete cascade,
  amount_coins bigint not null check(amount_coins>0),
  status text not null default 'pending' check(status in ('pending','accepted','rejected','cancelled','expired')),
  expires_at timestamptz not null default (now()+interval '24 hours'),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.market_offers enable row level security;
grant select on public.market_offers to authenticated;
drop policy if exists "market offers visible to participants" on public.market_offers;
create policy "market offers visible to participants" on public.market_offers for select to authenticated
using (
  buyer_id=(select auth.uid())
  or exists(select 1 from public.market_listings l where l.id=market_offers.listing_id and l.seller_id=(select auth.uid()))
);
create unique index if not exists market_offers_one_pending_per_buyer_idx on public.market_offers(listing_id,buyer_id) where status='pending';
create index if not exists market_offers_listing_idx on public.market_offers(listing_id);
create index if not exists market_offers_buyer_idx on public.market_offers(buyer_id);
create index if not exists market_offers_status_expiry_idx on public.market_offers(status,expires_at);

create table if not exists public.guild_wars (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  guild_a_id text not null references public.guilds(id) on delete cascade,
  guild_b_id text not null references public.guilds(id) on delete cascade,
  score_a integer not null default 0,
  score_b integer not null default 0,
  status text not null default 'active' check(status in ('active','completed')),
  winner_guild_id text references public.guilds(id) on delete set null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  created_at timestamptz not null default now(),
  check(guild_a_id<>guild_b_id),
  unique(week_start,guild_a_id,guild_b_id)
);
alter table public.guild_wars enable row level security;
grant select on public.guild_wars to authenticated;
drop policy if exists "guild wars readable" on public.guild_wars;
create policy "guild wars readable" on public.guild_wars for select to authenticated using (true);
create index if not exists guild_wars_active_idx on public.guild_wars(status,ends_at);
create index if not exists guild_wars_a_idx on public.guild_wars(guild_a_id,week_start desc);
create index if not exists guild_wars_b_idx on public.guild_wars(guild_b_id,week_start desc);
create index if not exists guild_wars_winner_idx on public.guild_wars(winner_guild_id);

create table if not exists public.guild_war_player_points (
  war_id uuid not null references public.guild_wars(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  guild_id text not null references public.guilds(id) on delete cascade,
  points integer not null default 0,
  wins integer not null default 0,
  matches integer not null default 0,
  updated_at timestamptz not null default now(),
  primary key(war_id,player_id)
);
alter table public.guild_war_player_points enable row level security;
grant select on public.guild_war_player_points to authenticated;
drop policy if exists "guild war points readable" on public.guild_war_player_points;
create policy "guild war points readable" on public.guild_war_player_points for select to authenticated using (true);
create index if not exists guild_war_player_points_guild_idx on public.guild_war_player_points(war_id,guild_id,points desc);
create index if not exists guild_war_player_points_guild_only_idx on public.guild_war_player_points(guild_id);
create index if not exists guild_war_player_points_player_idx on public.guild_war_player_points(player_id);

create table if not exists public.guild_collective_boosters (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guilds(id) on delete cascade,
  week_start date not null,
  progress integer not null default 0 check(progress>=0),
  target integer not null default 40 check(target>0),
  status text not null default 'building' check(status in ('building','ready')),
  ready_at timestamptz,
  created_at timestamptz not null default now(),
  unique(guild_id,week_start)
);
alter table public.guild_collective_boosters enable row level security;
grant select on public.guild_collective_boosters to authenticated;
drop policy if exists "guild collective boosters readable" on public.guild_collective_boosters;
create policy "guild collective boosters readable" on public.guild_collective_boosters for select to authenticated using (true);
create index if not exists guild_collective_boosters_week_idx on public.guild_collective_boosters(week_start desc,guild_id);

create table if not exists public.guild_collective_booster_claims (
  booster_id uuid not null references public.guild_collective_boosters(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  cards_received jsonb not null default '[]'::jsonb,
  claimed_at timestamptz not null default now(),
  primary key(booster_id,player_id)
);
alter table public.guild_collective_booster_claims enable row level security;
grant select on public.guild_collective_booster_claims to authenticated;
drop policy if exists "own collective booster claims readable" on public.guild_collective_booster_claims;
create policy "own collective booster claims readable" on public.guild_collective_booster_claims
for select to authenticated using ((select auth.uid())=player_id);
create index if not exists guild_collective_booster_claims_player_idx on public.guild_collective_booster_claims(player_id);

create table if not exists public.tournaments (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  status text not null default 'registration' check(status in ('registration','active','completed','cancelled')),
  max_players integer not null default 8 check(max_players=8),
  registration_ends_at timestamptz not null,
  starts_at timestamptz,
  ends_at timestamptz not null,
  winner_id uuid references public.players(id) on delete set null,
  reward_coins bigint not null default 100000,
  reward_diamonds integer not null default 5,
  created_at timestamptz not null default now()
);
alter table public.tournaments enable row level security;
grant select on public.tournaments to authenticated;
drop policy if exists "tournaments readable" on public.tournaments;
create policy "tournaments readable" on public.tournaments for select to authenticated using (true);
create index if not exists tournaments_status_idx on public.tournaments(status,registration_ends_at);
create index if not exists tournaments_winner_idx on public.tournaments(winner_id);

create table if not exists public.tournament_entries (
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  seed integer,
  joined_at timestamptz not null default now(),
  primary key(tournament_id,player_id)
);
alter table public.tournament_entries enable row level security;
grant select on public.tournament_entries to authenticated;
drop policy if exists "tournament entries readable" on public.tournament_entries;
create policy "tournament entries readable" on public.tournament_entries for select to authenticated using (true);
create index if not exists tournament_entries_player_idx on public.tournament_entries(player_id);

create table if not exists public.tournament_matches (
  id uuid primary key default gen_random_uuid(),
  tournament_id uuid not null references public.tournaments(id) on delete cascade,
  round_no integer not null check(round_no between 1 and 3),
  slot_no integer not null check(slot_no between 1 and 4),
  player_a_id uuid references public.players(id) on delete set null,
  player_b_id uuid references public.players(id) on delete set null,
  battle_id uuid references public.battles(id) on delete set null,
  winner_id uuid references public.players(id) on delete set null,
  status text not null default 'pending' check(status in ('pending','ready','playing','completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(tournament_id,round_no,slot_no)
);
alter table public.tournament_matches enable row level security;
grant select on public.tournament_matches to authenticated;
drop policy if exists "tournament matches readable" on public.tournament_matches;
create policy "tournament matches readable" on public.tournament_matches for select to authenticated using (true);
create index if not exists tournament_matches_battle_idx on public.tournament_matches(battle_id);
create index if not exists tournament_matches_players_idx on public.tournament_matches(tournament_id,round_no,slot_no);
create index if not exists tournament_matches_player_a_idx on public.tournament_matches(player_a_id);
create index if not exists tournament_matches_player_b_idx on public.tournament_matches(player_b_id);
create index if not exists tournament_matches_winner_idx on public.tournament_matches(winner_id);

create table if not exists public.cosmetic_definitions (
  id text primary key,
  kind text not null check(kind in ('frame','background')),
  name text not null,
  description text not null default '',
  icon text not null default 'sparkles',
  primary_color text not null default '#FFD447',
  secondary_color text not null default '#111827',
  unlock_type text not null,
  threshold integer not null default 0,
  unlock_key text,
  sort_order integer not null default 0,
  active boolean not null default true
);
alter table public.cosmetic_definitions enable row level security;
grant select on public.cosmetic_definitions to authenticated;
drop policy if exists "cosmetics readable" on public.cosmetic_definitions;
create policy "cosmetics readable" on public.cosmetic_definitions for select to authenticated using (active=true);

create table if not exists public.player_cosmetics (
  player_id uuid not null references public.players(id) on delete cascade,
  cosmetic_id text not null references public.cosmetic_definitions(id) on delete cascade,
  unlocked_at timestamptz not null default now(),
  primary key(player_id,cosmetic_id)
);
alter table public.player_cosmetics enable row level security;
grant select on public.player_cosmetics to authenticated;
drop policy if exists "own cosmetics readable" on public.player_cosmetics;
create policy "own cosmetics readable" on public.player_cosmetics for select to authenticated using ((select auth.uid())=player_id);
create index if not exists player_cosmetics_cosmetic_idx on public.player_cosmetics(cosmetic_id);

alter table public.players add column if not exists equipped_frame_id text references public.cosmetic_definitions(id) on delete set null;
alter table public.players add column if not exists equipped_background_id text references public.cosmetic_definitions(id) on delete set null;
create index if not exists players_equipped_frame_idx on public.players(equipped_frame_id);
create index if not exists players_equipped_background_idx on public.players(equipped_background_id);

insert into public.cosmetic_definitions(
  id,kind,name,description,icon,primary_color,secondary_color,unlock_type,threshold,unlock_key,sort_order,active
) values
('frame_classic','frame','Trainer Classic','Moldura inicial de todo treinador.','radio-button-on','#FFD447','#111827','default',0,null,10,true),
('frame_gold','frame','Gold League','Alcance 1.200 de ELO.','trophy','#F6C945','#3B2B08','rating',1200,null,20,true),
('frame_master','frame','Master Aura','Alcance 1.800 de ELO.','star','#B889FF','#24123D','rating',1800,null,30,true),
('frame_collector','frame','Collector 500','Tenha 500 cartas diferentes.','albums','#65D894','#123023','unique_cards',500,null,40,true),
('frame_guild','frame','Guild Vanguard','Faça parte de uma Guilda nível 3+.','shield','#68D9FF','#102C3A','guild_level',3,null,50,true),
('bg_midnight','background','Midnight Arena','Background inicial alternativo.','moon','#131824','#05070D','default',0,null,100,true),
('bg_kanto','background','Kanto Legacy','Complete a Pokédex de Kanto.','flame','#E84D5B','#35151B','pokedex_gen',1,'kanto',110,true),
('bg_johto','background','Johto Legacy','Complete a Pokédex de Johto.','leaf','#F0C84B','#30280E','pokedex_gen',2,'johto',120,true),
('bg_champion','background','Champion Hall','Vença 100 batalhas.','trophy','#FFD447','#2B2108','wins',100,null,130,true),
('bg_platinum','background','Platinum Season','Alcance 1.200 pontos em uma temporada.','diamond','#9CB6FF','#17203C','season_points',1200,null,140,true)
on conflict(id) do update set
kind=excluded.kind,name=excluded.name,description=excluded.description,icon=excluded.icon,
primary_color=excluded.primary_color,secondary_color=excluded.secondary_color,
unlock_type=excluded.unlock_type,threshold=excluded.threshold,unlock_key=excluded.unlock_key,
sort_order=excluded.sort_order,active=true;

CREATE OR REPLACE FUNCTION private.add_collective_booster_progress(p_player_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_guild text;
  v_id uuid;
begin
  select guild_id into v_guild from public.guild_members where player_id=p_player_id limit 1;
  if v_guild is null then return; end if;
  v_id:=private.ensure_guild_collective_booster(v_guild);

  update public.guild_collective_boosters
  set progress=least(target,progress+1),
      status=case when progress+1>=target then 'ready' else status end,
      ready_at=case when progress+1>=target and ready_at is null then now() else ready_at end
  where id=v_id and status='building';
end;
$function$;


CREATE OR REPLACE FUNCTION private.apply_guild_war_battle_progress()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_winner_guild text;
  v_loser uuid;
  v_loser_guild text;
  v_war public.guild_wars%rowtype;
begin
  if new.status<>'completed' or old.status='completed' or not new.is_ranked or new.winner_id is null then
    return new;
  end if;

  perform private.ensure_weekly_guild_wars();

  v_loser:=case when new.winner_id=new.challenger_id then new.opponent_id else new.challenger_id end;

  select guild_id into v_winner_guild
  from public.guild_members where player_id=new.winner_id limit 1;
  select guild_id into v_loser_guild
  from public.guild_members where player_id=v_loser limit 1;

  if v_winner_guild is null or v_loser_guild is null or v_winner_guild=v_loser_guild then
    return new;
  end if;

  select * into v_war
  from public.guild_wars
  where status='active'
    and starts_at<=now() and ends_at>now()
    and (
      (guild_a_id=v_winner_guild and guild_b_id=v_loser_guild)
      or (guild_b_id=v_winner_guild and guild_a_id=v_loser_guild)
    )
  order by starts_at desc
  limit 1
  for update;

  if v_war.id is null then return new; end if;

  if v_winner_guild=v_war.guild_a_id then
    update public.guild_wars set score_a=score_a+3 where id=v_war.id;
  else
    update public.guild_wars set score_b=score_b+3 where id=v_war.id;
  end if;

  if v_loser_guild=v_war.guild_a_id then
    update public.guild_wars set score_a=score_a+1 where id=v_war.id;
  else
    update public.guild_wars set score_b=score_b+1 where id=v_war.id;
  end if;

  insert into public.guild_war_player_points(war_id,player_id,guild_id,points,wins,matches)
  values(v_war.id,new.winner_id,v_winner_guild,3,1,1)
  on conflict(war_id,player_id) do update
  set points=public.guild_war_player_points.points+3,
      wins=public.guild_war_player_points.wins+1,
      matches=public.guild_war_player_points.matches+1,
      updated_at=now();

  insert into public.guild_war_player_points(war_id,player_id,guild_id,points,wins,matches)
  values(v_war.id,v_loser,v_loser_guild,1,0,1)
  on conflict(war_id,player_id) do update
  set points=public.guild_war_player_points.points+1,
      matches=public.guild_war_player_points.matches+1,
      updated_at=now();

  return new;
end;
$function$;


CREATE OR REPLACE FUNCTION private.apply_pack_guild_xp()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  update public.guilds g
  set xp=g.xp+1,level=greatest(g.level,1+floor((g.xp+1)/500.0)::integer)
  where g.id=(select gm.guild_id from public.guild_members gm where gm.player_id=new.player_id limit 1);

  perform private.add_collective_booster_progress(new.player_id);
  return new;
end;
$function$;


CREATE OR REPLACE FUNCTION private.apply_tournament_battle_result()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_match public.tournament_matches%rowtype;
  v_next_round integer;
  v_next_slot integer;
  v_next public.tournament_matches%rowtype;
  v_reward_coins bigint;
  v_reward_diamonds integer;
begin
  if new.status<>'completed' or old.status='completed' or new.winner_id is null then
    return new;
  end if;

  select * into v_match
  from public.tournament_matches
  where battle_id=new.id
  for update;
  if v_match.id is null then return new; end if;

  update public.tournament_matches
  set winner_id=new.winner_id,status='completed',updated_at=now()
  where id=v_match.id;

  if v_match.round_no=3 then
    update public.tournaments
    set status='completed',winner_id=new.winner_id
    where id=v_match.tournament_id and status='active'
    returning reward_coins,reward_diamonds into v_reward_coins,v_reward_diamonds;

    if found then
      update public.players
      set coins=coins+v_reward_coins,diamonds=diamonds+v_reward_diamonds
      where id=new.winner_id;

      perform public.server_queue_notification(
        new.winner_id,'tournament_champion','Você é campeão!',
        'Você venceu a Copa Trainer e recebeu 🪙 '||v_reward_coins||' + 💎 '||v_reward_diamonds||'.',
        jsonb_build_object('tournamentId',v_match.tournament_id,'coins',v_reward_coins,'diamonds',v_reward_diamonds)
      );
    end if;
    return new;
  end if;

  v_next_round:=v_match.round_no+1;
  v_next_slot:=ceil(v_match.slot_no/2.0)::integer;

  insert into public.tournament_matches(
    tournament_id,round_no,slot_no,
    player_a_id,player_b_id,status
  )
  values(
    v_match.tournament_id,v_next_round,v_next_slot,
    case when mod(v_match.slot_no,2)=1 then new.winner_id else null end,
    case when mod(v_match.slot_no,2)=0 then new.winner_id else null end,
    'pending'
  )
  on conflict(tournament_id,round_no,slot_no) do update
  set player_a_id=case
        when mod(v_match.slot_no,2)=1 then new.winner_id
        else public.tournament_matches.player_a_id
      end,
      player_b_id=case
        when mod(v_match.slot_no,2)=0 then new.winner_id
        else public.tournament_matches.player_b_id
      end,
      updated_at=now();

  select * into v_next
  from public.tournament_matches
  where tournament_id=v_match.tournament_id and round_no=v_next_round and slot_no=v_next_slot
  for update;

  if v_next.player_a_id is not null and v_next.player_b_id is not null and v_next.battle_id is null then
    update public.tournament_matches set status='ready' where id=v_next.id;
    perform private.create_tournament_match_battle(
      v_next.tournament_id,v_next.round_no,v_next.slot_no,v_next.player_a_id,v_next.player_b_id
    );
  end if;

  return new;
end;
$function$;


CREATE OR REPLACE FUNCTION private.cancel_market_offer(p_offer_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
  v_offer public.market_offers%rowtype;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;

  select * into v_offer from public.market_offers where id=p_offer_id for update;
  if not found then raise exception 'OFFER_NOT_FOUND'; end if;
  if v_offer.buyer_id<>v_actor then raise exception 'FORBIDDEN'; end if;
  if v_offer.status<>'pending' then raise exception 'OFFER_NOT_PENDING'; end if;

  update public.market_offers
  set status='cancelled',updated_at=now()
  where id=v_offer.id;

  return jsonb_build_object('id',v_offer.id,'status','cancelled');
end;
$function$;


CREATE OR REPLACE FUNCTION private.capture_card_market_price_history()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if new.market_price_usd is not null
     and old.market_price_usd is distinct from new.market_price_usd then
    insert into public.card_market_price_history(card_id,price_usd,source)
    values(new.id,new.market_price_usd,'tcgplayer');
  end if;
  return new;
end;
$function$;


CREATE OR REPLACE FUNCTION private.claim_guild_collective_booster()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_guild text;
  v_id uuid;
  v_booster public.guild_collective_boosters%rowtype;
  v_cards jsonb;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  select guild_id into v_guild from public.guild_members where player_id=v_player limit 1;
  if v_guild is null then raise exception 'NO_GUILD'; end if;

  v_id:=private.ensure_guild_collective_booster(v_guild);
  select * into v_booster from public.guild_collective_boosters where id=v_id for update;
  if v_booster.status<>'ready' then raise exception 'GUILD_BOOSTER_NOT_READY'; end if;
  if exists(select 1 from public.guild_collective_booster_claims where booster_id=v_id and player_id=v_player)
    then raise exception 'ALREADY_CLAIMED'; end if;

  with guaranteed as (
    select c.id,c.pokemon_name,c.rarity,c.image_small,c.image_large,
      coalesce(pc.quantity,0)>0 already_owned
    from public.cards c
    left join public.player_cards pc on pc.player_id=v_player and pc.card_id=c.id
    where public.rarity_tier(c.rarity)>=4
    order by (-ln(greatest(random(),0.0000001))/greatest(0.000001,public.rarity_pull_weight(c.rarity)))
    limit 1
  ), filler as (
    select c.id,c.pokemon_name,c.rarity,c.image_small,c.image_large,
      coalesce(pc.quantity,0)>0 already_owned
    from public.cards c
    left join public.player_cards pc on pc.player_id=v_player and pc.card_id=c.id
    where c.id not in(select id from guaranteed)
    order by (-ln(greatest(random(),0.0000001))/greatest(0.000001,public.rarity_pull_weight(c.rarity)))
    limit 4
  ), picked as (
    select * from guaranteed
    union all
    select * from filler
  ), upserted as (
    insert into public.player_cards(player_id,card_id,quantity)
    select v_player,id,1 from picked
    on conflict(player_id,card_id) do update set quantity=public.player_cards.quantity+1
    returning card_id
  )
  select jsonb_agg(jsonb_build_object(
    'id',id,'name',pokemon_name,'rarity',rarity,
    'image',coalesce(nullif(image_large,''),nullif(image_small,'')),
    'imageLarge',nullif(image_large,''),'imageSmall',nullif(image_small,''),
    'isNew',not already_owned,'wishlistHit',false
  ))
  into v_cards
  from picked;

  insert into public.guild_collective_booster_claims(booster_id,player_id,cards_received)
  values(v_id,v_player,coalesce(v_cards,'[]'::jsonb));

  perform public.server_refresh_player_achievements(v_player);

  return jsonb_build_object(
    'boosterId',v_id,'guildId',v_guild,'cards',coalesce(v_cards,'[]'::jsonb),'claimed',true
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.create_market_offer(p_listing_id uuid, p_amount bigint)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
  v_listing public.market_listings%rowtype;
  v_coins bigint;
  v_offer uuid;
  v_card_name text;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;
  if p_listing_id is null or p_amount is null or p_amount<1 or p_amount>100000000
    then raise exception 'INVALID_OFFER'; end if;

  update public.market_offers
  set status='expired',updated_at=now()
  where status='pending' and expires_at<=now();

  select * into v_listing
  from public.market_listings
  where id=p_listing_id
  for update;
  if not found then raise exception 'LISTING_NOT_FOUND'; end if;
  if v_listing.status<>'active' then raise exception 'LISTING_NOT_ACTIVE'; end if;
  if v_listing.seller_id=v_actor then raise exception 'CANNOT_OFFER_OWN_LISTING'; end if;

  select coins into v_coins
  from public.players
  where id=v_actor and account_status='active'
  for update;
  if not found then raise exception 'PLAYER_NOT_AVAILABLE'; end if;
  if v_coins<p_amount then raise exception 'NOT_ENOUGH_COINS'; end if;

  update public.market_offers
  set status='cancelled',updated_at=now()
  where listing_id=p_listing_id and buyer_id=v_actor and status='pending';

  insert into public.market_offers(listing_id,buyer_id,amount_coins)
  values(p_listing_id,v_actor,p_amount)
  returning id into v_offer;

  select pokemon_name into v_card_name from public.cards where id=v_listing.card_id;

  perform public.server_queue_notification(
    v_listing.seller_id,
    'market_offer',
    'Nova oferta no mercado',
    'Recebeu uma oferta de 🪙 '||p_amount||' por '||coalesce(v_card_name,'uma carta')||'.',
    jsonb_build_object('offerId',v_offer,'listingId',p_listing_id,'buyerId',v_actor,'amountCoins',p_amount)
  );

  return jsonb_build_object(
    'id',v_offer,'listingId',p_listing_id,'amountCoins',p_amount,
    'status','pending','expiresAt',now()+interval '24 hours'
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.create_tournament_match_battle(p_tournament uuid, p_round integer, p_slot integer, p_a uuid, p_b uuid)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_battle uuid;
begin
  if p_a is null or p_b is null then return null; end if;

  insert into public.battles(
    challenger_id,opponent_id,mode,stake_type,wager_coins,status,rounds_to_win,
    selection_seconds,selection_deadline,reward_eligible,is_ranked
  )
  values(
    p_a,p_b,'mystery','none',0,'selecting',2,90,now()+interval '24 hours',true,false
  )
  returning id into v_battle;

  insert into public.battle_events(battle_id,event_type,payload)
  values(v_battle,'tournament_started',jsonb_build_object(
    'tournamentId',p_tournament,'round',p_round,'slot',p_slot,'selectionSeconds',90
  ));

  update public.tournament_matches
  set battle_id=v_battle,status='playing',updated_at=now()
  where tournament_id=p_tournament and round_no=p_round and slot_no=p_slot;

  perform public.server_queue_notification(
    p_a,'tournament_match','Partida de torneio pronta!',
    'Sua próxima partida da Copa Trainer está disponível.',
    jsonb_build_object('battleId',v_battle,'tournamentId',p_tournament)
  );
  perform public.server_queue_notification(
    p_b,'tournament_match','Partida de torneio pronta!',
    'Sua próxima partida da Copa Trainer está disponível.',
    jsonb_build_object('battleId',v_battle,'tournamentId',p_tournament)
  );

  return v_battle;
end;
$function$;


CREATE OR REPLACE FUNCTION private.ensure_active_tournament()
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_id uuid;
  v_number integer;
begin
  update public.tournaments
  set status='cancelled'
  where status='registration' and registration_ends_at<=now()
    and (select count(*) from public.tournament_entries e where e.tournament_id=tournaments.id)<8;

  select id into v_id
  from public.tournaments
  where status in ('registration','active')
  order by created_at desc
  limit 1;

  if v_id is not null then return v_id; end if;

  select count(*)+1 into v_number from public.tournaments;

  insert into public.tournaments(
    name,status,registration_ends_at,starts_at,ends_at,reward_coins,reward_diamonds
  )
  values(
    'Copa Trainer #'||v_number,
    'registration',
    now()+interval '24 hours',
    null,
    now()+interval '7 days',
    100000,
    5
  )
  returning id into v_id;

  return v_id;
end;
$function$;


CREATE OR REPLACE FUNCTION private.ensure_guild_collective_booster(p_guild_id text)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_week date:=date_trunc('week',now())::date;
  v_id uuid;
begin
  if p_guild_id is null then return null; end if;
  insert into public.guild_collective_boosters(guild_id,week_start)
  values(p_guild_id,v_week)
  on conflict(guild_id,week_start) do nothing;

  select id into v_id
  from public.guild_collective_boosters
  where guild_id=p_guild_id and week_start=v_week;

  return v_id;
end;
$function$;


CREATE OR REPLACE FUNCTION private.ensure_weekly_guild_wars()
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_week date:=date_trunc('week',now())::date;
  v_cycle integer:=mod(extract(week from now())::integer,3);
  r record;
  v_winner text;
begin
  for r in
    select * from public.guild_wars
    where status='active' and ends_at<=now()
    for update
  loop
    v_winner:=case
      when r.score_a>r.score_b then r.guild_a_id
      when r.score_b>r.score_a then r.guild_b_id
      else null
    end;

    update public.guild_wars
    set status='completed',winner_guild_id=v_winner
    where id=r.id;

    if v_winner is not null then
      update public.guilds
      set xp=xp+100,
          level=greatest(level,1+floor((xp+100)/500.0)::integer)
      where id=v_winner;
    end if;
  end loop;

  if not (
    exists(select 1 from public.guilds where id='kanto') and
    exists(select 1 from public.guilds where id='johto') and
    exists(select 1 from public.guilds where id='hoenn') and
    exists(select 1 from public.guilds where id='sinnoh')
  ) then
    return;
  end if;

  if v_cycle=0 then
    insert into public.guild_wars(week_start,guild_a_id,guild_b_id,starts_at,ends_at)
    values
      (v_week,'kanto','johto',v_week::timestamptz,(v_week+7)::timestamptz),
      (v_week,'hoenn','sinnoh',v_week::timestamptz,(v_week+7)::timestamptz)
    on conflict(week_start,guild_a_id,guild_b_id) do nothing;
  elsif v_cycle=1 then
    insert into public.guild_wars(week_start,guild_a_id,guild_b_id,starts_at,ends_at)
    values
      (v_week,'kanto','hoenn',v_week::timestamptz,(v_week+7)::timestamptz),
      (v_week,'johto','sinnoh',v_week::timestamptz,(v_week+7)::timestamptz)
    on conflict(week_start,guild_a_id,guild_b_id) do nothing;
  else
    insert into public.guild_wars(week_start,guild_a_id,guild_b_id,starts_at,ends_at)
    values
      (v_week,'kanto','sinnoh',v_week::timestamptz,(v_week+7)::timestamptz),
      (v_week,'johto','hoenn',v_week::timestamptz,(v_week+7)::timestamptz)
    on conflict(week_start,guild_a_id,guild_b_id) do nothing;
  end if;
end;
$function$;


CREATE OR REPLACE FUNCTION private.equip_cosmetic(p_cosmetic_id text)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_kind text;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  perform private.refresh_player_cosmetics(v_player);

  select d.kind into v_kind
  from public.cosmetic_definitions d
  join public.player_cosmetics pc on pc.cosmetic_id=d.id and pc.player_id=v_player
  where d.id=p_cosmetic_id and d.active;
  if v_kind is null then raise exception 'COSMETIC_LOCKED'; end if;

  if v_kind='frame' then
    update public.players set equipped_frame_id=p_cosmetic_id where id=v_player;
  else
    update public.players set equipped_background_id=p_cosmetic_id where id=v_player;
  end if;

  return jsonb_build_object('id',p_cosmetic_id,'kind',v_kind,'equipped',true);
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_cosmetics_hub()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  perform private.refresh_player_cosmetics(v_player);

  return jsonb_build_object(
    'equippedFrameId',(select equipped_frame_id from public.players where id=v_player),
    'equippedBackgroundId',(select equipped_background_id from public.players where id=v_player),
    'items',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',d.id,'kind',d.kind,'name',d.name,'description',d.description,'icon',d.icon,
        'primaryColor',d.primary_color,'secondaryColor',d.secondary_color,
        'unlockType',d.unlock_type,'threshold',d.threshold,'unlockKey',d.unlock_key,
        'unlocked',pc.cosmetic_id is not null
      ) order by d.kind,d.sort_order)
      from public.cosmetic_definitions d
      left join public.player_cosmetics pc on pc.player_id=v_player and pc.cosmetic_id=d.id
      where d.active
    ),'[]'::jsonb)
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_guild_collective_booster_status()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_guild text;
  v_id uuid;
  v_booster public.guild_collective_boosters%rowtype;
  v_claimed boolean:=false;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  select guild_id into v_guild from public.guild_members where player_id=v_player limit 1;
  if v_guild is null then
    return jsonb_build_object('guildId',null,'status','none','progress',0,'target',40,'claimed',false,'claimable',false);
  end if;

  v_id:=private.ensure_guild_collective_booster(v_guild);
  select * into v_booster from public.guild_collective_boosters where id=v_id;

  select exists(
    select 1 from public.guild_collective_booster_claims
    where booster_id=v_id and player_id=v_player
  ) into v_claimed;

  return jsonb_build_object(
    'id',v_booster.id,'guildId',v_guild,'weekStart',v_booster.week_start,
    'progress',v_booster.progress,'target',v_booster.target,'status',v_booster.status,
    'readyAt',v_booster.ready_at,'claimed',v_claimed,
    'claimable',v_booster.status='ready' and not v_claimed
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_guild_wars()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
  v_my_guild text;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;
  perform private.ensure_weekly_guild_wars();

  select guild_id into v_my_guild from public.guild_members where player_id=v_actor limit 1;

  return jsonb_build_object(
    'myGuildId',v_my_guild,
    'wars',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',w.id,'weekStart',w.week_start,'status',w.status,
        'startsAt',w.starts_at,'endsAt',w.ends_at,
        'guildA',jsonb_build_object('id',ga.id,'name',ga.name,'color',ga.color,'score',w.score_a),
        'guildB',jsonb_build_object('id',gb.id,'name',gb.name,'color',gb.color,'score',w.score_b),
        'winnerGuildId',w.winner_guild_id,
        'contributors',coalesce((
          select jsonb_agg(jsonb_build_object(
            'playerId',x.player_id,'username',x.username,'guildId',x.guild_id,
            'points',x.points,'wins',x.wins,'matches',x.matches
          ) order by x.points desc,x.wins desc,x.username)
          from (
            select p.id player_id,p.username,gp.guild_id,gp.points,gp.wins,gp.matches
            from public.guild_war_player_points gp
            join public.players p on p.id=gp.player_id
            where gp.war_id=w.id
            order by gp.points desc,gp.wins desc,p.username
            limit 10
          ) x
        ),'[]'::jsonb)
      ) order by w.status,w.starts_at desc)
      from public.guild_wars w
      join public.guilds ga on ga.id=w.guild_a_id
      join public.guilds gb on gb.id=w.guild_b_id
      where w.ends_at>now()-interval '14 days'
    ),'[]'::jsonb)
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_market_offers()
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;

  return jsonb_build_object(
    'incoming',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',o.id,'listingId',o.listing_id,'amountCoins',o.amount_coins,'status',o.status,
        'expiresAt',o.expires_at,'createdAt',o.created_at,
        'buyerId',o.buyer_id,'buyerUsername',bp.username,
        'sellerId',l.seller_id,'sellerUsername',sp.username,
        'listingPrice',l.unit_price_coins,'quantity',l.quantity,
        'card',jsonb_build_object('id',c.id,'name',c.pokemon_name,'rarity',c.rarity,'image',coalesce(c.image_small,c.image_large))
      ) order by o.created_at desc)
      from public.market_offers o
      join public.market_listings l on l.id=o.listing_id
      join public.players bp on bp.id=o.buyer_id
      join public.players sp on sp.id=l.seller_id
      join public.cards c on c.id=l.card_id
      where l.seller_id=v_actor
        and o.created_at>=now()-interval '14 days'
    ),'[]'::jsonb),
    'outgoing',coalesce((
      select jsonb_agg(jsonb_build_object(
        'id',o.id,'listingId',o.listing_id,'amountCoins',o.amount_coins,'status',o.status,
        'expiresAt',o.expires_at,'createdAt',o.created_at,
        'buyerId',o.buyer_id,'buyerUsername',bp.username,
        'sellerId',l.seller_id,'sellerUsername',sp.username,
        'listingPrice',l.unit_price_coins,'quantity',l.quantity,
        'card',jsonb_build_object('id',c.id,'name',c.pokemon_name,'rarity',c.rarity,'image',coalesce(c.image_small,c.image_large))
      ) order by o.created_at desc)
      from public.market_offers o
      join public.market_listings l on l.id=o.listing_id
      join public.players bp on bp.id=o.buyer_id
      join public.players sp on sp.id=l.seller_id
      join public.cards c on c.id=l.card_id
      where o.buyer_id=v_actor
        and o.created_at>=now()-interval '14 days'
    ),'[]'::jsonb)
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_public_player_profile(p_player_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
  v_result jsonb;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;

  select jsonb_build_object(
    'player',jsonb_build_object(
      'id',p.id,'username',p.username,'profileIcon',p.profile_icon,'level',p.level,
      'battleWins',p.battle_wins,'battleLosses',p.battle_losses,'battleStreak',p.battle_streak,
      'battleRating',case when p.id=v_actor or p.show_battle_rating then p.battle_rating else null end,
      'showBattleRating',p.show_battle_rating,
      'equippedTitle',case when ad.id is null then null else jsonb_build_object('id',ad.id,'title',ad.title,'icon',ad.icon) end,
      'guild',case when g.id is null then null else jsonb_build_object(
        'id',g.id,'name',g.name,'color',g.color,'role',gm.role,'level',g.level,'xp',g.xp
      ) end,
      'frame',case when frame.id is null then null else jsonb_build_object(
        'id',frame.id,'name',frame.name,'primaryColor',frame.primary_color,'secondaryColor',frame.secondary_color,'icon',frame.icon
      ) end,
      'background',case when bg.id is null then null else jsonb_build_object(
        'id',bg.id,'name',bg.name,'primaryColor',bg.primary_color,'secondaryColor',bg.secondary_color,'icon',bg.icon
      ) end
    ),
    'collection',jsonb_build_object(
      'uniqueCards',(select count(*) from public.player_cards pc where pc.player_id=p.id and pc.quantity>0),
      'totalCopies',(select coalesce(sum(pc.quantity),0) from public.player_cards pc where pc.player_id=p.id and pc.quantity>0),
      'totalValueUsd',(select coalesce(sum(pc.quantity*coalesce(c.market_price_usd,0)),0)::numeric(14,2)
        from public.player_cards pc join public.cards c on c.id=pc.card_id
        where pc.player_id=p.id and pc.quantity>0),
      'rarestCards',coalesce((
        select jsonb_agg(to_jsonb(r) order by r.rarity_tier desc,r."marketPriceUsd" desc nulls last,r.name)
        from (
          select c.id,c.pokemon_name name,c.set_name "setName",c.rarity,c.image_small "imageSmall",
            c.image_large "imageLarge",c.market_price_usd "marketPriceUsd",pc.quantity,
            public.rarity_tier(c.rarity) rarity_tier
          from public.player_cards pc join public.cards c on c.id=pc.card_id
          where pc.player_id=p.id and pc.quantity>0
          order by public.rarity_tier(c.rarity) desc,c.market_price_usd desc nulls last,
            pc.quantity desc,c.pokemon_name
          limit 12
        ) r
      ),'[]'::jsonb),
      'showcase',coalesce((
        select jsonb_agg(jsonb_build_object(
          'slot',s.slot,'id',c.id,'name',c.pokemon_name,'setName',c.set_name,
          'rarity',c.rarity,'imageSmall',c.image_small,'imageLarge',c.image_large,
          'marketPriceUsd',c.market_price_usd
        ) order by s.slot)
        from public.profile_showcase s
        join public.cards c on c.id=s.card_id
        where s.player_id=p.id
      ),'[]'::jsonb)
    )
  ) into v_result
  from public.players p
  left join public.achievement_definitions ad on ad.id=p.equipped_title_id
  left join public.guild_members gm on gm.player_id=p.id
  left join public.guilds g on g.id=gm.guild_id
  left join public.cosmetic_definitions frame on frame.id=p.equipped_frame_id
  left join public.cosmetic_definitions bg on bg.id=p.equipped_background_id
  where p.id=p_player_id and p.account_status<>'banned';

  if v_result is null then raise exception 'PLAYER_NOT_FOUND'; end if;
  return v_result;
end;
$function$;


CREATE OR REPLACE FUNCTION private.get_tournament_hub()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
  v_id uuid;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;
  v_id:=private.ensure_active_tournament();

  return (
    select jsonb_build_object(
      'id',t.id,'name',t.name,'status',t.status,
      'registrationEndsAt',t.registration_ends_at,'startsAt',t.starts_at,'endsAt',t.ends_at,
      'maxPlayers',t.max_players,'rewardCoins',t.reward_coins,'rewardDiamonds',t.reward_diamonds,
      'winnerId',t.winner_id,
      'joined',exists(select 1 from public.tournament_entries e where e.tournament_id=t.id and e.player_id=v_actor),
      'entries',coalesce((
        select jsonb_agg(jsonb_build_object(
          'playerId',e.player_id,'username',p.username,'seed',e.seed,'rating',p.battle_rating,'joinedAt',e.joined_at
        ) order by coalesce(e.seed,999),e.joined_at)
        from public.tournament_entries e join public.players p on p.id=e.player_id
        where e.tournament_id=t.id
      ),'[]'::jsonb),
      'matches',coalesce((
        select jsonb_agg(jsonb_build_object(
          'id',m.id,'round',m.round_no,'slot',m.slot_no,'status',m.status,'battleId',m.battle_id,
          'playerA',case when pa.id is null then null else jsonb_build_object('id',pa.id,'username',pa.username) end,
          'playerB',case when pb.id is null then null else jsonb_build_object('id',pb.id,'username',pb.username) end,
          'winnerId',m.winner_id
        ) order by m.round_no,m.slot_no)
        from public.tournament_matches m
        left join public.players pa on pa.id=m.player_a_id
        left join public.players pb on pb.id=m.player_b_id
        where m.tournament_id=t.id
      ),'[]'::jsonb)
    )
    from public.tournaments t where t.id=v_id
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.join_tournament()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_tournament uuid;
  v_count integer;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  if not exists(select 1 from public.players where id=v_player and account_status='active')
    then raise exception 'PLAYER_NOT_AVAILABLE'; end if;

  v_tournament:=private.ensure_active_tournament();

  perform 1 from public.tournaments
  where id=v_tournament and status='registration' and registration_ends_at>now()
  for update;
  if not found then raise exception 'REGISTRATION_CLOSED'; end if;

  insert into public.tournament_entries(tournament_id,player_id)
  values(v_tournament,v_player)
  on conflict(tournament_id,player_id) do nothing;

  select count(*) into v_count from public.tournament_entries where tournament_id=v_tournament;
  if v_count>8 then
    delete from public.tournament_entries where tournament_id=v_tournament and player_id=v_player;
    raise exception 'TOURNAMENT_FULL';
  end if;

  if v_count=8 then
    perform private.start_tournament(v_tournament);
  end if;

  return jsonb_build_object('tournamentId',v_tournament,'joined',true,'entries',v_count,'maxPlayers',8);
end;
$function$;


CREATE OR REPLACE FUNCTION private.leave_tournament()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_player uuid:=auth.uid();
  v_tournament uuid;
begin
  if v_player is null then raise exception 'UNAUTHORIZED'; end if;
  select id into v_tournament
  from public.tournaments
  where status='registration'
  order by created_at desc limit 1;
  if v_tournament is null then raise exception 'NO_OPEN_TOURNAMENT'; end if;

  delete from public.tournament_entries
  where tournament_id=v_tournament and player_id=v_player;

  return jsonb_build_object('tournamentId',v_tournament,'joined',false);
end;
$function$;


CREATE OR REPLACE FUNCTION private.refresh_player_cosmetics(p_player uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  p public.players%rowtype;
  d public.cosmetic_definitions%rowtype;
  v_ok boolean;
  v_count integer;
  v_guild_level integer;
  v_min integer;
  v_max integer;
  v_target integer;
begin
  select * into p from public.players where id=p_player;
  if p.id is null then return; end if;

  select g.level into v_guild_level
  from public.guild_members gm join public.guilds g on g.id=gm.guild_id
  where gm.player_id=p_player limit 1;
  v_guild_level:=coalesce(v_guild_level,0);

  for d in select * from public.cosmetic_definitions where active order by sort_order loop
    v_ok:=false;

    if d.unlock_type='default' then
      v_ok:=true;
    elsif d.unlock_type='level' then
      v_ok:=p.level>=d.threshold;
    elsif d.unlock_type='rating' then
      v_ok:=p.battle_rating>=d.threshold;
    elsif d.unlock_type='wins' then
      v_ok:=p.battle_wins>=d.threshold;
    elsif d.unlock_type='guild_level' then
      v_ok:=v_guild_level>=d.threshold;
    elsif d.unlock_type='unique_cards' then
      select count(*) into v_count from public.player_cards where player_id=p_player and quantity>0;
      v_ok:=v_count>=d.threshold;
    elsif d.unlock_type='season_points' then
      select coalesce(max(points),0) into v_count from public.player_seasons where player_id=p_player;
      v_ok:=v_count>=d.threshold;
    elsif d.unlock_type='pokedex_gen' then
      if d.threshold=1 then v_min:=1;v_max:=151;
      elsif d.threshold=2 then v_min:=152;v_max:=251;
      elsif d.threshold=3 then v_min:=252;v_max:=386;
      elsif d.threshold=4 then v_min:=387;v_max:=493;
      elsif d.threshold=5 then v_min:=494;v_max:=649;
      elsif d.threshold=6 then v_min:=650;v_max:=721;
      elsif d.threshold=7 then v_min:=722;v_max:=809;
      elsif d.threshold=8 then v_min:=810;v_max:=905;
      else v_min:=906;v_max:=1025;
      end if;
      v_target:=v_max-v_min+1;
      select count(distinct n) into v_count
      from public.player_cards pc
      join public.cards c on c.id=pc.card_id
      cross join lateral unnest(coalesce(c.pokedex_numbers,array[]::integer[])) n
      where pc.player_id=p_player and pc.quantity>0 and n between v_min and v_max;
      v_ok:=v_count>=v_target;
    end if;

    if v_ok then
      insert into public.player_cosmetics(player_id,cosmetic_id)
      values(p_player,d.id)
      on conflict do nothing;
    end if;
  end loop;

  if p.equipped_frame_id is null then
    update public.players set equipped_frame_id='frame_classic' where id=p_player;
  end if;
  if p.equipped_background_id is null then
    update public.players set equipped_background_id='bg_midnight' where id=p_player;
  end if;
end;
$function$;


CREATE OR REPLACE FUNCTION private.respond_market_offer(p_offer_id uuid, p_accept boolean)
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_actor uuid:=auth.uid();
  v_offer public.market_offers%rowtype;
  v_listing public.market_listings%rowtype;
  v_buyer_coins bigint;
  v_buyer_after bigint;
  v_seller_after bigint;
  v_card_name text;
begin
  if v_actor is null then raise exception 'UNAUTHORIZED'; end if;

  select * into v_offer
  from public.market_offers
  where id=p_offer_id
  for update;
  if not found then raise exception 'OFFER_NOT_FOUND'; end if;

  select * into v_listing
  from public.market_listings
  where id=v_offer.listing_id
  for update;
  if not found then raise exception 'LISTING_NOT_FOUND'; end if;
  if v_listing.seller_id<>v_actor then raise exception 'FORBIDDEN'; end if;
  if v_offer.status<>'pending' then raise exception 'OFFER_NOT_PENDING'; end if;

  if v_offer.expires_at<=now() then
    update public.market_offers set status='expired',updated_at=now() where id=v_offer.id;
    raise exception 'OFFER_EXPIRED';
  end if;

  select pokemon_name into v_card_name from public.cards where id=v_listing.card_id;

  if not coalesce(p_accept,false) then
    update public.market_offers
    set status='rejected',updated_at=now()
    where id=v_offer.id;

    perform public.server_queue_notification(
      v_offer.buyer_id,'market_offer_rejected','Oferta recusada',
      'Sua oferta por '||coalesce(v_card_name,'uma carta')||' foi recusada.',
      jsonb_build_object('offerId',v_offer.id,'listingId',v_listing.id)
    );

    return jsonb_build_object('id',v_offer.id,'status','rejected');
  end if;

  if v_listing.status<>'active' then raise exception 'LISTING_NOT_ACTIVE'; end if;

  perform 1 from public.players
  where id in (v_offer.buyer_id,v_actor)
  order by id
  for update;

  select coins into v_buyer_coins
  from public.players
  where id=v_offer.buyer_id and account_status='active';
  if not found then raise exception 'BUYER_NOT_AVAILABLE'; end if;
  if v_buyer_coins<v_offer.amount_coins then raise exception 'BUYER_NOT_ENOUGH_COINS'; end if;

  update public.players
  set coins=coins-v_offer.amount_coins
  where id=v_offer.buyer_id
  returning coins into v_buyer_after;

  update public.players
  set coins=coins+v_offer.amount_coins
  where id=v_actor
  returning coins into v_seller_after;

  insert into public.player_cards(player_id,card_id,quantity)
  values(v_offer.buyer_id,v_listing.card_id,v_listing.quantity)
  on conflict(player_id,card_id)
  do update set quantity=public.player_cards.quantity+excluded.quantity;

  update public.market_listings
  set status='sold',buyer_id=v_offer.buyer_id,sold_at=now(),updated_at=now()
  where id=v_listing.id;

  update public.market_offers
  set status=case when id=v_offer.id then 'accepted' else 'rejected' end,
      updated_at=now()
  where listing_id=v_listing.id and status='pending';

  perform public.server_queue_notification(
    v_offer.buyer_id,'market_offer_accepted','Oferta aceita!',
    'Sua oferta por '||coalesce(v_card_name,'uma carta')||' foi aceita. A carta já está na sua Bag.',
    jsonb_build_object('offerId',v_offer.id,'listingId',v_listing.id,'cardId',v_listing.card_id,'amountCoins',v_offer.amount_coins)
  );

  return jsonb_build_object(
    'id',v_offer.id,'status','accepted','listingId',v_listing.id,
    'cardId',v_listing.card_id,'quantity',v_listing.quantity,
    'amountCoins',v_offer.amount_coins,'buyerCoins',v_buyer_after,'sellerCoins',v_seller_after
  );
end;
$function$;


CREATE OR REPLACE FUNCTION private.start_tournament(p_tournament uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare
  v_players uuid[];
  v_count integer;
  i integer;
begin
  select count(*) into v_count
  from public.tournament_entries
  where tournament_id=p_tournament;

  if v_count<>8 then return; end if;

  update public.tournaments
  set status='active',starts_at=coalesce(starts_at,now())
  where id=p_tournament and status='registration';

  if not found then return; end if;

  select array_agg(player_id order by random())
  into v_players
  from public.tournament_entries
  where tournament_id=p_tournament;

  for i in 1..8 loop
    update public.tournament_entries
    set seed=i
    where tournament_id=p_tournament and player_id=v_players[i];
  end loop;

  for i in 1..4 loop
    insert into public.tournament_matches(
      tournament_id,round_no,slot_no,player_a_id,player_b_id,status
    )
    values(
      p_tournament,1,i,v_players[(i-1)*2+1],v_players[(i-1)*2+2],'ready'
    )
    on conflict(tournament_id,round_no,slot_no) do nothing;

    perform private.create_tournament_match_battle(
      p_tournament,1,i,v_players[(i-1)*2+1],v_players[(i-1)*2+2]
    );
  end loop;
end;
$function$;


CREATE OR REPLACE FUNCTION public.cancel_market_offer(p_offer_id uuid)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.cancel_market_offer(p_offer_id); $function$;


CREATE OR REPLACE FUNCTION public.claim_guild_collective_booster()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.claim_guild_collective_booster(); $function$;


CREATE OR REPLACE FUNCTION public.create_market_offer(p_listing_id uuid, p_amount bigint)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.create_market_offer(p_listing_id,p_amount); $function$;


CREATE OR REPLACE FUNCTION public.equip_cosmetic(p_cosmetic_id text)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.equip_cosmetic(p_cosmetic_id); $function$;


CREATE OR REPLACE FUNCTION public.get_cosmetics_hub()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.get_cosmetics_hub(); $function$;


CREATE OR REPLACE FUNCTION public.get_guild_collective_booster_status()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.get_guild_collective_booster_status(); $function$;


CREATE OR REPLACE FUNCTION public.get_guild_wars()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.get_guild_wars(); $function$;


CREATE OR REPLACE FUNCTION public.get_market_offers()
 RETURNS jsonb
 LANGUAGE sql
 STABLE
 SET search_path TO ''
AS $function$ select private.get_market_offers(); $function$;


CREATE OR REPLACE FUNCTION public.get_tournament_hub()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.get_tournament_hub(); $function$;


CREATE OR REPLACE FUNCTION public.join_tournament()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.join_tournament(); $function$;


CREATE OR REPLACE FUNCTION public.leave_tournament()
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.leave_tournament(); $function$;


CREATE OR REPLACE FUNCTION public.respond_market_offer(p_offer_id uuid, p_accept boolean)
 RETURNS jsonb
 LANGUAGE sql
 SET search_path TO ''
AS $function$ select private.respond_market_offer(p_offer_id,p_accept); $function$;


CREATE OR REPLACE FUNCTION public.server_background_tick()
 RETURNS jsonb
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_battles integer;
  v_push integer;
  v_catalog jsonb;
  v_market_pending integer;
  v_restored_suspensions integer;
  v_season text;
begin
  update public.players
  set account_status='active',suspended_until=null,moderation_reason=null
  where account_status='suspended'
    and suspended_until is not null and suspended_until<=now();
  get diagnostics v_restored_suspensions=row_count;

  v_season:=private.ensure_active_season();

  perform private.ensure_weekly_guild_wars();
  perform private.ensure_active_tournament();

  update public.market_offers
  set status='expired',updated_at=now()
  where status='pending' and expires_at<=now();

  v_battles:=public.server_process_expired_battles();
  v_push:=public.server_dispatch_push_notifications();

  if exists(select 1 from public.catalog_refresh_state where job_name='full_tcg_refresh' and status='running') then
    begin
      v_catalog:=public.server_refresh_catalog_batch(2);
    exception when others then
      v_catalog:=jsonb_build_object('error',sqlerrm);
    end;
  else
    v_catalog:=jsonb_build_object('status','idle');
  end if;

  select count(*)::integer into v_market_pending
  from private.market_price_sync_sets
  where status in ('pending','running','retry');

  return jsonb_build_object(
    'battles',v_battles,'pushes',v_push,'catalog',v_catalog,
    'season',v_season,
    'guildWars','checked',
    'tournaments','checked',
    'moderation',jsonb_build_object('restoredSuspensions',v_restored_suspensions),
    'marketPrices',jsonb_build_object(
      'status',case when v_market_pending>0 then 'syncing' else 'ready' end,
      'pendingSets',v_market_pending,'source','pokemontcg:tcgplayer_market_v3'
    ),
    'at',now()
  );
end;
$function$;


drop trigger if exists trg_capture_card_market_price_history on public.cards;
create trigger trg_capture_card_market_price_history
after update of market_price_usd on public.cards
for each row execute function private.capture_card_market_price_history();

drop trigger if exists trg_guild_war_battle_progress on public.battles;
create trigger trg_guild_war_battle_progress
after update of status on public.battles
for each row execute function private.apply_guild_war_battle_progress();

drop trigger if exists trg_pack_guild_xp on public.pack_openings;
create trigger trg_pack_guild_xp
after insert on public.pack_openings
for each row execute function private.apply_pack_guild_xp();

drop trigger if exists trg_tournament_battle_result on public.battles;
create trigger trg_tournament_battle_result
after update of status on public.battles
for each row execute function private.apply_tournament_battle_result();

insert into public.card_market_price_history(card_id,price_usd,source,recorded_at)
select c.id,c.market_price_usd,'tcgplayer',now()
from public.cards c
where c.market_price_usd is not null
  and not exists(select 1 from public.card_market_price_history h where h.card_id=c.id);

do $engagement_realtime$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='market_offers') then alter publication supabase_realtime add table public.market_offers; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='card_market_price_history') then alter publication supabase_realtime add table public.card_market_price_history; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='guild_wars') then alter publication supabase_realtime add table public.guild_wars; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='guild_war_player_points') then alter publication supabase_realtime add table public.guild_war_player_points; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='guild_collective_boosters') then alter publication supabase_realtime add table public.guild_collective_boosters; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='guild_collective_booster_claims') then alter publication supabase_realtime add table public.guild_collective_booster_claims; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='tournaments') then alter publication supabase_realtime add table public.tournaments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='tournament_entries') then alter publication supabase_realtime add table public.tournament_entries; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='tournament_matches') then alter publication supabase_realtime add table public.tournament_matches; end if;
end
$engagement_realtime$;

revoke all on function private.create_market_offer(uuid,bigint) from public,anon;
grant execute on function private.create_market_offer(uuid,bigint) to authenticated,service_role;
revoke all on function public.create_market_offer(uuid,bigint) from public,anon;
grant execute on function public.create_market_offer(uuid,bigint) to authenticated;
revoke all on function private.cancel_market_offer(uuid) from public,anon;
grant execute on function private.cancel_market_offer(uuid) to authenticated,service_role;
revoke all on function public.cancel_market_offer(uuid) from public,anon;
grant execute on function public.cancel_market_offer(uuid) to authenticated;
revoke all on function private.respond_market_offer(uuid,boolean) from public,anon;
grant execute on function private.respond_market_offer(uuid,boolean) to authenticated,service_role;
revoke all on function public.respond_market_offer(uuid,boolean) from public,anon;
grant execute on function public.respond_market_offer(uuid,boolean) to authenticated;
revoke all on function private.get_market_offers() from public,anon;
grant execute on function private.get_market_offers() to authenticated,service_role;
revoke all on function public.get_market_offers() from public,anon;
grant execute on function public.get_market_offers() to authenticated;

revoke all on function private.get_guild_wars() from public,anon;
grant execute on function private.get_guild_wars() to authenticated,service_role;
revoke all on function public.get_guild_wars() from public,anon;
grant execute on function public.get_guild_wars() to authenticated;
revoke all on function private.get_guild_collective_booster_status() from public,anon;
grant execute on function private.get_guild_collective_booster_status() to authenticated,service_role;
revoke all on function public.get_guild_collective_booster_status() from public,anon;
grant execute on function public.get_guild_collective_booster_status() to authenticated;
revoke all on function private.claim_guild_collective_booster() from public,anon;
grant execute on function private.claim_guild_collective_booster() to authenticated,service_role;
revoke all on function public.claim_guild_collective_booster() from public,anon;
grant execute on function public.claim_guild_collective_booster() to authenticated;

revoke all on function private.join_tournament() from public,anon;
grant execute on function private.join_tournament() to authenticated,service_role;
revoke all on function public.join_tournament() from public,anon;
grant execute on function public.join_tournament() to authenticated;
revoke all on function private.leave_tournament() from public,anon;
grant execute on function private.leave_tournament() to authenticated,service_role;
revoke all on function public.leave_tournament() from public,anon;
grant execute on function public.leave_tournament() to authenticated;
revoke all on function private.get_tournament_hub() from public,anon;
grant execute on function private.get_tournament_hub() to authenticated,service_role;
revoke all on function public.get_tournament_hub() from public,anon;
grant execute on function public.get_tournament_hub() to authenticated;

revoke all on function private.get_cosmetics_hub() from public,anon;
grant execute on function private.get_cosmetics_hub() to authenticated,service_role;
revoke all on function public.get_cosmetics_hub() from public,anon;
grant execute on function public.get_cosmetics_hub() to authenticated;
revoke all on function private.equip_cosmetic(text) from public,anon;
grant execute on function private.equip_cosmetic(text) to authenticated,service_role;
revoke all on function public.equip_cosmetic(text) from public,anon;
grant execute on function public.equip_cosmetic(text) to authenticated;

select private.ensure_weekly_guild_wars();
select private.ensure_active_tournament();
