-- Guild War Gyms: server-authoritative territory control, persistent defender HP,
-- 25k coin heals, and Supabase Realtime updates.

create table if not exists public.guild_war_gyms (
  id uuid primary key default gen_random_uuid(),
  war_id uuid not null references public.guild_wars(id) on delete cascade,
  slot smallint not null check (slot between 1 and 5),
  gym_key text not null,
  gym_name text not null,
  owner_guild_id text references public.guilds(id) on delete set null,
  controlled_since timestamptz not null default now(),
  capture_count integer not null default 0 check (capture_count >= 0),
  last_attacked_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (war_id, slot),
  unique (war_id, gym_key),
  unique (id, war_id)
);

create table if not exists public.guild_war_gym_defenders (
  id uuid primary key default gen_random_uuid(),
  war_id uuid not null references public.guild_wars(id) on delete cascade,
  gym_id uuid not null,
  player_id uuid not null references public.players(id) on delete cascade,
  guild_id text not null references public.guilds(id) on delete cascade,
  card_id text not null references public.cards(id) on delete restrict,
  max_hp integer not null check (max_hp > 0),
  current_hp integer not null check (current_hp >= 0 and current_hp <= max_hp),
  max_damage integer not null check (max_damage > 0),
  wins integer not null default 0 check (wins >= 0),
  placed_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint guild_war_gym_defenders_gym_war_fk
    foreign key (gym_id, war_id)
    references public.guild_war_gyms(id, war_id)
    on delete cascade,
  unique (war_id, player_id)
);

create table if not exists public.guild_war_gym_events (
  id bigint generated by default as identity primary key,
  war_id uuid not null references public.guild_wars(id) on delete cascade,
  gym_id uuid not null references public.guild_war_gyms(id) on delete cascade,
  event_type text not null check (event_type in ('defender_set','heal','attack','capture')),
  actor_id uuid references public.players(id) on delete set null,
  guild_id text references public.guilds(id) on delete set null,
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists guild_war_gyms_war_idx
  on public.guild_war_gyms(war_id, slot);
create index if not exists guild_war_gyms_owner_idx
  on public.guild_war_gyms(owner_guild_id, war_id);
create index if not exists guild_war_gym_defenders_gym_idx
  on public.guild_war_gym_defenders(gym_id, current_hp desc, placed_at);
create index if not exists guild_war_gym_defenders_guild_idx
  on public.guild_war_gym_defenders(guild_id, war_id);
create index if not exists guild_war_gym_events_war_idx
  on public.guild_war_gym_events(war_id, created_at desc);
create index if not exists guild_war_gym_events_gym_idx
  on public.guild_war_gym_events(gym_id, created_at desc);

alter table public.guild_war_gyms enable row level security;
alter table public.guild_war_gym_defenders enable row level security;
alter table public.guild_war_gym_events enable row level security;

drop policy if exists "guild war gyms readable" on public.guild_war_gyms;
create policy "guild war gyms readable"
on public.guild_war_gyms for select to authenticated using (true);

drop policy if exists "guild war gym defenders readable" on public.guild_war_gym_defenders;
create policy "guild war gym defenders readable"
on public.guild_war_gym_defenders for select to authenticated using (true);

drop policy if exists "guild war gym events readable" on public.guild_war_gym_events;
create policy "guild war gym events readable"
on public.guild_war_gym_events for select to authenticated using (true);

grant select on public.guild_war_gyms to authenticated;
grant select on public.guild_war_gym_defenders to authenticated;
grant select on public.guild_war_gym_events to authenticated;

create or replace function private.guild_gym_card_hp(p_card_id text)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select greatest(
    10,
    least(
      1000,
      coalesce(
        nullif(regexp_replace(coalesce(c.tcg_data->>'hp',''), '[^0-9]', '', 'g'), '')::integer,
        50
      )
    )
  )
  from public.cards c
  where c.id = p_card_id;
$$;

create or replace function private.guild_gym_card_damage(p_card_id text)
returns integer
language sql
stable
security definer
set search_path = ''
as $$
  select greatest(
    10,
    least(
      1000,
      coalesce(
        (
          select max(
            coalesce(
              nullif(substring(coalesce(a->>'damage','') from '([0-9]+)'), '')::integer,
              0
            )
          )
          from jsonb_array_elements(
            case
              when jsonb_typeof(c.tcg_data->'attacks') = 'array' then c.tcg_data->'attacks'
              else '[]'::jsonb
            end
          ) a
        ),
        10
      )
    )
  )
  from public.cards c
  where c.id = p_card_id;
$$;

create or replace function private.ensure_guild_war_gyms(p_war_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_war public.guild_wars%rowtype;
begin
  select * into v_war
  from public.guild_wars
  where id = p_war_id;

  if not found then
    raise exception 'WAR_NOT_FOUND';
  end if;

  insert into public.guild_war_gyms(
    war_id, slot, gym_key, gym_name, owner_guild_id, controlled_since
  )
  values
    (v_war.id, 1, 'pewter',    'Ginásio de Pewter',    v_war.guild_a_id, v_war.starts_at),
    (v_war.id, 2, 'cerulean',  'Ginásio de Cerulean',  v_war.guild_b_id, v_war.starts_at),
    (v_war.id, 3, 'vermilion', 'Ginásio de Vermilion', v_war.guild_a_id, v_war.starts_at),
    (v_war.id, 4, 'celadon',   'Ginásio de Celadon',   v_war.guild_b_id, v_war.starts_at),
    (v_war.id, 5, 'saffron',   'Ginásio de Saffron',   v_war.guild_a_id, v_war.starts_at)
  on conflict (war_id, slot) do nothing;
end;
$$;

create or replace function public.get_guild_war_gyms(p_war_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_result jsonb;
begin
  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  perform private.ensure_guild_war_gyms(p_war_id);

  select jsonb_build_object(
    'warId', w.id,
    'status', w.status,
    'startsAt', w.starts_at,
    'endsAt', w.ends_at,
    'guildA', jsonb_build_object('id', ga.id, 'name', ga.name, 'color', ga.color),
    'guildB', jsonb_build_object('id', gb.id, 'name', gb.name, 'color', gb.color),
    'gyms', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', gym.id,
          'slot', gym.slot,
          'key', gym.gym_key,
          'name', gym.gym_name,
          'ownerGuild', case
            when owner.id is null then null
            else jsonb_build_object('id', owner.id, 'name', owner.name, 'color', owner.color)
          end,
          'controlledSince', gym.controlled_since,
          'captureCount', gym.capture_count,
          'lastAttackedAt', gym.last_attacked_at,
          'defenders', coalesce((
            select jsonb_agg(
              jsonb_build_object(
                'id', d.id,
                'playerId', d.player_id,
                'username', p.username,
                'guildId', d.guild_id,
                'cardId', d.card_id,
                'pokemonName', c.pokemon_name,
                'imageSmall', c.image_small,
                'rarity', c.rarity,
                'types', c.types,
                'maxHp', d.max_hp,
                'currentHp', d.current_hp,
                'maxDamage', d.max_damage,
                'wins', d.wins,
                'placedAt', d.placed_at,
                'updatedAt', d.updated_at
              )
              order by (d.current_hp > 0) desc, d.placed_at, d.id
            )
            from public.guild_war_gym_defenders d
            join public.players p on p.id = d.player_id
            join public.cards c on c.id = d.card_id
            where d.gym_id = gym.id
          ), '[]'::jsonb)
        )
        order by gym.slot
      )
      from public.guild_war_gyms gym
      left join public.guilds owner on owner.id = gym.owner_guild_id
      where gym.war_id = w.id
    ), '[]'::jsonb),
    'events', coalesce((
      select jsonb_agg(to_jsonb(e) order by e.created_at desc)
      from (
        select
          ge.id,
          ge.gym_id as "gymId",
          ge.event_type as "eventType",
          ge.actor_id as "actorId",
          ge.guild_id as "guildId",
          ge.message,
          ge.metadata,
          ge.created_at as "createdAt"
        from public.guild_war_gym_events ge
        where ge.war_id = w.id
        order by ge.created_at desc
        limit 20
      ) e
    ), '[]'::jsonb)
  )
  into v_result
  from public.guild_wars w
  join public.guilds ga on ga.id = w.guild_a_id
  join public.guilds gb on gb.id = w.guild_b_id
  where w.id = p_war_id;

  if v_result is null then
    raise exception 'WAR_NOT_FOUND';
  end if;

  return v_result;
end;
$$;

create or replace function public.set_guild_war_gym_defender(
  p_war_id uuid,
  p_gym_id uuid,
  p_card_id text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_guild text;
  v_war public.guild_wars%rowtype;
  v_gym public.guild_war_gyms%rowtype;
  v_existing public.guild_war_gym_defenders%rowtype;
  v_hp integer;
  v_damage integer;
  v_username text;
  v_card_name text;
  v_id uuid;
begin
  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  perform private.ensure_guild_war_gyms(p_war_id);

  select * into v_war
  from public.guild_wars
  where id = p_war_id;

  if not found or v_war.status <> 'active' or v_war.starts_at > now() or v_war.ends_at <= now() then
    raise exception 'WAR_NOT_ACTIVE';
  end if;

  select * into v_gym
  from public.guild_war_gyms
  where id = p_gym_id and war_id = p_war_id
  for update;

  if not found then
    raise exception 'GYM_NOT_FOUND';
  end if;

  select gm.guild_id into v_actor_guild
  from public.guild_members gm
  where gm.player_id = v_actor;

  if v_actor_guild is null
     or v_actor_guild not in (v_war.guild_a_id, v_war.guild_b_id) then
    raise exception 'NOT_IN_THIS_GUILD_WAR';
  end if;

  if v_gym.owner_guild_id is distinct from v_actor_guild then
    raise exception 'GYM_NOT_OWNED_BY_YOUR_GUILD';
  end if;

  if not exists (
    select 1
    from public.player_cards pc
    join public.cards c on c.id = pc.card_id
    where pc.player_id = v_actor
      and pc.card_id = p_card_id
      and pc.quantity > 0
      and coalesce(c.tcg_data->>'supertype','Pokémon') = 'Pokémon'
  ) then
    raise exception 'CARD_NOT_OWNED_OR_NOT_POKEMON';
  end if;

  v_hp := private.guild_gym_card_hp(p_card_id);
  v_damage := private.guild_gym_card_damage(p_card_id);

  select * into v_existing
  from public.guild_war_gym_defenders
  where war_id = p_war_id and player_id = v_actor
  for update;

  if found then
    if v_existing.current_hp < v_existing.max_hp then
      raise exception 'DEFENDER_DAMAGED_CANNOT_REPLACE';
    end if;

    update public.guild_war_gym_defenders
    set gym_id = p_gym_id,
        guild_id = v_actor_guild,
        card_id = p_card_id,
        max_hp = v_hp,
        current_hp = v_hp,
        max_damage = v_damage,
        wins = 0,
        placed_at = now(),
        updated_at = now()
    where id = v_existing.id
    returning id into v_id;
  else
    insert into public.guild_war_gym_defenders(
      war_id, gym_id, player_id, guild_id, card_id,
      max_hp, current_hp, max_damage
    )
    values(
      p_war_id, p_gym_id, v_actor, v_actor_guild, p_card_id,
      v_hp, v_hp, v_damage
    )
    returning id into v_id;
  end if;

  select p.username, c.pokemon_name
  into v_username, v_card_name
  from public.players p
  cross join public.cards c
  where p.id = v_actor and c.id = p_card_id;

  insert into public.guild_war_gym_events(
    war_id, gym_id, event_type, actor_id, guild_id, message, metadata
  )
  values(
    p_war_id,
    p_gym_id,
    'defender_set',
    v_actor,
    v_actor_guild,
    '@' || coalesce(v_username,'Treinador') || ' colocou ' || coalesce(v_card_name,'Pokémon') || ' na defesa de ' || v_gym.gym_name || '.',
    jsonb_build_object('defenderId', v_id, 'cardId', p_card_id)
  );

  return jsonb_build_object(
    'defenderId', v_id,
    'gymId', p_gym_id,
    'cardId', p_card_id,
    'maxHp', v_hp,
    'currentHp', v_hp,
    'maxDamage', v_damage
  );
end;
$$;

create or replace function public.heal_guild_war_gym_defender(
  p_defender_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_def public.guild_war_gym_defenders%rowtype;
  v_gym public.guild_war_gyms%rowtype;
  v_war public.guild_wars%rowtype;
  v_actor_guild text;
  v_coins bigint;
  v_healed integer;
  v_new_hp integer;
  v_username text;
begin
  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  select * into v_def
  from public.guild_war_gym_defenders
  where id = p_defender_id;

  if not found then
    raise exception 'DEFENDER_NOT_FOUND';
  end if;

  select * into v_gym
  from public.guild_war_gyms
  where id = v_def.gym_id and war_id = v_def.war_id
  for update;

  if not found then
    raise exception 'GYM_NOT_FOUND';
  end if;

  select * into v_war
  from public.guild_wars
  where id = v_def.war_id;

  if not found or v_war.status <> 'active' or v_war.starts_at > now() or v_war.ends_at <= now() then
    raise exception 'WAR_NOT_ACTIVE';
  end if;

  select * into v_def
  from public.guild_war_gym_defenders
  where id = p_defender_id
  for update;

  if not found then
    raise exception 'DEFENDER_NOT_FOUND';
  end if;

  select gm.guild_id into v_actor_guild
  from public.guild_members gm
  where gm.player_id = v_actor;

  if v_actor_guild is null
     or v_actor_guild <> v_def.guild_id
     or v_gym.owner_guild_id is distinct from v_def.guild_id then
    raise exception 'CANNOT_HEAL_ENEMY_DEFENDER';
  end if;

  if v_def.current_hp <= 0 then
    raise exception 'DEFENDER_ALREADY_DEFEATED';
  end if;

  if v_def.current_hp >= v_def.max_hp then
    raise exception 'DEFENDER_ALREADY_FULL_HP';
  end if;

  select p.coins into v_coins
  from public.players p
  where p.id = v_actor
  for update;

  if coalesce(v_coins,0) < 25000 then
    raise exception 'INSUFFICIENT_COINS';
  end if;

  v_new_hp := least(v_def.max_hp, v_def.current_hp + 50);
  v_healed := v_new_hp - v_def.current_hp;

  update public.players
  set coins = coins - 25000
  where id = v_actor;

  update public.guild_war_gym_defenders
  set current_hp = v_new_hp,
      updated_at = now()
  where id = v_def.id;

  select username into v_username
  from public.players
  where id = v_actor;

  insert into public.guild_war_gym_events(
    war_id, gym_id, event_type, actor_id, guild_id, message, metadata
  )
  values(
    v_def.war_id,
    v_def.gym_id,
    'heal',
    v_actor,
    v_actor_guild,
    '@' || coalesce(v_username,'Treinador') || ' restaurou ' || v_healed || ' HP de um defensor por 🪙 25.000.',
    jsonb_build_object(
      'defenderId', v_def.id,
      'healedHp', v_healed,
      'costCoins', 25000,
      'currentHp', v_new_hp
    )
  );

  return jsonb_build_object(
    'defenderId', v_def.id,
    'healedHp', v_healed,
    'costCoins', 25000,
    'currentHp', v_new_hp,
    'maxHp', v_def.max_hp
  );
end;
$$;

create or replace function public.attack_guild_war_gym(
  p_war_id uuid,
  p_gym_id uuid,
  p_card_ids text[]
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_actor uuid := auth.uid();
  v_actor_guild text;
  v_war public.guild_wars%rowtype;
  v_gym public.guild_war_gyms%rowtype;
  v_def public.guild_war_gym_defenders%rowtype;
  v_team_count integer;
  v_i integer;
  v_card_id text;
  v_attacker_index integer := 1;
  v_attacker_hp integer := 0;
  v_attacker_damage integer := 0;
  v_attacker_name text;
  v_def_hp integer;
  v_defender_knockouts integer;
  v_defeated integer := 0;
  v_fainted integer := 0;
  v_alive integer := 0;
  v_rounds integer := 0;
  v_conquered boolean := false;
  v_guild_name text;
  v_actor_name text;
  v_owner_before text;
begin
  if v_actor is null then
    raise exception 'UNAUTHORIZED';
  end if;

  v_team_count := coalesce(cardinality(p_card_ids), 0);
  if v_team_count < 1 or v_team_count > 6 then
    raise exception 'ATTACK_TEAM_MUST_HAVE_1_TO_6_POKEMON';
  end if;

  if (
    select count(distinct x)
    from unnest(p_card_ids) as x
  ) <> v_team_count then
    raise exception 'ATTACK_TEAM_HAS_DUPLICATES';
  end if;

  perform private.ensure_guild_war_gyms(p_war_id);

  select * into v_war
  from public.guild_wars
  where id = p_war_id;

  if not found or v_war.status <> 'active' or v_war.starts_at > now() or v_war.ends_at <= now() then
    raise exception 'WAR_NOT_ACTIVE';
  end if;

  select * into v_gym
  from public.guild_war_gyms
  where id = p_gym_id and war_id = p_war_id
  for update;

  if not found then
    raise exception 'GYM_NOT_FOUND';
  end if;

  select gm.guild_id into v_actor_guild
  from public.guild_members gm
  where gm.player_id = v_actor;

  if v_actor_guild is null
     or v_actor_guild not in (v_war.guild_a_id, v_war.guild_b_id) then
    raise exception 'NOT_IN_THIS_GUILD_WAR';
  end if;

  if v_gym.owner_guild_id is null then
    raise exception 'GYM_HAS_NO_OWNER';
  end if;

  if v_gym.owner_guild_id = v_actor_guild then
    raise exception 'CANNOT_ATTACK_YOUR_OWN_GYM';
  end if;

  if v_gym.owner_guild_id not in (v_war.guild_a_id, v_war.guild_b_id) then
    raise exception 'INVALID_GYM_OWNER';
  end if;

  for v_i in 1..v_team_count loop
    v_card_id := p_card_ids[v_i];

    if not exists (
      select 1
      from public.player_cards pc
      join public.cards c on c.id = pc.card_id
      where pc.player_id = v_actor
        and pc.card_id = v_card_id
        and pc.quantity > 0
        and coalesce(c.tcg_data->>'supertype','Pokémon') = 'Pokémon'
    ) then
      raise exception 'ATTACK_CARD_NOT_OWNED_OR_NOT_POKEMON';
    end if;
  end loop;

  v_owner_before := v_gym.owner_guild_id;

  for v_def in
    select d.*
    from public.guild_war_gym_defenders d
    where d.gym_id = p_gym_id
      and d.war_id = p_war_id
      and d.current_hp > 0
      and d.guild_id = v_owner_before
    order by d.placed_at, d.id
    for update
  loop
    v_def_hp := v_def.current_hp;
    v_defender_knockouts := 0;

    while v_def_hp > 0 and v_attacker_index <= v_team_count loop
      if v_attacker_hp <= 0 then
        v_card_id := p_card_ids[v_attacker_index];
        v_attacker_hp := private.guild_gym_card_hp(v_card_id);
        v_attacker_damage := private.guild_gym_card_damage(v_card_id);
        select c.pokemon_name into v_attacker_name
        from public.cards c
        where c.id = v_card_id;
      end if;

      v_rounds := v_rounds + 1;
      if v_rounds > 500 then
        raise exception 'GYM_BATTLE_SAFETY_LIMIT';
      end if;

      v_def_hp := greatest(0, v_def_hp - greatest(10, v_attacker_damage));

      if v_def_hp > 0 then
        v_attacker_hp := greatest(0, v_attacker_hp - greatest(10, v_def.max_damage));

        if v_attacker_hp <= 0 then
          v_fainted := v_fainted + 1;
          v_defender_knockouts := v_defender_knockouts + 1;
          v_attacker_index := v_attacker_index + 1;
        end if;
      end if;
    end loop;

    update public.guild_war_gym_defenders
    set current_hp = v_def_hp,
        wins = wins + v_defender_knockouts,
        updated_at = now()
    where id = v_def.id;

    if v_def_hp <= 0 then
      v_defeated := v_defeated + 1;
    end if;

    if v_attacker_index > v_team_count and v_attacker_hp <= 0 then
      exit;
    end if;
  end loop;

  select count(*) into v_alive
  from public.guild_war_gym_defenders d
  where d.gym_id = p_gym_id
    and d.war_id = p_war_id
    and d.guild_id = v_owner_before
    and d.current_hp > 0;

  update public.guild_war_gyms
  set last_attacked_at = now(),
      updated_at = now()
  where id = p_gym_id;

  select p.username into v_actor_name
  from public.players p
  where p.id = v_actor;

  if v_alive = 0 then
    update public.guild_war_gyms
    set owner_guild_id = v_actor_guild,
        controlled_since = now(),
        capture_count = capture_count + 1,
        last_attacked_at = now(),
        updated_at = now()
    where id = p_gym_id;

    delete from public.guild_war_gym_defenders
    where gym_id = p_gym_id
      and war_id = p_war_id;

    select g.name into v_guild_name
    from public.guilds g
    where g.id = v_actor_guild;

    insert into public.guild_war_gym_events(
      war_id, gym_id, event_type, actor_id, guild_id, message, metadata
    )
    values(
      p_war_id,
      p_gym_id,
      'capture',
      v_actor,
      v_actor_guild,
      'Guilda ' || coalesce(v_guild_name,'sem nome') || ' domina ' || v_gym.gym_name || '.',
      jsonb_build_object(
        'previousOwnerGuildId', v_owner_before,
        'newOwnerGuildId', v_actor_guild,
        'defendersDefeated', v_defeated,
        'attackersFainted', v_fainted,
        'teamSize', v_team_count
      )
    );

    v_conquered := true;
  else
    insert into public.guild_war_gym_events(
      war_id, gym_id, event_type, actor_id, guild_id, message, metadata
    )
    values(
      p_war_id,
      p_gym_id,
      'attack',
      v_actor,
      v_actor_guild,
      '@' || coalesce(v_actor_name,'Treinador') || ' atacou ' || v_gym.gym_name || ' e derrubou ' || v_defeated || ' defensor(es).',
      jsonb_build_object(
        'defendersDefeated', v_defeated,
        'defendersRemaining', v_alive,
        'attackersFainted', v_fainted,
        'teamSize', v_team_count
      )
    );
  end if;

  return jsonb_build_object(
    'gymId', p_gym_id,
    'conquered', v_conquered,
    'ownerGuildId', case when v_conquered then v_actor_guild else v_owner_before end,
    'defendersDefeated', v_defeated,
    'defendersRemaining', case when v_conquered then 0 else v_alive end,
    'attackersFainted', v_fainted,
    'teamSize', v_team_count
  );
end;
$$;

revoke all on function public.get_guild_war_gyms(uuid) from public, anon;
revoke all on function public.set_guild_war_gym_defender(uuid,uuid,text) from public, anon;
revoke all on function public.heal_guild_war_gym_defender(uuid) from public, anon;
revoke all on function public.attack_guild_war_gym(uuid,uuid,text[]) from public, anon;

grant execute on function public.get_guild_war_gyms(uuid) to authenticated;
grant execute on function public.set_guild_war_gym_defender(uuid,uuid,text) to authenticated;
grant execute on function public.heal_guild_war_gym_defender(uuid) to authenticated;
grant execute on function public.attack_guild_war_gym(uuid,uuid,text[]) to authenticated;

alter table public.guild_war_gyms replica identity full;
alter table public.guild_war_gym_defenders replica identity full;
alter table public.guild_war_gym_events replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='guild_war_gyms'
  ) then
    alter publication supabase_realtime add table public.guild_war_gyms;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='guild_war_gym_defenders'
  ) then
    alter publication supabase_realtime add table public.guild_war_gym_defenders;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime'
      and schemaname='public'
      and tablename='guild_war_gym_events'
  ) then
    alter publication supabase_realtime add table public.guild_war_gym_events;
  end if;
end $$;
