-- Economy 2.1 permanent sinks platform.
-- Regular players are gated by RPCs until release 1.0 is completed.

create table if not exists private.economy_sink_ledger (
  id bigint generated by default as identity primary key,
  player_id uuid references public.players(id) on delete set null,
  guild_id text references public.guilds(id) on delete set null,
  sink_type text not null,
  amount_coins bigint not null check (amount_coins > 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists economy_sink_ledger_created_idx on private.economy_sink_ledger(created_at desc);
create index if not exists economy_sink_ledger_type_created_idx on private.economy_sink_ledger(sink_type,created_at desc);
create index if not exists economy_sink_ledger_player_created_idx on private.economy_sink_ledger(player_id,created_at desc);

create table if not exists public.economy_store_items (
  id text primary key,
  category text not null check (category in ('profile_frame','profile_background','card_style','deck_style','shop_theme','booster_fx','title','trophy','guild_decor')),
  name text not null,
  description text not null default '',
  icon text not null default 'sparkles',
  price_coins bigint not null check (price_coins > 0),
  rarity text not null default 'standard',
  active boolean not null default true,
  limited_starts_at timestamptz,
  limited_ends_at timestamptz,
  max_purchases_per_player integer not null default 1 check (max_purchases_per_player >= 1),
  metadata jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.player_economy_items (
  player_id uuid not null references public.players(id) on delete cascade,
  item_id text not null references public.economy_store_items(id) on delete cascade,
  quantity integer not null default 1 check (quantity > 0),
  purchased_at timestamptz not null default now(),
  primary key(player_id,item_id)
);

create table if not exists public.player_prestige (
  player_id uuid primary key references public.players(id) on delete cascade,
  prestige_level integer not null default 0 check (prestige_level >= 0),
  total_spent_coins bigint not null default 0 check (total_spent_coins >= 0),
  updated_at timestamptz not null default now()
);

create table if not exists public.player_card_customizations (
  player_id uuid not null references public.players(id) on delete cascade,
  card_id text not null references public.cards(id) on delete cascade,
  style_item_id text not null references public.economy_store_items(id) on delete restrict,
  applied_at timestamptz not null default now(),
  primary key(player_id,card_id)
);

alter table public.decks add column if not exists style_item_id text references public.economy_store_items(id) on delete set null;
alter table public.player_shops add column if not exists highlight_until timestamptz;
alter table public.players add column if not exists equipped_booster_fx_id text references public.economy_store_items(id) on delete set null;
alter table public.market_listings add column if not exists boosted_until timestamptz;
alter table public.market_listings add column if not exists boost_tier text;
create index if not exists market_listings_boosted_idx on public.market_listings(status,boosted_until desc nulls last,created_at desc);

create table if not exists public.guild_project_definitions (
  project_no integer primary key,
  name text not null,
  description text not null,
  target_coins bigint not null check (target_coins > 0),
  icon text not null default 'business',
  reward_metadata jsonb not null default '{}'::jsonb
);
create table if not exists public.guild_projects (
  id uuid primary key default gen_random_uuid(),
  guild_id text not null references public.guilds(id) on delete cascade,
  project_no integer not null,
  name text not null,
  description text not null,
  target_coins bigint not null check (target_coins > 0),
  contributed_coins bigint not null default 0 check (contributed_coins >= 0),
  status text not null default 'active' check (status in ('active','completed')),
  reward_metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  unique(guild_id,project_no)
);
create unique index if not exists guild_projects_one_active_idx on public.guild_projects(guild_id) where status='active';

create table if not exists public.guild_project_contributions (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.guild_projects(id) on delete cascade,
  guild_id text not null references public.guilds(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  amount_coins bigint not null check (amount_coins > 0),
  created_at timestamptz not null default now()
);
create index if not exists guild_project_contrib_project_idx on public.guild_project_contributions(project_id,amount_coins desc,created_at);
create index if not exists guild_project_contrib_player_idx on public.guild_project_contributions(player_id,created_at desc);

create table if not exists public.guild_upgrades (
  guild_id text not null references public.guilds(id) on delete cascade,
  upgrade_key text not null,
  level integer not null default 0 check (level >= 0),
  updated_at timestamptz not null default now(),
  primary key(guild_id,upgrade_key)
);

create table if not exists public.economy_global_projects (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  description text not null,
  target_coins bigint not null check (target_coins > 0),
  contributed_coins bigint not null default 0 check (contributed_coins >= 0),
  reward_item_id text references public.economy_store_items(id) on delete set null,
  active boolean not null default true,
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists public.economy_global_project_contributions (
  project_id uuid not null references public.economy_global_projects(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  amount_coins bigint not null default 0 check (amount_coins >= 0),
  updated_at timestamptz not null default now(),
  primary key(project_id,player_id)
);

create table if not exists public.economy_auctions (
  id uuid primary key default gen_random_uuid(),
  item_id text not null references public.economy_store_items(id) on delete restrict,
  min_bid_coins bigint not null check (min_bid_coins > 0),
  bid_increment_coins bigint not null check (bid_increment_coins > 0),
  highest_bid_coins bigint,
  highest_bidder_id uuid references public.players(id) on delete set null,
  starts_at timestamptz not null default now(),
  ends_at timestamptz not null,
  status text not null default 'active' check (status in ('active','settled','expired')),
  settled_at timestamptz,
  created_at timestamptz not null default now()
);
create table if not exists private.economy_auction_bids (
  id bigint generated by default as identity primary key,
  auction_id uuid not null references public.economy_auctions(id) on delete cascade,
  bidder_id uuid not null references public.players(id) on delete cascade,
  amount_coins bigint not null check (amount_coins > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.economy_price_recommendations (
  id bigint generated by default as identity primary key,
  generated_at timestamptz not null default now(),
  health_status text not null,
  burn_to_mint_ratio numeric,
  recommendation_type text not null,
  current_value numeric,
  suggested_value numeric,
  rationale text not null,
  active boolean not null default true
);
create table if not exists public.economy_alerts (
  id bigint generated by default as identity primary key,
  alert_key text not null,
  severity text not null check (severity in ('info','watch','critical')),
  message text not null,
  metrics jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);
create index if not exists economy_alerts_open_idx on public.economy_alerts(resolved_at,created_at desc);

alter table public.economy_store_items enable row level security;
alter table public.player_economy_items enable row level security;
alter table public.player_prestige enable row level security;
alter table public.player_card_customizations enable row level security;
alter table public.guild_project_definitions enable row level security;
alter table public.guild_projects enable row level security;
alter table public.guild_project_contributions enable row level security;
alter table public.guild_upgrades enable row level security;
alter table public.economy_global_projects enable row level security;
alter table public.economy_global_project_contributions enable row level security;
alter table public.economy_auctions enable row level security;
alter table public.economy_price_recommendations enable row level security;
alter table public.economy_alerts enable row level security;

drop policy if exists "economy store readable" on public.economy_store_items;
create policy "economy store readable" on public.economy_store_items for select to authenticated using (true);
drop policy if exists "own economy items readable" on public.player_economy_items;
create policy "own economy items readable" on public.player_economy_items for select to authenticated using (player_id=auth.uid());
drop policy if exists "own prestige readable" on public.player_prestige;
create policy "own prestige readable" on public.player_prestige for select to authenticated using (player_id=auth.uid());
drop policy if exists "own card styles readable" on public.player_card_customizations;
create policy "own card styles readable" on public.player_card_customizations for select to authenticated using (player_id=auth.uid());
drop policy if exists "guild project defs readable" on public.guild_project_definitions;
create policy "guild project defs readable" on public.guild_project_definitions for select to authenticated using (true);
drop policy if exists "guild projects readable" on public.guild_projects;
create policy "guild projects readable" on public.guild_projects for select to authenticated using (true);
drop policy if exists "guild project contrib readable" on public.guild_project_contributions;
create policy "guild project contrib readable" on public.guild_project_contributions for select to authenticated using (true);
drop policy if exists "guild upgrades readable" on public.guild_upgrades;
create policy "guild upgrades readable" on public.guild_upgrades for select to authenticated using (true);
drop policy if exists "global projects readable" on public.economy_global_projects;
create policy "global projects readable" on public.economy_global_projects for select to authenticated using (true);
drop policy if exists "own global contrib readable" on public.economy_global_project_contributions;
create policy "own global contrib readable" on public.economy_global_project_contributions for select to authenticated using (player_id=auth.uid());
drop policy if exists "auctions readable" on public.economy_auctions;
create policy "auctions readable" on public.economy_auctions for select to authenticated using (true);
drop policy if exists "economy recommendations admin readable" on public.economy_price_recommendations;
create policy "economy recommendations admin readable" on public.economy_price_recommendations for select to authenticated using (exists(select 1 from public.admin_members a where a.player_id=auth.uid()));
drop policy if exists "economy alerts admin readable" on public.economy_alerts;
create policy "economy alerts admin readable" on public.economy_alerts for select to authenticated using (exists(select 1 from public.admin_members a where a.player_id=auth.uid()));

grant select on public.economy_store_items,public.player_economy_items,public.player_prestige,public.player_card_customizations,
public.guild_project_definitions,public.guild_projects,public.guild_project_contributions,public.guild_upgrades,
public.economy_global_projects,public.economy_global_project_contributions,public.economy_auctions,
public.economy_price_recommendations,public.economy_alerts to authenticated;

insert into public.guild_project_definitions(project_no,name,description,target_coins,icon,reward_metadata) values
(1,'Centro Pokémon','Construa a primeira estrutura permanente da sede.',250000,'medkit','{"upgradeKey":"hq","level":1,"decor":"centro_pokemon"}'),
(2,'Hall da Fama','Crie uma galeria coletiva para feitos da guilda.',750000,'trophy','{"upgradeKey":"hall","level":1,"decor":"hall_da_fama"}'),
(3,'Estátua Lendária','Erga um monumento visível no prestígio da guilda.',1500000,'sparkles','{"upgradeKey":"monument","level":1,"decor":"estatua_lendaria"}'),
(4,'Liga da Guilda','Transforme a sede em um centro de competição.',3000000,'shield','{"upgradeKey":"league","level":1,"decor":"liga_da_guilda"}'),
(5,'Sede Master','Complete a primeira grande evolução visual da guilda.',5000000,'business','{"upgradeKey":"hq","level":2,"decor":"sede_master"}')
on conflict(project_no) do update set name=excluded.name,description=excluded.description,target_coins=excluded.target_coins,icon=excluded.icon,reward_metadata=excluded.reward_metadata;

insert into public.cosmetic_definitions(id,kind,name,description,icon,primary_color,secondary_color,unlock_type,threshold,unlock_key,sort_order,active) values
('coin_frame_indigo','frame','Aura Indigo','Moldura comprada na Loja de Luxo.','sparkles','#6A7CFF','#111831','coin_shop',0,null,200,true),
('coin_frame_champion','frame','Champion Gold','Moldura de prestígio dourada.','trophy','#FFD447','#2B2310','coin_shop',0,null,201,true),
('coin_frame_master','frame','Master Nebula','Moldura endgame para colecionadores.','planet','#C493FF','#20172F','coin_shop',0,null,202,true),
('coin_bg_kanto','background','Kanto Night','Background premium inspirado na jornada Kanto.','moon','#5B8CFF','#081323','coin_shop',0,null,210,true),
('coin_bg_indigo','background','Indigo League','Background de campeão da Liga.','ribbon','#FFD447','#1C1830','coin_shop',0,null,211,true),
('coin_bg_master','background','Master Collection','Background endgame da coleção.','diamond','#8AE7FF','#111827','coin_shop',0,null,212,true)
on conflict(id) do nothing;

insert into public.economy_store_items(id,category,name,description,icon,price_coins,rarity,metadata,sort_order) values
('coin_frame_indigo','profile_frame','Aura Indigo','Moldura premium para seu perfil.','sparkles',40000,'rare','{"cosmeticId":"coin_frame_indigo"}',10),
('coin_frame_champion','profile_frame','Champion Gold','Moldura dourada para treinadores avançados.','trophy',150000,'epic','{"cosmeticId":"coin_frame_champion"}',11),
('coin_frame_master','profile_frame','Master Nebula','Moldura de luxo para o endgame.','planet',500000,'master','{"cosmeticId":"coin_frame_master"}',12),
('coin_bg_kanto','profile_background','Kanto Night','Background noturno da região de Kanto.','moon',30000,'rare','{"cosmeticId":"coin_bg_kanto"}',20),
('coin_bg_indigo','profile_background','Indigo League','Background da Liga Indigo.','ribbon',120000,'epic','{"cosmeticId":"coin_bg_indigo"}',21),
('coin_bg_master','profile_background','Master Collection','Background para colecionadores de elite.','diamond',400000,'master','{"cosmeticId":"coin_bg_master"}',22),
('card_style_holo','card_style','Holo Edge','Contorno holográfico para uma carta favorita.','color-wand',25000,'rare','{"applyCost":15000}',30),
('card_style_champion','card_style','Champion Seal','Selo de campeão aplicado a uma carta.','ribbon',90000,'epic','{"applyCost":40000}',31),
('card_style_master','card_style','Master Pedestal','Apresentação máxima para uma carta de coleção.','diamond',300000,'master','{"applyCost":100000}',32),
('deck_style_classic','deck_style','Deck Classic','Ícone e moldura clássica para decks.','albums',20000,'standard','{"applyCost":10000}',40),
('deck_style_elite','deck_style','Deck Elite','Acabamento premium para seu deck.','shield',80000,'epic','{"applyCost":25000}',41),
('deck_style_master','deck_style','Deck Master','Visual endgame para o deck principal.','trophy',300000,'master','{"applyCost":75000}',42),
('shop_theme_royal','shop_theme','Loja Royal','Tema premium para sua loja no mercado.','storefront',60000,'rare','{"themeStyle":"royal"}',50),
('shop_theme_neon','shop_theme','Loja Neon','Tema luminoso para a loja do Trainer Market.','flash',250000,'epic','{"themeStyle":"neon"}',51),
('shop_theme_master','shop_theme','Loja Master','Tema endgame de marketplace.','diamond',750000,'master','{"themeStyle":"master"}',52),
('booster_fx_spark','booster_fx','Spark Opening','Efeito visual especial para abertura de booster.','flash',100000,'rare','{}',60),
('booster_fx_champion','booster_fx','Champion Opening','Efeito dourado de abertura.','sparkles',500000,'epic','{}',61),
('booster_fx_master','booster_fx','Master Opening','Efeito máximo para abertura de packs.','diamond',2000000,'master','{}',62),
('title_collector','title','Colecionador de Elite','Título de prestígio econômico.','ribbon',250000,'epic','{}',70),
('trophy_million','trophy','Troféu Milionário','Troféu permanente para quem investe pesado na coleção.','trophy',1000000,'master','{}',71),
('trophy_legend','trophy','Monumento Lendário','Símbolo de prestígio extremo.','medal',2500000,'legendary','{}',72),
('global_indigo_builder','trophy','Fundador da Liga Indigo','Recompensa do primeiro projeto global da comunidade.','construct',1,'legacy','{"notForDirectSale":true}',90)
on conflict(id) do update set category=excluded.category,name=excluded.name,description=excluded.description,icon=excluded.icon,price_coins=excluded.price_coins,rarity=excluded.rarity,metadata=excluded.metadata,sort_order=excluded.sort_order;

insert into public.economy_global_projects(code,name,description,target_coins,reward_item_id,active,starts_at)
values('build_indigo_league_v1','Construção da Liga Indigo','A comunidade inteira contribui Coins para erguer a primeira grande obra da Economy 2.0.',15000000,'global_indigo_builder',true,now())
on conflict(code) do nothing;
