import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { Screen } from '@/components/Screen';
import { getBattleSpectatorState } from '@/services/adminLaunchTools';
import { useAppTheme } from '@/theme/ThemeProvider';

export default function BattleSpectatorScreen(){
  const{id}=useLocalSearchParams<{id:string}>();const{colors}=useAppTheme();
  const[data,setData]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState<string|null>(null);
  const load=useCallback(async(silent=false)=>{if(!id)return;try{if(!silent)setLoading(true);setError(null);setData(await getBattleSpectatorState(String(id)));}catch(e){if(!silent)setError(e instanceof Error?e.message:'Esta batalha não permite espectadores.');}finally{if(!silent)setLoading(false);}},[id]);
  useFocusEffect(useCallback(()=>{void load();},[load]));
  useEffect(()=>{if(!data||['completed','cancelled','declined'].includes(data.battle?.status))return;const t=setInterval(()=>void load(true),1800);return()=>clearInterval(t);},[data?.battle?.status,load]);
  const players=useMemo(()=>Object.fromEntries((data?.players??[]).map((p:any)=>[p.id,p])),[data?.players]);
  const latest=data?.resolvedTurns?.[data.resolvedTurns.length-1]?.result;
  return <Screen title="Modo Espectador" subtitle="Somente informações já reveladas. Escolhas secretas e golpes ainda não resolvidos nunca aparecem.">
    <View style={[styles.privacy,{backgroundColor:colors.accentSoft,borderColor:colors.accent}]}><Ionicons name="eye" size={21} color={colors.accent}/><Text style={[styles.privacyText,{color:colors.muted}]}>Proteção de informação ativa. Batalhas valendo Coins ou cartas não podem ser abertas para espectadores externos.</Text></View>
    {loading?<ActivityIndicator size="large" color={colors.yellow}/>:null}{error?<View style={[styles.error,{borderColor:'#D96575'}]}><Ionicons name="lock-closed" size={21} color="#FF8290"/><Text style={[styles.errorText,{color:colors.text}]}>{error}</Text></View>:null}
    {data?<><View style={[styles.scoreboard,{backgroundColor:colors.surface,borderColor:colors.border}]}><Player name={players[data.battle.challengerId]?.username} score={data.battle.challengerScore}/><View style={styles.center}><Text style={[styles.vs,{color:colors.yellow}]}>VS</Text><Text style={[styles.status,{color:colors.accent}]}>{String(data.battle.status).toUpperCase()}</Text><Text style={[styles.round,{color:colors.muted}]}>Rodada {data.battle.activeRound}</Text></View><Player name={players[data.battle.opponentId]?.username} score={data.battle.opponentScore} right/></View>
      <View style={styles.fighters}>{(data.fighters??[]).filter((f:any)=>f.round===data.battle.activeRound).map((f:any)=><View key={f.playerId+'-'+f.cardId} style={[styles.fighter,{backgroundColor:colors.surface,borderColor:colors.border}]}>{f.image?<Image source={{uri:f.image}} style={styles.image} resizeMode="contain"/>:null}<View style={{flex:1}}><Text style={[styles.name,{color:colors.text}]}>{f.name}</Text><Text style={[styles.hp,{color:f.currentHp<=0?'#FF8290':'#65D894'}]}>HP {f.currentHp}/{f.maxHp}</Text><Text style={[styles.small,{color:colors.muted}]}>{(f.types??[]).join(' / ').toUpperCase()}{f.status?' • '+String(f.status).toUpperCase():''}</Text></View></View>)}</View>
      {latest?<View style={[styles.latest,{backgroundColor:colors.surface,borderColor:colors.border}]}><Text style={[styles.latestTitle,{color:colors.text}]}>Último turno resolvido</Text><Action row={latest.firstMove}/><Action row={latest.secondMove}/></View>:null}
      <Text style={[styles.small,{color:colors.muted,textAlign:'center'}]}>Atualização automática enquanto a batalha estiver ativa.</Text>
    </>:null}
  </Screen>;
}
function Player({name,score,right=false}:{name:string;score:number;right?:boolean}){const{colors}=useAppTheme();return <View style={[styles.player,right&&{alignItems:'flex-end'}]}><Text numberOfLines={1} style={[styles.playerName,{color:colors.text}]}>@{name??'Treinador'}</Text><Text style={[styles.playerScore,{color:colors.yellow}]}>{score}</Text></View>;}
function Action({row}:{row:any}){const{colors}=useAppTheme();if(!row)return null;return <View style={[styles.action,{backgroundColor:colors.surfaceAlt,borderColor:colors.border}]}><Ionicons name="flash" size={16} color={colors.accent}/><View style={{flex:1}}><Text style={[styles.actionTitle,{color:colors.text}]}>{row.move??row.identifier??'Ação'}</Text><Text style={[styles.small,{color:colors.muted}]}>dano {row.damage??0}{row.critical?' • CRÍTICO':''}{Number(row.effectiveness??1)>1?' • SUPER EFETIVO':''}</Text></View></View>;}
const styles=StyleSheet.create({privacy:{borderRadius:16,borderWidth:1,padding:10,flexDirection:'row',alignItems:'center',gap:8},privacyText:{flex:1,fontSize:7.5,lineHeight:11},error:{borderRadius:16,borderWidth:1,padding:12,flexDirection:'row',gap:8,alignItems:'center'},errorText:{fontSize:9,flex:1},scoreboard:{borderRadius:19,borderWidth:1,padding:12,flexDirection:'row',alignItems:'center'},player:{flex:1},playerName:{fontSize:11,fontWeight:'900'},playerScore:{fontSize:27,fontWeight:'900'},center:{width:100,alignItems:'center'},vs:{fontSize:22,fontWeight:'900'},status:{fontSize:7,fontWeight:'900',marginTop:2},round:{fontSize:7,marginTop:2},fighters:{flexDirection:'row',flexWrap:'wrap',gap:8},fighter:{flexGrow:1,flexBasis:230,minWidth:210,borderRadius:16,borderWidth:1,padding:9,flexDirection:'row',alignItems:'center',gap:8},image:{width:70,height:70},name:{fontSize:11,fontWeight:'900'},hp:{fontSize:9,fontWeight:'900',marginTop:3},small:{fontSize:7.2,lineHeight:11,marginTop:2},latest:{borderRadius:16,borderWidth:1,padding:10,gap:6},latestTitle:{fontSize:12,fontWeight:'900'},action:{borderRadius:12,borderWidth:1,padding:8,flexDirection:'row',alignItems:'center',gap:7},actionTitle:{fontSize:9,fontWeight:'900'}});
